import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

const root = process.cwd();
const read = (file: string) => readFileSync(join(root, file), 'utf8');

describe('layout and flow audit regressions', () => {
  it('keeps private admin routes out of public marketing chrome', () => {
    const routeChrome = read('components/layout/RouteChrome.tsx');
    const middleware = read('middleware.ts');
    const toolsLayoutClient = read('app/tools/ToolsLayoutClient.tsx');
    const operatorLayout = read('app/operator/layout.tsx');
    const operatorCommandStrip = read('components/OperatorCommandStrip.tsx');
    const adminUsageAnalytics = read('app/admin/usage-analytics/page.tsx');
    const adminAiUsage = read('app/admin/ai-usage/page.tsx');
    const adminCosts = read('app/admin/costs/page.tsx');
    const adminIncome = read('app/admin/income/page.tsx');
    const adminDeleteRequests = read('app/admin/delete-requests/page.tsx');
    const adminDiscordBridge = read('app/admin/discord-bridge/page.tsx');
    const adminTrials = read('app/admin/trials/page.tsx');
    const adminOutcomes = read('app/admin/outcomes/page.tsx');
    const adminScalper = read('app/admin/scalper/page.tsx');

    expect(routeChrome).toContain("pathname.startsWith('/admin')");
    expect(routeChrome).toContain('!isAdminRoute && !isOperatorRoute && !isV2Route && <Header />');
    expect(routeChrome).toContain("pathname.startsWith('/tools') || isAdminRoute || isOperatorRoute");
    expect(middleware).toContain("if (pathname === '/operator' || pathname.startsWith('/operator/'))");
    expect(middleware).toContain("url.pathname = '/auth';");
    expect(middleware).toContain('return withNoIndexHeaders(NextResponse.redirect(url));');
    expect(operatorLayout).toContain("export const dynamic = 'force-dynamic';");
    expect(operatorLayout).toContain('export const revalidate = 0;');
    expect(toolsLayoutClient).not.toContain('Operator HUD');
    expect(toolsLayoutClient).not.toContain('<OperatorCommandStrip />');
    expect(operatorCommandStrip).toContain('Research Flow: {flowStatus}');
    expect(operatorCommandStrip).toContain('Review {displayAction(state.action)}');
    expect(operatorCommandStrip).not.toContain('Operator Flow: {flowStatus}');
    expect(operatorCommandStrip).not.toContain('Awaiting Execution');
    expect(adminUsageAnalytics).toContain('Usage Analytics');
    expect(adminUsageAnalytics).toContain('Feature Adoption (30d)');
    expect(adminUsageAnalytics).toContain('{ label: "Scanner", users: safeAdoption.scanner_users, code: "SCN" }');
    expect(adminUsageAnalytics).toContain('{f.code} · {f.label}');
    expect(adminUsageAnalytics).not.toContain('📈 Usage Analytics');
    expect(adminUsageAnalytics).not.toContain('icon: "🔍"');
    expect(adminAiUsage).toContain('AI Usage Analytics');
    expect(adminAiUsage).toContain('{ id: "overview", label: "Daily Stats" }');
    expect(adminAiUsage).not.toContain('🤖 AI Usage Analytics');
    expect(adminAiUsage).not.toContain('📊 Daily Stats');
    expect(adminCosts).toContain('AI Cost Tracker');
    expect(adminCosts).toContain('30-Day Token Breakdown:');
    expect(adminCosts).not.toContain('💰 AI Cost Tracker');
    expect(adminCosts).not.toContain('📊 30-Day Token Breakdown:');
    expect(adminIncome).toContain('Income & Expenses');
    expect(adminIncome).toContain('Revenue History');
    expect(adminIncome).not.toContain('💵 Income & Expenses');
    expect(adminIncome).not.toContain('📊 Revenue History');
    expect(adminDeleteRequests).toContain('Delete Requests');
    expect(adminDeleteRequests).toContain('GDPR Deletion Checklist');
    expect(adminDeleteRequests).toContain('CLEAR');
    expect(adminDeleteRequests).not.toContain('🗑️ Delete Requests');
    expect(adminDeleteRequests).not.toContain('📋 GDPR Deletion Checklist');
    expect(adminDiscordBridge).toContain('CORE MSP PAGES');
    expect(adminDiscordBridge).toContain('code: "CORE"');
    expect(adminDiscordBridge).toContain('Test sent to ${channelKey}');
    expect(adminDiscordBridge).toContain('Compliance Reminder');
    expect(adminDiscordBridge).not.toContain('emoji:');
    expect(adminDiscordBridge).not.toContain('📊 CORE MSP PAGES');
    expect(adminDiscordBridge).not.toContain('✅ Test sent');
    expect(adminTrials).toContain('Grant Trial Access');
    expect(adminTrials).toContain('All Trials ({trials.length})');
    expect(adminTrials).not.toContain('🎟️ Grant Trial Access');
    expect(adminTrials).not.toContain('📋 All Trials');
    expect(adminOutcomes).toContain('Signal Outcomes');
    expect(adminOutcomes).toContain('Run Labeler Now');
    expect(adminOutcomes).toContain('expired:{(labelerResult.breakdown as Record<string, number>).expired ?? 0}');
    expect(adminOutcomes).not.toContain('🎯 Signal Outcomes');
    expect(adminOutcomes).not.toContain('⚡ Run Labeler Now');
    expect(adminScalper).toContain('function signalCode');
    expect(adminScalper).toContain("return 'BULL';");
    expect(adminScalper).toContain('Scalping Scanner');
    expect(adminScalper).toContain("{loading ? 'Scanning…' : 'Scan Now'}");
    expect(adminScalper).toContain('SCLP');
    expect(adminScalper).toContain('code="ATR"');
    expect(adminScalper).not.toContain('function signalDot');
    expect(adminScalper).not.toContain('⚡ Scalping Scanner');
    expect(adminScalper).not.toContain('🔍 Scan Now');
  });

  it('positions the homepage around workflow and product proof instead of generic hero art', () => {
    const hero = read('components/home/Hero.tsx');
    const commandHub = read('components/home/CommandHub.tsx');
    const workflows = read('lib/toolWorkflows.ts');
    const parkedDashboard = read('components/home/TradePermissionDashboard.tsx');

    expect(hero).toContain('Educational market intelligence');
    expect(hero).toContain('No brokerage execution. No financial advice.');
    expect(hero).toContain('Open Scanner Preview');
    expect(hero).not.toContain('/logos/landing-hero.png');

    expect(commandHub.indexOf('<Hero />')).toBeLessThan(commandHub.indexOf('Start with the workflow'));
    expect(commandHub.indexOf('Start with the workflow')).toBeLessThan(commandHub.indexOf('<HomePreviewStrip />'));
    expect(commandHub).toContain('Core workflow tools');
    expect(commandHub).toContain('One research path, five decisions.');
    expect(commandHub).toContain('const workflowSteps = [');
    expect(commandHub).not.toContain('Core Scanners');
    expect(commandHub).not.toContain('v2 Platform Surfaces');
    expect(commandHub).not.toContain('FeaturedTile');
    expect(workflows).toContain("{ href: '/tools', label: 'Workflow' }");
    expect(parkedDashboard).toContain('const FALLBACK_CANDIDATES: Candidate[] = [];');
    expect(parkedDashboard).toContain('Research Alignment Matrix');
    expect(parkedDashboard).toContain('Alignment-Filtered Observations');
    expect(parkedDashboard).toContain('Research guard active');
    expect(parkedDashboard).not.toContain('Trade Permission Matrix');
    expect(parkedDashboard).not.toContain('Permission-Filtered Candidates');
    expect(parkedDashboard).not.toContain("'Enter'");
  });

  it('keeps account plan copy from exposing permission-engine language', () => {
    const accountPage = read('app/account/page.tsx');
    const workspaceAccount = read('app/tools/workspace/AccountSection.tsx');

    expect(accountPage).toContain('Research risk framework');
    expect(workspaceAccount).toContain('Research risk framework');
    expect(accountPage).not.toContain('Brain / Permission Engine');
    expect(workspaceAccount).not.toContain('Brain / Permission Engine');
  });

  it('keeps public resource guides from exposing private operator language', () => {
    const resourcesPage = read('app/resources/page.tsx');
    const platformGuide = read('app/resources/platform-guide/page.tsx');
    const tradingGuides = read('app/resources/trading-guides/page.tsx');
    const openInterestGuide = read('app/guide/open-interest/page.tsx');
    const toolGuides = read('lib/guides/toolGuides.ts');
    const platformKnowledge = read('lib/prompts/platformKnowledge.ts');

    expect(resourcesPage).toContain('research checklists');
    expect(platformGuide).toContain('Market Research Dashboard');
    expect(platformGuide).toContain('Treat dashboard bias as context, not a trigger.');
    expect(platformGuide).toContain('Compare derivatives evidence before increasing confidence in a scenario.');
    expect(tradingGuides).toContain('Research checklist');
    expect(tradingGuides).toContain('Review state');
    expect(openInterestGuide).toContain('How to Read Open Interest');
    expect(openInterestGuide).toContain('code: "UP"');
    expect(openInterestGuide).toContain('Positioning Lens:');
    expect(openInterestGuide).toContain('Review bullish reversal evidence');
    expect(openInterestGuide).toContain('Stress-test invalidation');
    expect(openInterestGuide).not.toContain('📊 How to Read Open Interest');
    expect(openInterestGuide).not.toContain('💡 Key Insight');
    expect(openInterestGuide).not.toContain('🎓 Summary Cheat Sheet');
    expect(openInterestGuide).not.toContain('Look for longs');
    expect(openInterestGuide).not.toContain('Tighten stops');
    expect(toolGuides).toContain('Private Research Dashboard');
    expect(toolGuides).toContain('internal research state, not public advice');
    expect(platformKnowledge).toContain('/operator — Private Research Dashboard');
    expect(platformKnowledge).toContain('No public recommendation or broker execution.');
    expect(resourcesPage).not.toContain('operator checklists');
    expect(platformGuide).not.toContain('Operator Dashboard');
    expect(platformGuide).not.toContain('sizing aggressively');
    expect(platformGuide).not.toContain('immediate entries');
    expect(tradingGuides).not.toContain('Operator checklist');
    expect(tradingGuides).not.toContain('Permission state');
    expect(toolGuides).not.toContain('execute, and review');
    expect(platformKnowledge).not.toContain('control tower');
  });

  it('keeps the Tools page discoverable while preserving the guided workflow', () => {
    const toolsPage = read('app/tools/page.tsx');
    const workflows = read('lib/toolWorkflows.ts');
    const toolCatalog = read('lib/toolCatalog.ts');
    const watchlistsPage = read('app/tools/watchlists/page.tsx');
    const watchlistsLayout = read('app/tools/watchlists/layout.tsx');
    const portfolioLayout = read('app/tools/portfolio/layout.tsx');
    const journalLayout = read('app/tools/journal/layout.tsx');
    const backtestLayout = read('app/tools/backtest/layout.tsx');
    const alertsLayout = read('app/tools/alerts/layout.tsx');
    const aiAnalystPage = read('app/tools/ai-analyst/page.tsx');
    const aiAnalystLayout = read('app/tools/ai-analyst/layout.tsx');
    const aiToolsPage = read('app/tools/ai-tools/page.tsx');
    const aiToolsLayout = read('app/tools/ai-tools/layout.tsx');
    const earningsPage = read('app/tools/earnings/page.tsx');
    const earningsLayout = read('app/tools/earnings/layout.tsx');
    const earningsCalendarPage = read('app/tools/earnings-calendar/page.tsx');
    const earningsCalendarLayout = read('app/tools/earnings-calendar/layout.tsx');
    const mobileNav = read('components/MobileNav.tsx');
    const commandHub = read('components/home/CommandHub.tsx');
    const toolsNavBar = read('components/ToolsNavBar.tsx');
    const onboardingChecklist = read('components/OnboardingChecklist.tsx');
    const pricing = read('components/Pricing.tsx');
    const partnerDemo = read('app/partners/demo/page.tsx');
    const email = read('lib/email.ts');
    const discordBridge = read('lib/discord-bridge.ts');
    const pushServer = read('lib/pushServer.ts');
    const notificationRouter = read('worker/notification-router.ts');
    const operatorPage = read('app/operator/page.tsx');
    const goldenEggFeature = read('src/features/goldenEgg/GoldenEggPage.tsx');
    const scannerPage = read('app/tools/scanner/page.tsx');
    const alertsWidget = read('components/AlertsWidget.tsx');
    const watchlistWidget = read('components/WatchlistWidget.tsx');
    const explorerActionGrid = read('components/explorer/ExplorerActionGrid.tsx');
    const tradeIdeasSection = read('components/derivatives/TradeIdeasSection.tsx');
    const optionsTerminalView = read('components/options-terminal/OptionsTerminalView.tsx');
    const optionsScannerPage = read('components/options/OptionsScannerPage.tsx');
    const alertsCheckRoute = read('app/api/alerts/check/route.ts');
    const testEmailRoute = read('app/api/test-email/route.ts');
    const workflowEventsRoute = read('app/api/workflow/events/route.ts');
    const platformKnowledge = read('lib/prompts/platformKnowledge.ts');
    const nextConfig = read('next.config.mjs');
    const sitemap = read('app/sitemap.ts');
    const staticToolsPreview = read('public/tools-preview.html');

    expect(toolsPage).toContain('Your MSP research workflow.');
    expect(toolsPage).toContain('Workflow map');
    expect(toolsPage).toContain('Open Tool Directory');
    expect(toolsPage).toContain('Tool directory');
    expect(toolsPage).toContain('Tool directory for direct access.');
    expect(toolsPage).toContain('Access does not depend on My Pages');
    expect(toolsPage).toContain('const featuredDirectoryKeys = new Set');
    expect(toolsPage).toContain('TOOL_CATALOG.filter');
    expect(toolsPage).toContain('TOOL_CATEGORIES.map');
    expect(toolsPage).toContain('function DirectoryToolCard');
    expect(toolsPage).toContain('h-8 w-8 shrink-0 items-center justify-center rounded-md');
    expect(toolsPage).toContain('h-6 w-6 shrink-0 items-center justify-center rounded');
    expect(toolCatalog).toContain('short visual code for quick scanning');
    expect(toolCatalog).toContain("icon: 'DB'");
    expect(toolCatalog).toContain("icon: 'GE'");
    expect(toolCatalog).toContain("icon: 'BT'");
    expect(toolCatalog).not.toContain("icon: '🥚'");
    expect(toolCatalog).not.toContain("icon: '📊'");
    expect(toolCatalog).not.toContain("icon: '🧪'");
    expect(partnerDemo).toContain('icon: "SCAN"');
    expect(partnerDemo).toContain('icon: "AI"');
    expect(partnerDemo).toContain('Completed: no execution capability, broker connections, or order submission');
    expect(partnerDemo).not.toContain('icon: "📊"');
    expect(partnerDemo).not.toContain('✅ 350+ text changes');
    expect(toolsPage.indexOf('id="workflow"')).toBeLessThan(toolsPage.indexOf('id="all-tools"'));
    expect(toolsPage).toContain('Recommended start');
    expect(toolsPage).toContain('Start here');
    expect(toolsPage).toContain('Recommended next:');
    expect(toolsPage).toContain('aria-label="Workflow command header"');
    expect(toolsPage).toContain('function WorkflowMetric');
    expect(toolsPage).toContain('label="Steps"');
    expect(toolsPage).toContain('label="Tools"');
    expect(toolsPage).toContain('label="Categories"');
    expect(toolsPage).toContain('label="Next Check"');
    expect(toolsPage).toContain('Open Market Scanner');
    expect(toolsPage).not.toContain('text-4xl font-black tracking-tight sm:text-5xl');
    expect(workflows).toContain('Inspect market mechanics');
    expect(toolsPage).toContain("mechanics: 'Next: test the research idea in Backtest.'");
    expect(toolsPage).toContain('<details id="advanced"');
    expect(toolsPage).toContain('Specialist tools after the core workflow is clear.');
    expect(workflows.indexOf("{ href: '/tools/golden-egg', label: 'Golden Egg' }")).toBeLessThan(workflows.indexOf("{ href: '/tools/terminal', label: 'Terminal' }"));
    expect(workflows.indexOf("{ href: '/tools/terminal', label: 'Terminal' }")).toBeLessThan(workflows.indexOf("{ href: '/tools/workspace?tab=backtest', label: 'Backtest' }"));
    expect(workflows).toContain("id: 'mechanics'");
    expect(workflows).toContain('3. Inspect market mechanics');
    expect(workflows).toContain("{ href: '/tools/terminal', label: 'Terminal', description: 'Close calendar, options, crypto, flow, and time-confluence checks before backtesting.', tier: 'pro', role: 'primary' }");
    expect(toolCatalog).toContain("href: '/tools/workspace?tab=watchlists'");
    expect(toolCatalog).toContain("href: '/tools/workspace?tab=portfolio'");
    expect(toolCatalog).toContain("href: '/tools/workspace?tab=journal'");
    expect(toolCatalog).toContain("href: '/tools/workspace?tab=backtest'");
    expect(toolCatalog).toContain("href: '/tools/workspace?tab=alerts'");
    expect(toolCatalog).toContain("href: '/tools/terminal?tab=options-confluence'");
    expect(toolCatalog).toContain("href: '/tools/terminal?tab=options-flow'");
    expect(toolCatalog).toContain("href: '/tools/terminal?tab=options-terminal'");
    expect(toolCatalog).toContain("href: '/tools/explorer?tab=movers'");
    expect(toolCatalog).toContain("href: '/tools/explorer?tab=heatmap'");
    expect(toolCatalog).toContain("href: '/tools/explorer?tab=crypto'");
    expect(toolCatalog).toContain("href: '/tools/explorer?tab=macro'");
    expect(toolCatalog).toContain("href: '/tools/dashboard?tab=crypto'");
    expect(toolCatalog).toContain("href: '/tools/research?tab=calendar'");
    expect(watchlistsPage).toContain("redirect('/tools/workspace?tab=watchlists')");
    expect(watchlistsLayout).toContain("canonical: 'https://marketscannerpros.app/tools/workspace?tab=watchlists'");
    expect(watchlistsLayout).toContain('index: false');
    expect(portfolioLayout).toContain("canonical: 'https://marketscannerpros.app/tools/workspace?tab=portfolio'");
    expect(journalLayout).toContain("canonical: 'https://marketscannerpros.app/tools/workspace?tab=journal'");
    expect(backtestLayout).toContain("canonical: 'https://marketscannerpros.app/tools/workspace?tab=backtest'");
    expect(alertsLayout).toContain("canonical: 'https://marketscannerpros.app/tools/workspace?tab=alerts'");
    expect(portfolioLayout).toContain('robots: { index: false, follow: true }');
    expect(journalLayout).toContain('robots: { index: false, follow: true }');
    expect(backtestLayout).toContain('robots: { index: false, follow: true }');
    expect(alertsLayout).toContain('robots: { index: false, follow: true }');
    expect(sitemap).not.toContain("'/tools/watchlists'");
    expect(toolCatalog).toContain("href: '/tools/scanner'" );
    expect(toolCatalog).toContain("label: 'ARCA AI Panel'");
    expect(toolCatalog).toContain("href: '/tools/research?tab=earnings'");
    expect(aiAnalystPage).toContain('redirect("/tools/scanner")');
    expect(aiAnalystLayout).toContain("canonical: 'https://marketscannerpros.app/tools/scanner'");
    expect(aiAnalystLayout).toContain('index: false');
    expect(aiToolsPage).toContain("redirect('/tools')");
    expect(aiToolsLayout).toContain("canonical: 'https://marketscannerpros.app/tools'");
    expect(aiToolsLayout).toContain('index: false');
    expect(earningsPage).toContain("redirect('/tools/research?tab=earnings')");
    expect(earningsLayout).toContain("canonical: 'https://marketscannerpros.app/tools/research?tab=earnings'");
    expect(earningsCalendarPage).toContain("redirect('/tools/research?tab=earnings')");
    expect(earningsCalendarLayout).toContain("canonical: 'https://marketscannerpros.app/tools/research?tab=earnings'");
    expect(mobileNav).toContain('href="/tools/scanner" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>ARCA AI Panel</a>');
    expect(mobileNav).toContain('href="/tools/research?tab=earnings" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Earnings Calendar</a>');
    expect(mobileNav).toContain('href="/tools/workspace?tab=portfolio" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Portfolio</a>');
    expect(mobileNav).toContain('href="/tools/workspace?tab=backtest" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Backtest</a>');
    expect(mobileNav).toContain('href="/tools/workspace?tab=journal" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Journal</a>');
    expect(mobileNav).toContain('href="/tools/golden-egg" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Golden Egg</a>');
    expect(mobileNav).toContain('href="/tools/terminal?tab=options-confluence" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Options Confluence Scanner</a>');
    expect(mobileNav).toContain('href="/tools/explorer?tab=crypto" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Crypto Explorer</a>');
    expect(mobileNav).toContain('href="/tools/explorer?tab=equity" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Equity Explorer</a>');
    expect(mobileNav).toContain('href="/tools/research?tab=calendar" className="py-2 hover:text-emerald-400" onClick={() => setIsOpen(false)}>Economic Calendar</a>');
    expect(mobileNav).not.toContain('href="/tools/deep-analysis"');
    expect(mobileNav).not.toContain('href="/tools/options-confluence"');
    expect(mobileNav).not.toContain('href="/tools/crypto-explorer"');
    expect(mobileNav).not.toContain('href="/tools/equity-explorer"');
    expect(mobileNav).not.toContain('href="/tools/economic-calendar"');
    expect(commandHub).toContain("href: '/tools/workspace?tab=backtest'");
    expect(commandHub).toContain("href: '/tools/terminal?tab=options-flow'");
    expect(commandHub).toContain("href: '/tools/dashboard?tab=crypto'");
    expect(toolsNavBar).toContain('["Portfolio", "/tools/workspace?tab=portfolio"]');
    expect(toolsNavBar).toContain('["Journal", "/tools/workspace?tab=journal"]');
    expect(toolsNavBar).toContain('["Markets", "/tools/explorer"]');
    expect(toolsNavBar).toContain('["Options", "/tools/terminal?tab=options-terminal"]');
    expect(toolsNavBar).toContain('["Crypto", "/tools/explorer?tab=crypto-command"]');
    expect(toolsNavBar).toContain('["Derivatives", "/tools/terminal?tab=crypto"]');
    expect(toolsNavBar).toContain("tier === 'pro_trader' ? 'Pro Trader' : tier === 'pro' ? 'Pro' : 'Free'");
    expect(toolsNavBar).not.toContain('⭐ Pro Trader');
    expect(toolsNavBar).not.toContain('✨ Pro');
    expect(onboardingChecklist).toContain("href: '/tools/workspace?tab=journal'");
    expect(onboardingChecklist).toContain("href: '/tools/workspace?tab=portfolio'");
    expect(onboardingChecklist).toContain("code: 'WL'");
    expect(onboardingChecklist).toContain("done ? 'OK' : step.code");
    expect(onboardingChecklist).not.toContain("icon: '🔍'");
    expect(onboardingChecklist).not.toContain("done ? '✅'");
    expect(pricing).toContain('ARCA AI (50/day)');
    expect(pricing).toContain('Market Movers & News');
    expect(pricing).toContain('Full backtesting engine');
    expect(pricing).not.toContain('🤖');
    expect(pricing).not.toContain('📊');
    expect(pricing).not.toContain('📈');
    expect(partnerDemo).toContain('href: "/tools/workspace?tab=backtest"');
    expect(partnerDemo).toContain('href: "/tools/terminal?tab=options-confluence"');
    expect(partnerDemo).toContain('href: "/tools/explorer?tab=crypto-command"');
    expect(email).toContain("['ARCA AI Panel', '/tools/scanner']");
    expect(email).toContain("['Portfolio', '/tools/workspace?tab=portfolio']");
    expect(email).toContain("['Journal', '/tools/workspace?tab=journal']");
    expect(email).toContain('https://app.marketscannerpros.app/tools/workspace?tab=alerts');
    expect(email).toContain("const alertCode = isSmartAlert ? 'AI' : 'PX';");
    expect(email).toContain("['SCAN', 'Unlimited Scanner'");
    expect(email).toContain('Welcome to MarketScanner Pros ${planName}');
    expect(email).not.toContain('🎉 Welcome');
    expect(email).not.toContain('📧 Email sent');
    expect(discordBridge).toContain('url: `${APP_BASE}/tools/scanner`');
    expect(discordBridge).toContain('url: `${APP_BASE}/tools/workspace?tab=alerts`');
    expect(discordBridge).toContain("'msp-scanner':       { code: 'SCAN'");
    expect(discordBridge).toContain("title: 'Scanner — Top Setups'");
    expect(discordBridge).toContain("title: `Golden Egg — ${egg.symbol}`");
    expect(discordBridge).toContain("value: state.squeeze ? 'Active' : 'Inactive'");
    expect(discordBridge).toContain("value: 'Connected'");
    expect(discordBridge).not.toContain('emoji:');
    expect(discordBridge).not.toContain('🔥 Squeeze');
    expect(discordBridge).not.toContain('✅ Connected');
    expect(pushServer).toContain("data: { url: '/tools/workspace?tab=portfolio', type: 'portfolio_alert', symbol }");
    expect(pushServer).toContain('title: `Price Alert: ${symbol}`');
    expect(pushServer).toContain("title: 'New Scanner Signals'");
    expect(pushServer).not.toContain('📊 Price Alert');
    expect(pushServer).not.toContain('🔍 New Scanner Signals');
    expect(notificationRouter).toContain("href: '/tools/workspace?tab=journal'");
    expect(notificationRouter).toContain("href || '/tools/workspace?tab=journal'");
    expect(operatorPage).toContain('/tools/workspace?tab=alerts&symbol=');
    expect(operatorPage).toContain('/tools/workspace?tab=backtest&symbol=');
    expect(operatorPage).toContain('/tools/workspace?tab=portfolio&symbol=');
    expect(operatorPage).toContain('/tools/workspace?tab=journal&source=operator');
    expect(operatorPage).toContain("markets: '/tools/explorer'");
    expect(operatorPage).toContain("movers: '/tools/explorer?tab=movers'");
    expect(operatorPage).toContain('/tools/golden-egg?symbol=');
    expect(goldenEggFeature).toContain('/tools/workspace?tab=portfolio&add=');
    expect(goldenEggFeature).toContain('/tools/workspace?tab=alerts&symbol=');
    expect(goldenEggFeature).toContain('/tools/workspace?tab=backtest&symbol=');
    expect(scannerPage).toContain('/tools/workspace?tab=alerts&symbol=');
    expect(alertsWidget).toContain('return `/tools/workspace?tab=journal&${params.toString()}`;');
    expect(alertsWidget).toContain('/tools/workspace?tab=backtest&symbol=');
    expect(watchlistWidget).toContain('alert: `/tools/workspace?tab=alerts&symbol=${encodedSymbol}`');
    expect(watchlistWidget).toContain('deep: `/tools/golden-egg?symbol=${encodedSymbol}`');
    expect(watchlistWidget).toContain('flow: `/tools/terminal?tab=options-confluence&symbol=${encodedSymbol}`');
    expect(explorerActionGrid).toContain('/tools/workspace?tab=alerts&symbol=');
    expect(explorerActionGrid).toContain('/tools/workspace?tab=journal&note=');
    expect(explorerActionGrid).toContain('/tools/terminal?tab=time-confluence&symbol=');
    expect(tradeIdeasSection).toContain('/tools/workspace?tab=alerts&symbol=');
    expect(tradeIdeasSection).toContain('/tools/workspace?tab=journal&note=');
    expect(optionsTerminalView).toContain('/tools/workspace?tab=journal&prefill=true&');
    expect(optionsScannerPage).toContain('/tools/workspace?tab=journal&${params.toString()}');
    expect(alertsCheckRoute).toContain('https://marketscannerpros.app/tools/workspace?tab=alerts');
    expect(testEmailRoute).toContain('https://app.marketscannerpros.app/tools/workspace?tab=alerts');
    expect(workflowEventsRoute).toContain("route: '/tools/workspace?tab=journal'");
    expect(platformKnowledge).toContain('/tools/workspace?tab=backtest — Backtester');
    expect(platformKnowledge).toContain('/tools/workspace?tab=portfolio — Portfolio Tracker');
    expect(platformKnowledge).toContain('/tools/workspace?tab=journal — Trade Journal');
    expect(platformKnowledge).toContain('/tools/workspace?tab=alerts — Alerts');
    expect(platformKnowledge).toContain('/tools/terminal?tab=options-confluence — Options Confluence Scanner');
    expect(platformKnowledge).toContain('/tools/dashboard?tab=crypto — Crypto Derivatives Dashboard');
    expect(platformKnowledge).toContain('/tools/explorer?tab=equity — Equity Explorer');
    expect(platformKnowledge).toContain('/tools/research?tab=calendar — Economic Calendar');
    expect(nextConfig).toContain("{ source: '/tools/earnings', destination: '/tools/research?tab=earnings', permanent: true }");
    expect(nextConfig).toContain("{ source: '/tools/earnings-calendar', destination: '/tools/research?tab=earnings', permanent: true }");
    expect(nextConfig).toContain("{ source: '/tools/options-confluence', destination: '/tools/terminal?tab=options-confluence', permanent: true }");
    expect(nextConfig).toContain("{ source: '/tools/crypto-dashboard', destination: '/tools/dashboard?tab=crypto', permanent: true }");
    expect(nextConfig).toContain("{ source: '/tools/market-movers', destination: '/tools/explorer?tab=movers', permanent: true }");
    expect(nextConfig).toContain("{ source: '/tools/news', destination: '/tools/research', permanent: true }");
    expect(sitemap).not.toContain("'/tools/ai-analyst'");
    expect(sitemap).not.toContain("'/tools/portfolio'");
    expect(sitemap).not.toContain("'/tools/journal'");
    expect(sitemap).not.toContain("'/tools/backtest'");
    expect(sitemap).not.toContain("'/tools/alerts'");
    expect(sitemap).not.toContain("'/tools/options-confluence'");
    expect(sitemap).not.toContain("'/tools/news'");
    expect(sitemap).not.toContain("'/tools/market-movers'");
    expect(sitemap).not.toContain("'/tools/economic-calendar'");
    expect(sitemap).not.toContain("'/tools/heatmap'");
    expect(sitemap).not.toContain("'/tools/crypto-dashboard'");
    expect(sitemap).not.toContain("'/tools/equity-explorer'");
    expect(toolsPage).not.toContain('rounded-3xl border border-white/10 bg-slate-900/70');
    expect(staticToolsPreview).toContain('<meta name="robots" content="noindex, follow" />');
    expect(staticToolsPreview).toContain('<meta http-equiv="refresh" content="0; url=/tools" />');
    expect(staticToolsPreview).toContain('Tools Preview Moved');
    expect(staticToolsPreview).not.toContain('TradingView tools built');
    expect(staticToolsPreview).not.toContain('Request Free Trial');
    expect(staticToolsPreview).not.toContain('random signals');
  });

  it('makes Terminal the handoff from Golden Egg to Backtest', () => {
    const terminalPage = read('app/tools/terminal/page.tsx');
    const terminalLayout = read('app/tools/terminal/layout.tsx');
    const toolsLayoutClient = read('app/tools/ToolsLayoutClient.tsx');
    const terminalShell = read('components/terminal/TerminalShell.tsx');
    const optionsConfluencePage = read('app/tools/options-confluence/page.tsx');
    const optionsFlowPage = read('app/tools/options-flow/page.tsx');
    const confluenceScannerPage = read('app/tools/confluence-scanner/page.tsx');
    const timeScannerPage = read('components/time/TimeScannerPage.tsx');

    expect(terminalPage).toContain('Workflow step 3 · Market mechanics check');
    expect(terminalPage).toContain('Use Terminal before Backtest.');
    expect(terminalPage).toContain('Golden Egg validates the symbol. Terminal checks whether timing, options positioning, flow, crypto derivatives, and close-calendar pressure support the scenario before you test it historically.');
    expect(terminalPage).toContain('function TerminalMetric');
    expect(terminalPage).toContain('aria-label="Terminal command header"');
    expect(terminalPage).toContain('<TerminalMetric label="Symbol" value={sym}');
    expect(terminalPage).toContain('<TerminalMetric label="Active Lens" value={tab}');
    expect(terminalPage).toContain('<TerminalMetric label="Data State" value={terminalDataState}');
    expect(terminalPage).toContain('<TerminalMetric label="Next Check" value={nextTerminalAction}');
    expect(terminalPage).toContain('<ComplianceDisclaimer compact variant={asset === \'crypto\' ? \'cryptoDerivatives\' : \'options\'} />');
    expect(terminalPage).toContain('function TerminalTabRail');
    expect(terminalPage).toContain('const TERMINAL_TAB_PARAM_MAP');
    expect(terminalPage).toContain("'options-confluence': 'Options Confluence'");
    expect(terminalPage).toContain("'crypto-terminal': 'Crypto'");
    expect(terminalPage).toContain("'time-scanner': 'Time Confluence'");
    expect(terminalPage).toContain('useSearchParams');
    expect(terminalPage).toContain('if (requestedTab && requestedTab !== tab) setTab(requestedTab);');
    expect(terminalPage).toContain('Mechanics workbench');
    expect(terminalPage).toContain('Timing first, then positioning, flow, and final confluence before Backtest.');
    expect(terminalPage).toContain('grid grid-cols-2 gap-1 sm:grid-cols-3 lg:grid-cols-5');
    expect(terminalPage).toContain('rounded-md border px-3 py-1.5 text-left transition');
    expect(terminalPage).not.toContain('min-w-[9rem] shrink-0 rounded-md border px-3 py-1.5');
    expect(terminalPage).toContain('Terminal subview');
    expect(terminalPage).toContain('<TerminalSubviewFrame tab="Time Gravity" symbol={sym}>');
    expect(terminalPage).toContain('Back to Golden Egg');
    expect(terminalPage).toContain('Continue to Backtest');
    expect(terminalPage).toContain("href=\"/tools/workspace?tab=backtest\"");
    expect(terminalPage).toContain('<OptionsConfluence embeddedInTerminal />');
    expect(terminalPage).toContain('<OptionsFlow embeddedInTerminal />');
    expect(terminalPage).toContain('<ConfluenceScanner embeddedInTerminal />');
    expect(terminalPage).not.toContain('<SectionHeader title="Terminal"');
    expect(terminalPage).not.toContain('ComplianceDisclaimer collapsible variant');
    expect(terminalPage).not.toContain("'? Refresh'");
    expect(toolsLayoutClient).toContain("const showFavoriteButton = pageKey !== 'dashboard' && pathname !== '/tools/terminal' && pathname !== '/tools/scanner';");
    expect(toolsLayoutClient).not.toContain("'/tools/terminal',");
    expect(terminalShell).toContain('embedded?: boolean');
    expect(terminalShell).toContain("{!embedded && <header");
    expect(optionsConfluencePage).toContain('embeddedInTerminal = false');
    expect(optionsConfluencePage).toContain('embedded={embeddedInTerminal}');
    expect(optionsConfluencePage).toContain("icon: 'OK'");
    expect(optionsConfluencePage).toContain("icon: 'NO'");
    expect(optionsConfluencePage).toContain('AI Watching');
    expect(optionsConfluencePage).toContain('EXPANSION CONTINUATION');
    expect(optionsConfluencePage).toContain('Bear Case');
    expect(optionsConfluencePage).toContain('Framework invalidation: Below ${result.aiMarketState.thesis.invalidationLevel.toFixed(2)}');
    expect(optionsConfluencePage).toContain('LIVE DATA STATUS: Nasdaq BX OK • FMV Options OK');
    expect(optionsConfluencePage).toContain('DECISION LADDER');
    expect(optionsConfluencePage).not.toContain("icon: '✔'");
    expect(optionsConfluencePage).not.toContain("icon: '✖'");
    expect(optionsConfluencePage).not.toContain('✓tag');
    expect(optionsConfluencePage).not.toContain('★ AI Watching');
    expect(optionsConfluencePage).not.toContain('🚫');
    expect(optionsConfluencePage).not.toContain('🚀 EXPANSION CONTINUATION');
    expect(optionsConfluencePage).not.toContain('🏊');
    expect(optionsConfluencePage).not.toContain('🐻 Bear Case');
    expect(optionsConfluencePage).not.toContain('⛔ Framework invalidation');
    expect(optionsConfluencePage).not.toContain('🪜 DECISION LADDER');
    expect(optionsFlowPage).toContain('embeddedInTerminal = false');
    expect(optionsFlowPage).toContain('{!embeddedInTerminal && <ComplianceDisclaimer variant="options" />}');
    expect(optionsFlowPage).toContain('function patternCode');
    expect(optionsFlowPage).toContain("if (p === 'block') return 'BLK';");
    expect(optionsFlowPage).toContain("return { label: 'Bullish Demand', color: 'var(--msp-bull)' };");
    expect(optionsFlowPage).toContain("{loading ? 'Analyzing...' : 'Analyze Flow'}");
    expect(optionsFlowPage).toContain('Net Premium Flow');
    expect(optionsFlowPage).toContain('Large Flow Estimate');
    expect(optionsFlowPage).not.toContain('patternEmoji');
    expect(optionsFlowPage).not.toContain('🔍 Analyze Flow');
    expect(optionsFlowPage).not.toContain('📊</div>');
    expect(confluenceScannerPage).toContain('<TimeScannerPage embeddedInTerminal={embeddedInTerminal} />');
    expect(timeScannerPage).toContain("embeddedInTerminal ? 'px-0 py-0' : 'px-4 py-4 lg:px-6 lg:py-6'");
    expect(timeScannerPage).toContain("scalping: 'Scalp 15m'");
    expect(timeScannerPage).toContain("macro_monthly: 'Monthly'");
    expect(timeScannerPage).toContain('Market Pressure Engine');
    expect(timeScannerPage).toContain('Intraday Equity Close Schedule');
    expect(timeScannerPage).toContain('Time Gravity Map');
    expect(timeScannerPage).not.toContain("scalping: '⚡ Scalp 15m'");
    expect(timeScannerPage).not.toContain('🧲 Time Gravity Map');
    expect(terminalLayout).not.toContain('Trade Terminal');
  });

  it('noindexes redirected child route layouts and points canonicals at hub tabs', () => {
    const legacyCanonicals: Array<[string, string]> = [
      ['app/tools/news/layout.tsx', 'https://marketscannerpros.app/tools/research'],
      ['app/tools/economic-calendar/layout.tsx', 'https://marketscannerpros.app/tools/research?tab=calendar'],
      ['app/tools/market-movers/layout.tsx', 'https://marketscannerpros.app/tools/explorer?tab=movers'],
      ['app/tools/heatmap/layout.tsx', 'https://marketscannerpros.app/tools/explorer?tab=heatmap'],
      ['app/tools/equity-explorer/layout.tsx', 'https://marketscannerpros.app/tools/explorer?tab=equity'],
      ['app/tools/crypto-dashboard/layout.tsx', 'https://marketscannerpros.app/tools/dashboard?tab=crypto'],
      ['app/tools/macro/layout.tsx', 'https://marketscannerpros.app/tools/explorer?tab=macro'],
      ['app/tools/options-confluence/layout.tsx', 'https://marketscannerpros.app/tools/terminal?tab=options-confluence'],
      ['app/tools/options-terminal/layout.tsx', 'https://marketscannerpros.app/tools/terminal?tab=options-terminal'],
      ['app/tools/crypto-terminal/layout.tsx', 'https://marketscannerpros.app/tools/terminal?tab=crypto'],
      ['app/tools/confluence-scanner/layout.tsx', 'https://marketscannerpros.app/tools/terminal?tab=time-confluence'],
      ['app/tools/deep-analysis/layout.tsx', 'https://marketscannerpros.app/tools/golden-egg'],
      ['app/tools/intraday-charts/layout.tsx', 'https://marketscannerpros.app/tools/golden-egg'],
    ];

    legacyCanonicals.forEach(([file, canonical]) => {
      const layout = read(file);
      expect(layout).toContain('robots: { index: false, follow: true }');
      expect(layout).toContain(`alternates: { canonical: '${canonical}' }`);
    });
  });

  it('keeps Workspace Backtest as one panel instead of nested result tabs', () => {
    const workspacePage = read('app/tools/workspace/page.tsx');
    const backtestHub = read('components/backtest/BacktestHub.tsx');

    expect(workspacePage).toContain('<BacktestPage embeddedInWorkspace />');
    expect(workspacePage).toContain('Workflow memory');
    expect(workspacePage).toContain('Watchlists, journal, portfolio, learning, backtest, alerts, and account settings in one compact workbench.');
    expect(workspacePage).toContain('rounded-lg border border-[var(--msp-border)] bg-[var(--msp-panel-2)] px-3 py-2');
    expect(workspacePage).toContain('shrink-0 rounded-md border px-3 py-1.5 text-[11px]');
    expect(workspacePage).not.toContain('<SectionHeader title="Workspace"');
    expect(workspacePage).toContain('useEffect(() => {');
    expect(workspacePage).toContain("const requestedTab = TABS.find(t => t.toLowerCase() === searchParams.get('tab')?.toLowerCase());");
    expect(workspacePage).toContain('if (requestedTab && requestedTab !== tab) setTab(requestedTab);');
    expect(backtestHub).toContain('embeddedInWorkspace = false');
    expect(backtestHub).toContain('Backtest method');
    expect(backtestHub).toContain('Choose one engine, then read the full result stack below.');
    expect(backtestHub).toContain('const showTabbedResults = !embeddedInWorkspace;');
    expect(backtestHub).toContain('{showTabbedResults && (');
    expect(backtestHub).toContain("{(!showTabbedResults || resultTab === 'Summary') && (");
    expect(backtestHub).toContain("{(!showTabbedResults || resultTab === 'Equity Curve') && (");
    expect(backtestHub).toContain("{(!showTabbedResults || resultTab === 'Trades') && (");
    expect(backtestHub).toContain("{(!showTabbedResults || resultTab === 'Diagnostics') && result.diagnostics && (");
  });

  it('keeps Workspace Journal compact with a focused drawer', () => {
    const workspacePage = read('app/tools/workspace/page.tsx');
    const journalPage = read('components/journal/JournalPage.tsx');
    const journalRoute = read('app/tools/journal/page.tsx');
    const journalLayout = read('components/journal/layout/JournalLayout.tsx');
    const journalCommand = read('components/journal/layer1/JournalCommandBar.tsx');
    const tradeDrawer = read('components/journal/drawer/TradeDrawer.tsx');

    expect(workspacePage).toContain('<JournalPageV1 tier={tier} embeddedInWorkspace />');
    expect(journalRoute).toContain('<ComplianceDisclaimer compact />');
    expect(journalRoute).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(journalPage).toContain('embeddedInWorkspace = false');
    expect(journalPage).toContain("embeddedInWorkspace ? 'px-0 py-0' : 'px-4 py-4 md:px-6'");
    expect(journalPage).toContain('embeddedInWorkspace={embeddedInWorkspace}');
    expect(journalLayout).toContain('embeddedInWorkspace?: boolean');
    expect(journalCommand).toContain('Journal review');
    expect(journalCommand).toContain('Historical journal, live open P&L, and review evidence for your saved trades.');
    expect(journalCommand).toContain('rounded-md border border-emerald-500/30 bg-emerald-500/20 px-3 py-1.5 text-xs');
    expect(journalCommand).toContain('New Trade</button>');
    expect(journalCommand).toContain('Export</button>');
    expect(tradeDrawer).toContain('embeddedInWorkspace = false');
    expect(tradeDrawer).toContain('max-w-xl p-5 md:rounded-l-xl');
    expect(tradeDrawer).toContain('New journal entry');
    expect(tradeDrawer).toContain('Close Panel');
    expect(tradeDrawer).not.toContain('>Done</button>');
  });

  it('keeps Workspace Portfolio compact without a wrapped inner tab grid', () => {
    const workspacePage = read('app/tools/workspace/page.tsx');
    const portfolioPage = read('app/tools/portfolio/page.tsx');

    expect(workspacePage).toContain('<PortfolioV1 embeddedInWorkspace />');
    expect(portfolioPage).toContain('embeddedInWorkspace = false');
    expect(portfolioPage).toContain('Portfolio review');
    expect(portfolioPage).toContain('Recorded paper positions, exposure, cash controls, and descriptive risk analytics.');
    expect(portfolioPage).toContain('Kelly Criterion Parameters');
    expect(portfolioPage).toContain('Position Estimate Results');
    expect(portfolioPage).toContain("? 'Elevated Drawdown'");
    expect(portfolioPage).toContain("const riskStateCode = isRiskEvent ? 'RISK' : isRiskElevated ? 'ELEVATED' : 'STABLE';");
    expect(portfolioPage).toContain('Risk event markers: {isRiskEvent ? \'Active\' : isRiskElevated ? \'Elevated\' : \'Stable\'}');
    expect(portfolioPage).toContain("icon=\"PF\"");
    expect(portfolioPage).toContain('Concentration warning');
    expect(portfolioPage).toContain("embeddedInWorkspace ? 'flex gap-2 overflow-x-auto pb-1' : 'grid gap-2 md:grid-cols-5'");
    expect(portfolioPage).toContain("embeddedInWorkspace ? 'min-w-fit shrink-0 px-3 py-1.5 text-[11px]' : 'px-3 py-2 text-xs'");
    expect(portfolioPage).toContain("{ key: 'add-manual', label: 'Add Position' }");
    expect(portfolioPage).toContain('{!embeddedInWorkspace && <ComplianceDisclaimer compact />}');
    expect(portfolioPage).toContain('{!embeddedInWorkspace && (');
    expect(portfolioPage).toContain('>Close</button>');
    expect(portfolioPage).toContain('>Delete</button>');
    expect(portfolioPage).not.toContain('📐 Kelly Criterion');
    expect(portfolioPage).not.toContain('📊 Position Estimate Results');
    expect(portfolioPage).not.toContain('riskStateIcon');
    expect(portfolioPage).not.toContain('🔒');
    expect(portfolioPage).not.toContain('➕ Add Position');
    expect(portfolioPage).not.toContain('🔄');
    expect(portfolioPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(portfolioPage).not.toContain('>✕</button>');
    expect(portfolioPage).not.toContain('>✕ Delete</button>');
    expect(portfolioPage).not.toContain("{ key: 'add-manual', label: '➕ Add Position' }");
  });

  it('keeps Dashboard as a morning research start page with compact secondary lenses', () => {
    const dashboardPage = read('app/tools/dashboard/page.tsx');
    const explorerPage = read('app/tools/explorer/page.tsx');
    const favoritesPanel = read('components/FavoritesPanel.tsx');
    const edgeInsightCards = read('components/intelligence/EdgeInsightCards.tsx');
    const cryptoDashboard = read('app/tools/crypto-dashboard/page.tsx');
    const macroDashboard = read('app/tools/macro/page.tsx');

    expect(dashboardPage).toContain('Morning Research Start');
    expect(dashboardPage).toContain('function DashboardMetric');
    expect(dashboardPage).toContain('function PanelHeader');
    expect(dashboardPage).toContain('function MoverRow');
    expect(dashboardPage).toContain('min-h-[3.1rem] rounded-md border border-white/10');
    expect(dashboardPage).toContain('aria-label="Dashboard command header"');
    expect(dashboardPage).toContain('Morning command dashboard');
    expect(dashboardPage).toContain('Open the research queue, then validate one symbol.');
    expect(dashboardPage).toContain('Scanner cache, movers, calendar risk, and headlines are compressed into a morning review path.');
    expect(dashboardPage).toContain('Start Scanner');
    expect(dashboardPage).toContain('Validate Symbol');
    expect(dashboardPage).toContain('Open Journal');
    expect(dashboardPage).toContain('const researchQueueCount = scannerQueue.length + moverQueue.length;');
    expect(dashboardPage).toContain('const dataHealthLabel = degradedFeeds.length');
    expect(dashboardPage).toContain('Top focus: ${topQueueSymbol}');
    expect(dashboardPage).toContain('href="/tools/workspace?tab=backtest"');
    expect(dashboardPage).toContain('href="/tools/workspace?tab=journal"');
    expect(dashboardPage).toContain('const DASH_TAB_PARAM_MAP');
    expect(dashboardPage).toContain("crypto: 'Crypto Derivatives'");
    expect(dashboardPage).toContain('if (requestedTab && requestedTab !== dashTab) setDashTab(requestedTab);');
    expect(explorerPage).toContain('const EXPLORER_TAB_PARAM_MAP');
    expect(explorerPage).toContain('Cross-market map');
    expect(explorerPage).toContain('Scan sector heat, crypto breadth, commodity context, and mover evidence before selecting one symbol. Macro context lives in the Dashboard Macro lens.');
    expect(explorerPage).toContain('aria-label="Markets command header"');
    expect(explorerPage).toContain('function MarketsMetric');
    expect(explorerPage).toContain('label="Sectors Leading"');
    expect(explorerPage).toContain('label="Crypto Cap"');
    expect(explorerPage).toContain('label="Top Gainer"');
    expect(explorerPage).toContain('label="Next Check"');
    expect(explorerPage).toContain('Open Macro Lens');
    expect(explorerPage).not.toContain("'Equity Search'");
    expect(explorerPage).not.toContain("'Crypto Search'");
    expect(explorerPage).not.toContain("'Movers Intelligence'");
    expect(explorerPage).not.toContain("'Commodities Deep'");
    expect(explorerPage).not.toContain("'Macro'");
    expect(explorerPage).not.toContain("import('@/app/tools/macro/page')");
    expect(explorerPage).toContain("'market-movers': 'Movers'");
    expect(explorerPage).toContain("'equity-explorer': 'Equity Deep-Dive'");
    expect(explorerPage).toContain("'crypto-explorer': 'Crypto Deep-Dive'");
    expect(explorerPage).toContain("'crypto-intel': 'Crypto Intel'");
    expect(explorerPage).toContain("tab === 'Crypto Intel'");
    expect(explorerPage).toContain('if (requestedTab && requestedTab !== tab) setTab(requestedTab);');
    expect(dashboardPage).toContain('aria-label="Morning research start"');
    expect(dashboardPage).toContain('Highest-evidence symbols first.');
    expect(dashboardPage).toContain('Click a symbol to open Golden Egg. Review context only; no trade instructions.');
    expect(dashboardPage).toContain('<ComplianceDisclaimer compact />');
    expect(dashboardPage).toContain('2xl:grid-cols-3');
    expect(dashboardPage).toContain('Data Health Strip');
    expect(dashboardPage).toContain('Continue Workflow');
    expect(dashboardPage).toContain('Next: review in Golden Egg');
    expect(dashboardPage).toContain('Validated queue');
    expect(dashboardPage).toContain('Live movement');
    expect(dashboardPage).toContain('Calendar risk');
    expect(dashboardPage).toContain('Context map');
    expect(dashboardPage).toContain('News context');
    expect(dashboardPage).toContain('eqGainers.slice(0, 4)');
    expect(dashboardPage).toContain('crLosers.slice(0, 4)');
    expect(dashboardPage).toContain('Dashboard lens');
    expect(dashboardPage).toContain('Switch between saved pages, live market desk, derivatives, and macro context.');
    expect(dashboardPage).toContain('rounded-md border px-3 py-1.5 text-[11px] font-semibold whitespace-nowrap');
    expect(dashboardPage).toContain("className={isPro ? 'grid items-start gap-3 xl:grid-cols-[minmax(16rem,0.55fr)_minmax(0,1.45fr)]' : ''}");
    expect(dashboardPage).toContain('<EdgeInsightCards compact />');
    expect(dashboardPage).toContain('grid gap-x-4 gap-y-1 xl:grid-cols-2');
    expect(dashboardPage).not.toContain('grid grid-cols-[5rem_1fr_6rem]');
    expect(dashboardPage).toContain('<FavoritesPanel embeddedInDashboard />');
    expect(dashboardPage).toContain('<CryptoDashboard embeddedInDashboard />');
    expect(dashboardPage).toContain('<MacroDashboard embeddedInDashboard />');
    expect(dashboardPage).not.toContain('rounded-t-md whitespace-nowrap transition-colors');
    expect(edgeInsightCards).toContain('const INSIGHT_CODES');
    expect(edgeInsightCards).toContain('Edge Profile');
    expect(edgeInsightCards).toContain('Not enough closed trades yet. Close at least 10 trades in your journal to unlock edge insights.');
    // Dashboard polish — single-source regime in eyebrow, Next Check tile, adaptive workflow,
    // empty Edge Profile collapses to one-liner.
    expect(dashboardPage).not.toContain('flex items-center gap-2 rounded-lg border border-[var(--msp-border)] bg-[var(--msp-panel-2)] px-3 py-1.5 flex-wrap');
    expect(dashboardPage).not.toContain('label={`Risk: ${regime.data.riskLevel}`}');
    expect(dashboardPage).toContain('label="Next Check"');
    expect(dashboardPage).not.toContain('label="Headlines"');
    expect(dashboardPage).toContain('const hasQueue = researchQueueCount > 0;');
    expect(dashboardPage).toContain('const nextCheckValue = hasQueue');
    expect(dashboardPage).toContain('scenarios queued');
    expect(edgeInsightCards).toContain('0/10 closed trades');
    expect(edgeInsightCards).not.toContain('Your Historical Patterns');
    expect(edgeInsightCards).not.toContain('📊');
    expect(edgeInsightCards).not.toContain('🔒');
    expect(favoritesPanel).toContain('embeddedInDashboard = false');
    expect(favoritesPanel).toContain('Saved workspace');
    expect(favoritesPanel).toContain('Manage Pages');
    expect(cryptoDashboard).toContain('embeddedInDashboard = false');
    expect(cryptoDashboard).toContain('Derivatives lens');
    expect(cryptoDashboard).toContain("embeddedInDashboard ? 'px-0 pb-6 pt-0' : 'px-4 pb-24 pt-6 md:px-6'");
    expect(cryptoDashboard).toContain('ComplianceDisclaimer compact={embeddedInDashboard}');
    expect(cryptoDashboard).toContain('WARN Funding elevated - longs paying shorts');
    expect(cryptoDashboard).toContain('BULL Negative funding - shorts paying longs');
    expect(cryptoDashboard).toContain('BULL L/S ratio favors bulls');
    expect(cryptoDashboard).toContain('BEAR L/S ratio favors bears');
    expect(cryptoDashboard).toContain('BULL OI building - risk-on mode');
    expect(cryptoDashboard).toContain('BEAR Longs getting liquidated - bearish');
    expect(cryptoDashboard).not.toContain('⚠️ Funding elevated');
    expect(cryptoDashboard).not.toContain('🟢 Negative funding');
    expect(cryptoDashboard).not.toContain('🟢 L/S ratio favors bulls');
    expect(cryptoDashboard).not.toContain('🔴 L/S ratio favors bears');
    expect(cryptoDashboard).not.toContain('🟢 OI building');
    expect(cryptoDashboard).not.toContain('🔴 Longs getting liquidated');
    expect(macroDashboard).toContain('embeddedInDashboard = false');
    expect(macroDashboard).toContain('Macro lens');
    expect(macroDashboard).toContain("embeddedInDashboard ? 'px-0 pb-6 pt-3' : 'px-4 pb-24 pt-6 md:px-6'");
    expect(macroDashboard).toContain('isAdmin && !embeddedInDashboard');

    // Dashboard lenses (My Pages / Crypto Derivatives / Macro) match the A-grade command standard.
    expect(favoritesPanel).toContain('aria-label="My Pages command header"');
    expect(favoritesPanel).toContain('function MyPagesMetric');
    expect(favoritesPanel).toContain('label="Saved"');
    expect(favoritesPanel).toContain('label="Catalog"');
    expect(favoritesPanel).toContain('label="Coverage"');
    expect(favoritesPanel).toContain('label="Next Check"');
    expect(cryptoDashboard).toContain('aria-label="Crypto Derivatives command header"');
    expect(cryptoDashboard).toContain('Bias, rotation, and volatility for the morning derivatives review.');
    expect(cryptoDashboard).toContain('>Bias<');
    expect(cryptoDashboard).toContain('>Liquidity<');
    expect(cryptoDashboard).toContain('>Funding<');
    expect(cryptoDashboard).toContain('>Next Check<');
    expect(cryptoDashboard).not.toContain("h1 className={`${embeddedInDashboard ? 'mt-1 text-base'");
    expect(macroDashboard).toContain('aria-label="Macro command header"');
    expect(macroDashboard).toContain('Global regime gate for liquidity, rates, growth, and cross-asset context.');
    expect(macroDashboard).toContain('>Permission<');
    expect(macroDashboard).toContain('>Risk State<');
    expect(macroDashboard).toContain('>Liquidity<');
    expect(macroDashboard).toContain('>Next Check<');
    expect(macroDashboard).toContain('!embeddedInDashboard && (');
    const scannerPageStandard = read('app/tools/scanner/page.tsx');
    const scanTemplatesBar = read('components/scanner/ScanTemplatesBar.tsx');
    const toolsLayoutClient = read('app/tools/ToolsLayoutClient.tsx');
    const rankExplanation = read('lib/scanner/rankExplanation.ts');
    expect(scannerPageStandard).toContain('aria-label="Scanner command header"');
    expect(scannerPageStandard).toContain('function ScannerMetric');
    expect(scannerPageStandard).toContain('label="Mode"');
    expect(scannerPageStandard).toContain('label="Data Health"');
    expect(scannerPageStandard).toContain('label="Next Check"');
    expect(scannerPageStandard).toContain('grid grid-cols-3 gap-2');
    expect(scannerPageStandard).not.toContain('flex gap-1 overflow-x-auto');
    expect(scannerPageStandard).not.toContain('min-w-[9rem] rounded-md border px-3 py-1.5 text-left transition');
    expect(scannerPageStandard).not.toContain('Active Regime Context');
    expect(scannerPageStandard).not.toContain('Regime State:');
    expect(scannerPageStandard).not.toContain('Bias: {direction.toUpperCase()}');
    expect(scannerPageStandard).toContain("Bias: {direction === 'bullish' ? 'Bullish' : direction === 'bearish' ? 'Bearish' : 'Neutral'}");
    expect(scannerPageStandard).toContain('All four levels unavailable');
    expect(scannerPageStandard).toContain('replace(/;\\s*rank is reduced when evidence is missing, stale, or liquidity is thin');
    expect(scannerPageStandard).not.toContain("background: proScanLoading ? 'rgba(16, 185, 129, 0.25)' : 'linear-gradient(135deg, #10B981 0%, #059669 100%)'");
    expect(scanTemplatesBar).not.toContain("icon: '🚀'");
    expect(scanTemplatesBar).not.toContain("icon: '💥'");
    expect(scanTemplatesBar).not.toContain("icon: '🔥'");
    expect(scanTemplatesBar).not.toContain("icon: '💪'");
    expect(scanTemplatesBar).not.toContain("icon: '🎯'");
    expect(scanTemplatesBar).toContain("icon: 'MOM'");
    expect(scanTemplatesBar).toContain("icon: 'BRK'");
    expect(scanTemplatesBar).toContain("icon: 'SQZ'");
    expect(scanTemplatesBar).toContain("icon: 'ALN'");
    expect(toolsLayoutClient).toContain("pathname !== '/tools/scanner'");
    // Boilerplate suffix in rank explanations is stripped at render-time in summarizeRankedReason.
    expect(rankExplanation).toContain('rank is reduced when evidence is missing');
  });


  it('keeps Research intelligence views embedded and compliance-safe', () => {
    const researchPage = read('app/tools/research/page.tsx');
    const newsPage = read('app/tools/news/page.tsx');
    const permissionGate = read('components/news-decision/PermissionGate.tsx');
    const economicCalendarPage = read('app/tools/economic-calendar/page.tsx');
    const toolsLayout = read('app/tools/layout.tsx');

    expect(researchPage).toContain('Research lens');
    expect(researchPage).toContain('Evidence layer');
    expect(researchPage).toContain('News, events, catalysts, earnings, and saved evidence for validating the morning research queue.');
    expect(researchPage).toContain('shrink-0 rounded-md border px-3 py-1.5 text-[11px]');
    expect(researchPage).not.toContain('<SectionHeader title="Research"');
    expect(researchPage).toContain('const TAB_PARAM_MAP');
    expect(researchPage).toContain("earnings: 'Earnings'");
    expect(researchPage).toContain("const initialTab = TAB_PARAM_MAP[(searchParams.get('tab') || '').toLowerCase()] || 'News';");
    expect(researchPage).toContain('Switch between catalyst feeds, macro calendar, earnings, saved cases, and deeper intelligence views.');
    expect(researchPage).toContain('<NewsIntelligence embeddedInResearch />');
    expect(researchPage).toContain('<EconCalendarV1 embeddedInResearch />');
    expect(newsPage).toContain('embeddedInResearch = false');
    expect(newsPage).toContain('const showAdminTools = isAdmin && !embeddedInResearch;');
    expect(newsPage).toContain("padding: embeddedInResearch ? \"0\" : \"24px 16px\"");
    expect(newsPage).toContain('Find News Evidence');
    expect(newsPage).toContain('Scenario Notes:');
    expect(newsPage).toContain('Research Mode: {catalystState.researchMode}');
    expect(newsPage).toContain("REVIEW: {catalystState.permission === 'YES' ? 'CLEAR' : catalystState.permission === 'NO' ? 'BLOCKED' : 'CAUTION'}");
    expect(newsPage).not.toContain('Allowed Trades:');
    expect(newsPage).not.toContain('Execution Mode: {catalystState.executionMode}');
    expect(permissionGate).toContain('News Review Gate');
    expect(permissionGate).toContain('Research Mode: ${gate.executionMode}');
    expect(permissionGate).not.toContain('News Condition Gate');
    expect(permissionGate).not.toContain('Execution Mode: ${gate.executionMode}');
    expect(economicCalendarPage).toContain('embeddedInResearch = false');
    expect(economicCalendarPage).toContain('type ReviewState');
    expect(economicCalendarPage).toContain('const showAdminTools = isAdmin && !embeddedInResearch;');
    expect(economicCalendarPage).toContain('REVIEW: {gate.reviewState}');
    expect(economicCalendarPage).toContain('Research Mode: ${gate.researchMode}');
    expect(economicCalendarPage).not.toContain('Override permission output');
    expect(toolsLayout).toContain('The MSP market research workflow');
  });

  it('keeps Workspace Alerts compact without duplicate compliance chrome', () => {
    const workspacePage = read('app/tools/workspace/page.tsx');
    const alertsPage = read('app/tools/alerts/page.tsx');

    expect(workspacePage).toContain('<AlertsContentV1 embeddedInWorkspace />');
    expect(alertsPage).toContain('embeddedInWorkspace = false');
    expect(alertsPage).toContain('Alerts review');
    expect(alertsPage).toContain("embeddedInWorkspace ? 'px-0 py-0' : 'px-4 py-6 md:px-6'");
    expect(alertsPage).toContain('{!embeddedInWorkspace && <ComplianceDisclaimer compact />}');
    expect(alertsPage).toContain('icon="ALR"');
    expect(alertsPage).not.toContain('icon="🔔"');
  });

  it('keeps specialist tools in research wording instead of recommendation wording', () => {
    const cryptoPage = read('app/tools/crypto/page.tsx');
    const cryptoMorningCard = read('components/CryptoMorningDecisionCard.tsx');
    const marketMoversPage = read('app/tools/market-movers/page.tsx');
    const optionsTerminalView = read('components/options-terminal/OptionsTerminalView.tsx');
    const suggestedStructures = read('components/options-terminal/SuggestedPlaysCard.tsx');
    const contractInspector = read('components/options-terminal/ContractInspectorPanel.tsx');
    const equityExplorerPage = read('app/tools/equity-explorer/page.tsx');
    const cryptoExplorerPage = read('app/tools/crypto-explorer/page.tsx');
    const commoditiesPage = read('app/tools/commodities/page.tsx');
    const regimeBanner = read('components/RegimeBanner.tsx');
    const liquiditySweepPage = read('app/tools/liquidity-sweep/page.tsx');
    const closeCalendar = read('components/time/CloseCalendar.tsx');
    const researchCaseModal = read('components/scanner/ResearchCaseModal.tsx');
    const correlationConfluenceCard = read('components/CorrelationConfluenceCard.tsx');
    const volatilityEnginePage = read('src/features/volatilityEngine/VolatilityEnginePage.tsx');
    const veProjectionCard = read('src/features/volatilityEngine/components/VEProjectionCard.tsx');
    const veSignalCard = read('src/features/volatilityEngine/components/VESignalCard.tsx');
    const veHeatmapGauge = read('src/features/volatilityEngine/components/VEHeatmapGauge.tsx');
    const vePhasePanel = read('src/features/volatilityEngine/components/VEPhasePanel.tsx');
    const scalperPage = read('app/tools/scalper/page.tsx');
    const intradayChartsPage = read('app/tools/intraday-charts/page.tsx');
    const signalAccuracyPage = read('app/tools/signal-accuracy/page.tsx');
    const goldenEggSignalHero = read('src/features/goldenEgg/components/GESignalHero.tsx');
    const timeScannerPageV2 = read('components/time/TimeScannerPage.tsx');
    const timeExecutionLayer = read('components/time/ExecutionLayer.tsx');
    const timeExecutionChecklist = read('components/time/ExecutionChecklist.tsx');
    const commandCenterStateBar = read('components/CommandCenterStateBar.tsx');
    const stateMachineCard = read('components/StateMachineTraderEyeCard.tsx');
    const capitalFlowCard = read('components/CapitalFlowCard.tsx');
    const derivativesWidget = read('components/DerivativesWidget.tsx');
    const mspOptionsHeader = read('components/msp/options/OptionsHeaderBar.tsx');
    const mspOptionsTimingLayer = read('components/msp/options/ExecutionLayer.tsx');
    const mspOptionsDecisionBar = read('components/msp/options/DecisionBar.tsx');
    const mspOptionsTimeWindow = read('components/msp/options/blocks/TimeWindowCard.tsx');
    const optionsExecutionPlanCard = read('components/options/layer2/ExecutionPlanCard.tsx');

    expect(cryptoPage).toContain('type ReviewVerdict');
    expect(cryptoPage).toContain('Risk Context: {morningDecision.riskContext}');
    expect(cryptoPage).toContain("Long Evidence: {morningDecision.longsAllowed ? 'Clear' : 'Limited'}");
    expect(cryptoPage).toContain('Review: {morningDecision.riskContext}');
    expect(cryptoPage).not.toContain('Capital Mode: {morningDecision.capitalMode}');
    expect(cryptoPage).not.toContain("Longs: {morningDecision.longsAllowed ? 'Allowed' : 'Restricted'}");
    expect(cryptoMorningCard).toContain('Crypto Review Gate');
    expect(cryptoMorningCard).toContain('Risk Context: {decision.riskContext}');
    expect(cryptoMorningCard).not.toContain('Crypto Condition Gate');
    expect(cryptoMorningCard).not.toContain('Sizing Context: {decision.capitalMode}');
    expect(marketMoversPage).toContain('Today&apos;s Movers Review Queue');
    expect(marketMoversPage).toContain('Risk Context: {environment.deploymentMode');
    expect(marketMoversPage).not.toContain('Today&apos;s Plays / Movers Queue');
    expect(marketMoversPage).not.toContain('Capital Mode: {environment.deploymentMode');
    expect(optionsTerminalView).toContain('Options scenario: ${label}');
    expect(optionsTerminalView).toContain('Save Scenario');
    expect(optionsTerminalView).toContain('These are educational frameworks only');
    expect(optionsTerminalView).toContain('{chain.error}');
    expect(optionsTerminalView).toContain('setWatchlistMsg(e.message)');
    expect(optionsTerminalView).not.toContain('Options play: ${label}');
    expect(optionsTerminalView).not.toContain('Save Play');
    expect(optionsTerminalView).not.toContain('⚠️ {chain.error}');
    expect(optionsTerminalView).not.toContain('setWatchlistMsg(`⚠ ${e.message}`)');
    expect(suggestedStructures).toContain('interface StructureExample');
    expect(suggestedStructures).toContain('context: string;');
    expect(suggestedStructures).toContain('code: string;');
    expect(suggestedStructures).toContain("code: 'BP'");
    expect(suggestedStructures).toContain('{p.code}');
    expect(suggestedStructures).not.toContain('interface Play');
    expect(suggestedStructures).not.toContain("icon: '🐂'");
    expect(suggestedStructures).not.toContain('{p.icon}');
    expect(contractInspector).toContain('Save Scenario');
    expect(contractInspector).not.toContain('Save Play');
    expect(equityExplorerPage).toContain('Risk Context: <span className="font-semibold text-slate-100">');
    expect(equityExplorerPage).toContain("icon: 'UP'");
    expect(equityExplorerPage).toContain("icon: 'DN'");
    expect(equityExplorerPage).toContain("icon: 'MID'");
    expect(equityExplorerPage).toContain("icon: 'STR'");
    expect(equityExplorerPage).toContain("icon: 'WK'");
    expect(equityExplorerPage).toContain("icon: 'HI'");
    expect(equityExplorerPage).toContain("icon: 'LO'");
    expect(equityExplorerPage).toContain("icon: 'NORM'");
    expect(equityExplorerPage).toContain("{refreshing ? 'Loading' : 'Refresh'}");
    expect(equityExplorerPage).toContain('<strong>ERROR</strong> {error}');
    expect(equityExplorerPage).not.toContain('Capital Mode: <span className="font-semibold text-slate-100">');
    expect(equityExplorerPage).not.toContain("icon: '📈'");
    expect(equityExplorerPage).not.toContain("icon: '📉'");
    expect(equityExplorerPage).not.toContain("icon: '➖'");
    expect(equityExplorerPage).not.toContain("icon: '🔥'");
    expect(equityExplorerPage).not.toContain("icon: '❄️'");
    expect(equityExplorerPage).not.toContain("icon: '⚖️'");
    expect(equityExplorerPage).not.toContain("icon: '⚡'");
    expect(equityExplorerPage).not.toContain("icon: '🛡️'");
    expect(equityExplorerPage).not.toContain("{refreshing ? '⏳' : '🔄'}");
    expect(equityExplorerPage).not.toContain('❌ {error}');
    expect(cryptoPage).toContain("icon: 'OVR'");
    expect(cryptoPage).toContain("icon: 'SRC'");
    expect(cryptoPage).toContain("icon: 'MAP'");
    expect(cryptoPage).toContain("icon: 'TRD'");
    expect(cryptoPage).toContain("icon: 'MOV'");
    expect(cryptoPage).toContain("icon: 'SEC'");
    expect(cryptoPage).toContain("icon: 'DFI'");
    expect(cryptoPage).toContain("icon: 'DEX'");
    expect(cryptoPage).toContain("icon: 'NEW'");
    expect(cryptoPage).toContain("icon: 'LST'");
    expect(cryptoPage).toContain('<span><strong>WARN</strong> {fetchError}</span>');
    expect(cryptoPage).toContain('>Close</button>');
    expect(cryptoPage).toContain('aria-label="Crypto Command Center command header"');
    expect(cryptoPage).toContain('Crypto command');
    expect(cryptoPage).toContain('Crypto Command Center.');
    expect(cryptoPage).toContain('Open Crypto Derivatives');
    expect(cryptoPage).toContain('Open Macro Lens');
    expect(cryptoPage).toContain('grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-5');
    expect(cryptoPage).toContain('Also in Markets');
    expect(cryptoPage).not.toContain("icon: '📊'");
    expect(cryptoPage).not.toContain("icon: '🔍'");
    expect(cryptoPage).not.toContain("icon: '🗺️'");
    expect(cryptoPage).not.toContain("icon: '🔥'");
    expect(cryptoPage).not.toContain("icon: '📈'");
    expect(cryptoPage).not.toContain("icon: '🏷️'");
    expect(cryptoPage).not.toContain("icon: '🏦'");
    expect(cryptoPage).not.toContain("icon: '🔄'");
    expect(cryptoPage).not.toContain("icon: '🌱'");
    expect(cryptoPage).not.toContain("icon: '🆕'");
    expect(cryptoPage).not.toContain('⚠️ {fetchError}');
    expect(cryptoPage).not.toContain('>✕</button>');
    expect(cryptoExplorerPage).toContain('<strong>ERROR</strong> {error}');
    expect(cryptoExplorerPage).not.toContain('❌ {error}');
    expect(commoditiesPage).toContain('type ReviewState');
    expect(commoditiesPage).toContain('const reviewBadge');
    expect(commoditiesPage).toContain('REVIEW: {derivedState.reviewState');
    expect(commoditiesPage).toContain('Long Evidence');
    expect(commoditiesPage).toContain('Scenario Implications');
    expect(commoditiesPage).not.toContain('type PermissionState');
    expect(commoditiesPage).not.toContain('const permissionBadge');
    expect(commoditiesPage).not.toContain("{derivedState.longsAllowed ? 'Allowed' : 'Restricted'}");
    expect(commoditiesPage).not.toContain('Trading Implications');
    expect(regimeBanner).toContain('const reviewColors');
    expect(regimeBanner).toContain('Review:');
    expect(regimeBanner).toContain('Risk Context:');
    expect(regimeBanner).toContain('Stale signals');
    expect(regimeBanner).not.toContain('permissionColors');
    expect(regimeBanner).not.toContain('Sizing:');
    expect(regimeBanner).not.toContain('⚠ Stale signals');
    expect(liquiditySweepPage).toContain('function observationBadge');
    expect(liquiditySweepPage).toContain('NO OBSERVATION');
    expect(liquiditySweepPage).toContain('Observations (Sweep + Near Level)');
    expect(liquiditySweepPage).toContain("{t === 'equity' ? 'Equity' : 'Crypto'}");
    expect(liquiditySweepPage).toContain("{loading ? 'Scanning...' : 'Scan for Sweeps'}");
    expect(liquiditySweepPage).toContain('Liquidity sweep detection is for educational purposes only.');
    expect(liquiditySweepPage).toContain("{r.direction === 'bullish' ? 'Bullish' : 'Bearish'} context");
    expect(liquiditySweepPage).not.toContain('function setupBadge');
    expect(liquiditySweepPage).not.toContain('NO SETUP');
    expect(liquiditySweepPage).not.toContain('🔍 Scan for Sweeps');
    expect(liquiditySweepPage).not.toContain('⚠️ Liquidity sweep');
    expect(liquiditySweepPage).not.toContain("{r.direction === 'bullish' ? '↑ LONG' : '↓ SHORT'} bias");
    expect(closeCalendar).toContain("'Close Calendar — Prior Day Closes'");
    expect(closeCalendar).toContain('Close Cluster Timeline');
    expect(closeCalendar).not.toContain('📋 Close Calendar');
    expect(closeCalendar).not.toContain('🔥 Close Cluster Timeline');
    expect(researchCaseModal).toContain('Research Case — {pick.symbol}');
    expect(researchCaseModal).toContain('Export CSV');
    expect(researchCaseModal).toContain('{invalidation}');
    expect(researchCaseModal).not.toContain('📋 Research Case');
    expect(researchCaseModal).not.toContain('📥 Export CSV');
    expect(researchCaseModal).not.toContain('⚠️ {invalidation}');
    expect(correlationConfluenceCard).toContain('Divergence');
    expect(correlationConfluenceCard).toContain("data.type === 'crypto' ? 'Crypto majors'");
    expect(correlationConfluenceCard).not.toContain('⚡ Divergence');
    expect(correlationConfluenceCard).not.toContain('🔗 Crypto majors');
    expect(volatilityEnginePage).toContain('function SectionTitle({ code, title }');
    expect(volatilityEnginePage).toContain('<SectionTitle code="VOL" title="Layer 1 — Volatility State" />');
    expect(volatilityEnginePage).toContain('<SectionTitle code="SIG" title="Layer 4 — Signal &amp; Invalidation" />');
    expect(volatilityEnginePage).not.toContain('SectionTitle icon=');
    expect(volatilityEnginePage).not.toContain('<span className="text-xl">⚡</span>');
    expect(veProjectionCard).toContain('>PROJ</span>');
    expect(veProjectionCard).not.toContain('>📊</span>');
    expect(veSignalCard).toContain('function stateCode');
    expect(veSignalCard).toContain("case 'fired': return 'LIVE';");
    expect(veSignalCard).toContain('>SIG</span>');
    expect(veSignalCard).not.toContain('function stateIcon');
    expect(veSignalCard).not.toContain("return '🟢'");
    expect(veHeatmapGauge).toContain('>VOL</span>');
    expect(veHeatmapGauge).toContain("vol.extremeAlert === 'low' ? 'Extreme Low' : 'Extreme High'");
    expect(veHeatmapGauge).not.toContain('🌡️');
    expect(veHeatmapGauge).not.toContain('🔥 Extreme High');
    expect(vePhasePanel).toContain('>PH</span>');
    expect(vePhasePanel).not.toContain('⏱️');
    expect(scalperPage).toContain("function directionLabel(direction: ScalpResult['direction'])");
    expect(scalperPage).toContain('<th className="text-left py-2 px-2">Context</th>');
    expect(scalperPage).toContain('{directionLabel(r.direction)} context');
    expect(scalperPage).not.toContain('<th className="text-left py-2 px-2">Direction</th>');
    expect(scalperPage).not.toContain("{r.direction === 'long' ? '▲ LONG' : r.direction === 'short' ? '▼ SHORT' : '— NEUTRAL'}");
    expect(intradayChartsPage).toContain("const reviewState: 'Clear' | 'Caution' | 'Blocked'");
    expect(intradayChartsPage).toContain('Indicator Review');
    expect(intradayChartsPage).toContain('{scenarioNote}');
    expect(intradayChartsPage).toContain('short-timeframe scenario review');
    expect(intradayChartsPage).not.toContain('const permissionState');
    expect(intradayChartsPage).not.toContain('const permissionReason');
    expect(intradayChartsPage).not.toContain('const playbook');
    expect(intradayChartsPage).not.toContain('day-trade setups');
    expect(signalAccuracyPage).toContain('<th className="text-left px-4 py-2">Context</th>');
    expect(signalAccuracyPage).toContain("{s.direction === 'bullish' ? 'Bullish' : s.direction === 'bearish' ? 'Bearish' : 'Neutral'}");
    expect(signalAccuracyPage).toContain('OK &ge;{t.correct_threshold}%');
    expect(signalAccuracyPage).toContain('NO &le;{t.wrong_threshold}%');
    expect(signalAccuracyPage).not.toContain('<th className="text-left px-4 py-2">Direction</th>');
    expect(signalAccuracyPage).not.toContain('✓ &ge;{t.correct_threshold}%');
    expect(signalAccuracyPage).not.toContain('✗ &le;{t.wrong_threshold}%');
    expect(goldenEggSignalHero).toContain('STRONG EVIDENCE');
    expect(goldenEggSignalHero).toContain('INSUFFICIENT EVIDENCE');
    expect(goldenEggSignalHero).toContain("{ label: 'Structure', value: setupLabel(setupType), color: 'text-sky-400' }");
    expect(goldenEggSignalHero).not.toContain('NO SETUP');
    expect(goldenEggSignalHero).not.toContain("{ label: 'Setup', value: setupLabel(setupType), color: 'text-sky-400' }");
    expect(timeScannerPageV2).toContain('function TimingField');
    expect(timeScannerPageV2).toContain("{ label: 'Close Evidence', score: out.executionScore }");
    expect(timeScannerPageV2).toContain('CONFLUENCE ENGINE + TIMING');
    expect(timeScannerPageV2).not.toContain('function ExecutionField');
    expect(timeScannerPageV2).not.toContain('CONFLUENCE ENGINE + EXECUTION');
    expect(timeExecutionLayer).toContain('function TimingSummary');
    expect(timeExecutionLayer).toContain('<MiniScore label="Timing" value={out.executionScore} />');
    expect(timeExecutionLayer).not.toContain('function ExecutionSummary');
    expect(timeExecutionLayer).not.toContain('<MiniScore label="Exec" value={out.executionScore} />');
    expect(timeExecutionChecklist).toContain('Close Evidence');
    expect(timeExecutionChecklist).not.toContain('Close Confirmation');
    expect(commandCenterStateBar).toContain('function stageLabel(mode: OperatorFlowMode)');
    expect(commandCenterStateBar).toContain("if (mode === 'EXECUTE') return 'Timing Review';");
    expect(commandCenterStateBar).toContain('{stageLabel(mode)}');
    expect(stateMachineCard).toContain('Scenario State');
    expect(stateMachineCard).toContain('READY TO REVIEW');
    expect(stateMachineCard).toContain('<strong>REVIEW:</strong>');
    expect(stateMachineCard).not.toContain('Trader Eye State');
    expect(stateMachineCard).not.toContain('<strong>CONDITION:</strong>');
    expect(capitalFlowCard).toContain('REVIEW CLEAR');
    expect(capitalFlowCard).toContain('REVIEW BLOCKED');
    expect(capitalFlowCard).toContain('Exposure Context:');
    expect(capitalFlowCard).toContain('Context Formula:');
    expect(capitalFlowCard).not.toContain('CONDITIONS MET');
    expect(capitalFlowCard).not.toContain('Size Formula:');
    expect(derivativesWidget).toContain('function getPositioningInsight');
    expect(derivativesWidget).toContain("return { code: 'RISK'");
    expect(derivativesWidget).toContain('Research context:');
    expect(derivativesWidget).toContain('getSentimentCode');
    expect(derivativesWidget).toContain('>DER</span>');
    expect(derivativesWidget).not.toContain('icon: string;');
    expect(derivativesWidget).not.toContain("return '🟢'");
    expect(derivativesWidget).not.toContain('💡 <strong');
    expect(mspOptionsHeader).toContain('Context → Setup → Timing → Review');
    expect(mspOptionsHeader).not.toContain('Context → Setup → Execution → Decision');
    expect(mspOptionsTimingLayer).toContain('subtitle="Is the timing evidence clean?"');
    expect(mspOptionsTimingLayer).not.toContain('Can we enter efficiently?');
    expect(mspOptionsDecisionBar).toContain('setup evidence stronger than timing evidence');
    expect(mspOptionsDecisionBar).toContain('Review State:');
    expect(mspOptionsDecisionBar).toContain('Context/Setup/Timing:');
    expect(mspOptionsDecisionBar).toContain('View Framework');
    expect(mspOptionsDecisionBar).not.toContain('setup strong but execution weaker');
    expect(mspOptionsDecisionBar).not.toContain('Context/Setup/Execution:');
    expect(mspOptionsDecisionBar).not.toContain('View Strategy');
    expect(mspOptionsTimeWindow).toContain('label="Timing State"');
    expect(mspOptionsTimeWindow).not.toContain('label="Permission"');
    expect(optionsExecutionPlanCard).toContain('Exposure Context:');
    expect(optionsExecutionPlanCard).not.toContain('Capital Exposure:');
  });

  it('keeps Time Scanner compact when embedded in Terminal', () => {
    const timeScannerPage = read('app/tools/time-scanner/page.tsx');

    expect(timeScannerPage).toContain('embeddedInTerminal = false');
    expect(timeScannerPage).toContain("propSymbol?.trim().toUpperCase()");
    expect(timeScannerPage).toContain('Time Scanner');
    expect(timeScannerPage).toContain('What is Time Gravity Map?');
    expect(timeScannerPage).toContain('Status Indicators');
    expect(timeScannerPage).toContain('>DEBT</span>');
    expect(timeScannerPage).not.toContain('⏰ Time Scanner');
    expect(timeScannerPage).not.toContain('🎯 What is Time Gravity Map?');
    expect(timeScannerPage).not.toContain('🔴</span>');
    expect(timeScannerPage).toContain('!embeddedInTerminal && <div className="text-center mb-8">');
    expect(timeScannerPage).toContain("embeddedInTerminal ? 'px-0 py-0' : 'container mx-auto px-4 py-8'");
    expect(timeScannerPage).toContain('!embeddedInTerminal && <div className="max-w-7xl mx-auto mt-12 grid grid-cols-1 lg:grid-cols-3 gap-6">');
  });

  it('treats Scanner as Ranked, Pro, and Analysis views', () => {
    const scannerPage = read('app/tools/scanner/page.tsx');

    expect(scannerPage).toContain("type ScannerStage = ScannerMode | 'analysis'");
    expect(scannerPage).toContain('function ScannerFlowRail');
    expect(scannerPage).toContain('Workflow step 1 · Market research queue');
    expect(scannerPage).toContain('Find the highest-evidence research queue.');
    expect(scannerPage).toContain('Ranked auto-triages the market. Pro lets you configure conditions. Analysis sends one symbol into Golden Egg.');
    expect(scannerPage).toContain('<ComplianceDisclaimer compact />');
    expect(scannerPage).toContain('grid grid-cols-3 gap-2');
    expect(scannerPage).not.toContain('flex gap-1 overflow-x-auto');
    expect(scannerPage).not.toContain('h-full min-w-[9rem] rounded-md border px-3 py-1.5');
    expect(scannerPage).not.toContain('<SectionHeader title="Scanner"');
    expect(scannerPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(scannerPage).toContain("{ id: 'ranked', label: 'Ranked'");
    expect(scannerPage).toContain("{ id: 'pro', label: 'Pro'");
    expect(scannerPage).toContain("{ id: 'analysis', label: 'Analysis'");
    expect(scannerPage).toContain("const activeScannerStage: ScannerStage = selectedSymbol ? 'analysis' : mode");
    expect(scannerPage).toContain('onSelectAnalysis');
    expect(scannerPage).toContain('const canOpenAnalysis = Boolean(selectedSymbol)');
    expect(scannerPage).toContain('const openScannerAnalysis = useCallback(() => {');
    expect(scannerPage).toContain('if (firstResult) handleV2RowClick(firstResult);');
    expect(scannerPage).toContain('if (firstResult) handleProRowClick(firstResult);');
    expect(scannerPage).toContain('Analysis view');
    expect(scannerPage).toContain('function RankedMobileCards');
    expect(scannerPage).toContain('<RankedMobileCards rows={filtered} activeRegime={currentRegime} onRowClick={handleV2RowClick} />');
    expect(scannerPage).toContain('Why This Rank / Review');
    expect(scannerPage).toContain('Aligned Scenarios');
    expect(scannerPage).toContain('<SortHeader k="direction" label="Bias"');
    expect(scannerPage).toContain('<SortHeader k="confidence" label="Alignment"');
    expect(scannerPage).toContain('Review scenario for ${r.symbol}');
    expect(scannerPage).not.toContain("label=\"Direction\"");
    expect(scannerPage).not.toContain("label=\"Conf\"");
    expect(scannerPage).not.toContain('Ready Setups');
    expect(scannerPage).toContain('function ProScannerCards');
    expect(scannerPage).toContain("proBulkViewMode === 'cards'");
    expect(scannerPage).toContain("returnLabel={mode === 'ranked' ? 'Back to Ranked' : 'Back to Pro Scanner'}");
  });

  it('keeps Backtest page-local chrome free of emoji-era badges', () => {
    const backtestPage = read('app/tools/backtest/page.tsx');
    const scannerBacktestPage = read('app/tools/scanner/backtest/page.tsx');
    const settingsPage = read('app/tools/settings/page.tsx');

    expect(backtestPage).toContain('icon="BT"');
    expect(backtestPage).toContain('>CTX</span>');
    expect(backtestPage).toContain('>CFG</span>');
    expect(backtestPage).toContain('Scan Best Timeframe');
    expect(backtestPage).toContain('Use Best Pair & Rerun');
    expect(backtestPage).toContain('Strategy Verdict: {verdict.label}');
    expect(backtestPage).toContain('Positive Expectancy');
    expect(backtestPage).toContain('Marginal Edge');
    expect(backtestPage).toContain('Negative Expectancy');
    expect(backtestPage).not.toContain('icon="🧪"');
    expect(backtestPage).not.toContain('>🔬</span>');
    expect(backtestPage).not.toContain('🔎 Scan Best Timeframe');
    expect(backtestPage).not.toContain('⚡ Use Best & Rerun');
    expect(backtestPage).not.toContain('🌐 Scan Universe');
    expect(backtestPage).not.toContain('🏛️ Scan Top 10 Stocks');
    expect(backtestPage).not.toContain('🪙 Scan Crypto (BTC)');
    expect(backtestPage).not.toContain('🧭 Use Best Pair & Rerun');
    expect(backtestPage).not.toContain('✅ Positive Expectancy');
    expect(backtestPage).not.toContain('⚠️ Marginal Edge');
    expect(backtestPage).not.toContain('❌ Negative Expectancy');
    expect(backtestPage).not.toContain('⚠️ <strong>Important:</strong>');
    expect(scannerBacktestPage).toContain('BULL ≥ {minScore}');
    expect(scannerBacktestPage).toContain('BEAR ≤ {bearThresh}');
    expect(scannerBacktestPage).toContain('Alert Me on Scenario Conditions');
    expect(scannerBacktestPage).not.toContain('🟢 Long');
    expect(scannerBacktestPage).not.toContain('🔴 Short');
    expect(scannerBacktestPage).not.toContain('🔔 Alert Me');
    expect(settingsPage).toContain('icon="SET"');
    expect(settingsPage).toContain('Cooldown Active');
    expect(settingsPage).toContain('Daily R Budget Halved');
    expect(settingsPage).not.toContain('icon="⚙️"');
    expect(settingsPage).not.toContain('⏳ Disable Cooldown Active');
    expect(settingsPage).not.toContain('⚠️ Daily R Budget Halved');
  });

  it('keeps market context routes on compact tool chrome', () => {
    const marketMoversPage = read('app/tools/market-movers/page.tsx');
    const newsPage = read('app/tools/news/page.tsx');
    const commoditiesPage = read('app/tools/commodities/page.tsx');
    const referralsPage = read('app/tools/referrals/page.tsx');
    const gainersLosersPage = read('app/tools/gainers-losers/page.tsx');

    expect(marketMoversPage).toContain('icon="MM"');
    expect(marketMoversPage).toContain('<ComplianceDisclaimer compact />');
    expect(marketMoversPage).toContain("mover.asset_class === 'equity' ? 'EQ Equity' : 'CR Crypto'");
    expect(marketMoversPage).toContain('No aligned movers: environment conditions are not suitable for momentum analysis.');
    expect(marketMoversPage).not.toContain('icon="📈"');
    expect(marketMoversPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(marketMoversPage).not.toContain('⚠ No Aligned Movers');
    expect(newsPage).toContain('icon="NI"');
    expect(newsPage).toContain('!embeddedInResearch && <ComplianceDisclaimer compact />');
    expect(newsPage).toContain("label: 'TOP 10'");
    expect(newsPage).toContain('News & Sentiment');
    expect(newsPage).toContain('Earnings Calendar');
    expect(newsPage).toContain('EARNINGS</div>');
    expect(newsPage).not.toContain('icon="📰"');
    expect(newsPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(newsPage).not.toContain('📅 Earnings Calendar');
    expect(commoditiesPage).toContain('icon="CMD"');
    expect(commoditiesPage).toContain('<ComplianceDisclaimer compact />');
    expect(commoditiesPage).toContain("Energy: { icon: 'EN'");
    expect(commoditiesPage).toContain("WTI: 'WTI'");
    expect(commoditiesPage).toContain('EN · MT · AG');
    expect(commoditiesPage).not.toContain('icon="🛢️"');
    expect(commoditiesPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(referralsPage).toContain('icon="REF"');
    expect(referralsPage).toContain('<ComplianceDisclaimer compact />');
    expect(referralsPage).toContain('Monthly $500 Draw');
    expect(referralsPage).toContain('This Month&apos;s Top Referrers');
    expect(referralsPage).not.toContain('icon="🎁"');
    expect(referralsPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(referralsPage).not.toContain('🏆 Monthly $500 Draw');
    expect(referralsPage).not.toContain('🏅 This Month&apos;s Top Referrers');
    expect(gainersLosersPage).toContain('icon="MOV"');
    expect(gainersLosersPage).toContain('<ComplianceDisclaimer compact />');
    expect(gainersLosersPage).toContain('Market data: {marketDate}');
    expect(gainersLosersPage).toContain('Fetched: {lastUpdated.toLocaleTimeString()}');
    expect(gainersLosersPage).toContain('Top Gainers</button>');
    expect(gainersLosersPage).toContain('Top Losers</button>');
    expect(gainersLosersPage).toContain('Most Active</button>');
    expect(gainersLosersPage).toContain('No Aligned Movers — environment conditions are not suitable for momentum analysis.');
    expect(gainersLosersPage).not.toContain('icon="📊"');
    expect(gainersLosersPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(gainersLosersPage).not.toContain('📅 Market data');
    expect(gainersLosersPage).not.toContain('🔄 Fetched');
    expect(gainersLosersPage).not.toContain('🚀 Top Gainers');
    expect(gainersLosersPage).not.toContain('📉 Top Losers');
    expect(gainersLosersPage).not.toContain('🔥 Most Active');
  });

  it('keeps secondary market routes on text-code visual identity', () => {
    const companyOverviewPage = read('app/tools/company-overview/page.tsx');
    const heatmapPage = read('app/tools/heatmap/page.tsx');
    const economicCalendarPage = read('app/tools/economic-calendar/page.tsx');
    const macroPage = read('app/tools/macro/page.tsx');

    expect(companyOverviewPage).toContain('icon="CO"');
    expect(companyOverviewPage).toContain('icon: "UP"');
    expect(companyOverviewPage).toContain('icon: "DN"');
    expect(companyOverviewPage).toContain('icon: "MID"');
    expect(companyOverviewPage).toContain('AI Decision Lens');
    expect(companyOverviewPage).toContain('Research disclaimer:');
    expect(companyOverviewPage).not.toContain('icon="🏢"');
    expect(companyOverviewPage).not.toContain('📈');
    expect(companyOverviewPage).not.toContain('📉');
    expect(companyOverviewPage).not.toContain('⚠️ Disclaimer');
    expect(heatmapPage).toContain('icon="HM"');
    expect(heatmapPage).toContain('>READ</span> How to Read');
    expect(heatmapPage).toContain('>TIP</span> Pro Tips');
    expect(heatmapPage).toContain('>ETF</span> Sector ETFs');
    expect(heatmapPage).not.toContain('icon="📊"');
    expect(heatmapPage).not.toContain('🎯');
    expect(economicCalendarPage).toContain('icon="EC"');
    expect(economicCalendarPage).toContain("employment: 'JOBS'");
    expect(economicCalendarPage).toContain("central_bank: 'CB'");
    expect(economicCalendarPage).not.toContain('icon="📅"');
    expect(economicCalendarPage).not.toContain("inflation: '📈'");
    expect(macroPage).toContain('icon="MAC"');
    expect(macroPage).toContain('<span className="font-bold text-red-200">WARN</span> {error}');
    expect(macroPage).toContain("correlationRegime.components?.goldSafeHaven ? 'Active' : 'Inactive'");
    expect(macroPage).not.toContain('icon="🏛️"');
    expect(macroPage).not.toContain('⚠️ {error}');
    expect(macroPage).not.toContain("'⚠️ Active'");
  });

  it('treats Golden Egg as a focused validation workbench with Liquidity Sweep separated', () => {
    const goldenEggPage = read('app/tools/golden-egg/page.tsx');
    const goldenEggLayout = read('app/tools/golden-egg/layout.tsx');
    const workflows = read('lib/toolWorkflows.ts');

    expect(goldenEggPage).toContain("const GE_TABS = ['Verdict', 'Chart', 'Deep Analysis', 'Fundamentals'] as const");
    expect(goldenEggPage).toContain('function GoldenEggTabRail');
    expect(goldenEggPage).toContain('function GoldenEggSubviewFrame');
    expect(goldenEggPage).toContain('Golden Egg subview');
    expect(goldenEggPage).toContain('const GOLDEN_EGG_WORKFLOW_CHECKS = [');
    expect(goldenEggPage).toContain('function FlagshipMetric');
    expect(goldenEggPage).toContain('min-h-[3.05rem] rounded-md border border-white/10');
    expect(goldenEggPage).toContain('Golden Egg validation workbench');
    expect(goldenEggPage).toContain('Validate one symbol before testing history.');
    expect(goldenEggPage).toContain('Regime, data trust, volatility, flow, timing, and invalidation are compressed into one research packet.');
    expect(goldenEggPage).toContain('Verdict first');
    expect(goldenEggPage).toContain('Data trust');
    expect(goldenEggPage).toContain('Reference level');
    expect(goldenEggPage).toContain('Next useful check:');
    expect(goldenEggPage).toContain('Choose a symbol to build the verdict packet.');
    expect(goldenEggPage).toContain('<ComplianceDisclaimer compact />');
    expect(goldenEggPage).toContain('Verdict Packet');
    expect(goldenEggPage).toContain('Validation workbench');
    expect(goldenEggPage).toContain('Open Liquidity Sweep');
    expect(goldenEggPage).toContain('Verdict first, then inspect chart, evidence detail, and business context.');
    expect(goldenEggPage).toContain('flex gap-1 overflow-x-auto');
    expect(goldenEggPage).toContain('min-w-[9rem] shrink-0 rounded-md border px-3 py-1.5');
    expect(goldenEggPage).toContain('Answer first: alignment, data trust, reference, invalidation, and next check.');
    expect(goldenEggPage).toContain('<GoldenEggTabRail activeTab={activeTab} onSelectTab={setActiveTab} />');
    expect(goldenEggPage).not.toContain('<SectionHeader title="Golden Egg"');
    expect(goldenEggPage).not.toContain('<ComplianceDisclaimer collapsible />');
    expect(goldenEggPage).not.toContain('decision packet is sample data');
    expect(goldenEggPage).not.toContain("activeTab === 'Liquidity'");
    expect(goldenEggPage).not.toContain('Loading Liquidity Sweep');
    expect(goldenEggPage).not.toContain('rounded-t-md whitespace-nowrap transition-colors');
    expect(goldenEggLayout).not.toContain('liquidity');
    expect(workflows).toContain("{ href: '/tools/liquidity-sweep', label: 'Liquidity Sweep', description: 'Broad sweep/reclaim scanner for liquidity-zone research.', tier: 'pro_trader', role: 'specialist' }");
  });

  it('keeps shared tool headers aligned with the compact command treatment', () => {
    const toolsPageHeader = read('components/ToolsPageHeader.tsx');
    const terminalPageHeader = read('components/terminal/TerminalPageHeader.tsx');

    expect(terminalPageHeader).toContain('function headerCode');
    expect(terminalPageHeader).toContain('style={{ padding: 12, borderRadius: 8');
    expect(terminalPageHeader).toContain('linear-gradient(135deg, rgba(15,23,42,0.98), rgba(8,13,24,0.98))');
    expect(terminalPageHeader).toContain('h-8 w-8');
    expect(terminalPageHeader).toContain('text-[1.08rem] font-black tracking-normal');
    expect(terminalPageHeader).toContain('max-w-3xl text-xs leading-5');
    expect(terminalPageHeader).not.toContain('text-[20px] leading-none');
    expect(toolsPageHeader).toContain('msp-container py-3');
    expect(toolsPageHeader).toContain('rounded-md border border-msp-border bg-msp-panel px-3 py-1.5');
    expect(toolsPageHeader).toContain('Educational Only • Not Financial Advice');
    expect(toolsPageHeader).toContain('rounded-md border border-msp-warn/30');
  });

  it('keeps Golden Egg nested pages in embedded validation mode', () => {
    const goldenEggPage = read('app/tools/golden-egg/page.tsx');
    const chartPage = read('app/tools/intraday-charts/page.tsx');
    const fundamentalsPage = read('app/tools/company-overview/page.tsx');

    expect(goldenEggPage).toContain('<GoldenEggSubviewFrame tab="Chart" symbol={sym}>');
    expect(goldenEggPage).toContain('<GoldenEggSubviewFrame tab="Deep Analysis" symbol={sym}>');
    expect(goldenEggPage).toContain('<GoldenEggSubviewFrame tab="Fundamentals" symbol={sym}>');
    expect(chartPage).toContain('{!embeddedInGoldenEgg && <div className="flex items-center justify-between gap-4 rounded-lg border border-slate-700 bg-slate-900 p-2">');
    expect(chartPage).toContain('Educational caution: elevated session risk; review only until conditions improve.');
    expect(chartPage).toContain('<div className="text-xs text-slate-400 uppercase tracking-wide">Intraday Console</div>');
    expect(fundamentalsPage).toContain('const embeddedInGoldenEgg = Boolean(propSymbol);');
    expect(fundamentalsPage).toContain('{!embeddedInGoldenEgg && (');
    expect(fundamentalsPage).toContain('padding: embeddedInGoldenEgg ? "8px 0 0" : "24px 16px"');
  });
});