[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.49.1",
    "yfinance>=0.2.66",
    "pandas>=2.3.2",
    "numpy>=2.3.3",
    "plotly>=6.3.0",
    "requests>=2.32.5",
]
