# wrangler.toml
name = "marketscannerpros"
pages_build_output_dir = "dist"
compatibility_date = "2025-09-22"


# If your static site is built into "dist"
pages_build_output_dir = "dist"

# (optional) if you'll add KV later:
# [[kv_namespaces]]
# binding = "SCANNER_KV"
# id = "xxxxxxxxxxxxxxxxxxxx"
