'use client';
import { useEffect,useState } from 'react';
type Holding={id:string;symbol:string;side:string;quantity:number|null;entry:number|null;mark:number|null;stop:number|null;target:number|null;exposure:number|null;unrealizedPnl:number|null;savedAt:string};
type Holdings={positions:Holding[];count:number;exposure:number|null;unrealizedPnl:number|null;limitations:string[]};
const fmt=(n:number|null)=>n==null?'Unavailable':n.toLocaleString(undefined,{maximumFractionDigits:4});
export default function SavedHoldings(){
 const [data,setData]=useState<Holdings|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/admin/portfolio-lab/holdings',{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j;}).then(setData).catch(e=>{if(!controller.signal.aborted){setError(e.message);setData(null);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[revision]);
 return <section className="space-y-5 p-6 text-slate-100"><h1 className="text-2xl font-bold">Saved Portfolio Holdings</h1><p>Read-only holdings from your workspace portfolio. Values use saved prices; they are not broker-verified or live marks.</p><button disabled={loading} onClick={()=>setRevision(v=>v+1)} className="rounded bg-emerald-800 px-4 py-2">{loading?'Loading…':'Refresh saved holdings'}</button>{error&&<p role="alert">{error}</p>}{data&&!loading&&<><p>{data.count} open positions · Saved exposure: {fmt(data.exposure)} USD · Unrealised P&amp;L: {fmt(data.unrealizedPnl)} USD</p>{data.count===0?<p>No saved holdings in this authenticated workspace. ARCA paper positions are shown separately.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Symbol','Side','Quantity','Entry','Saved mark','Stop','Target','Exposure USD','P&L USD','Record saved'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.positions.map(p=><tr key={p.id} className="border-t border-slate-700"><td className="p-2">{p.symbol}</td><td>{p.side}</td>{[p.quantity,p.entry,p.mark,p.stop,p.target,p.exposure,p.unrealizedPnl].map((n,i)=><td className="p-2" key={i}>{fmt(n)}</td>)}<td>{p.savedAt?new Date(p.savedAt).toLocaleString():'Unknown'}</td></tr>)}</tbody></table></div>}{data.limitations.map(s=><p className="text-sm text-slate-400" key={s}>{s}</p>)}</>}</section>;
}
