import Link from 'next/link';
import type {PublicM2Summary} from '@/lib/research/publicM2Summary';
import styles from './EconomicResearch.module.css';
const finite=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n);
const money=(n:number)=>finite(n)?`$${(n/1e12).toFixed(2)}T`:'Not available';
const pct=(n:number|null)=>finite(n)?`${n>0?'+':''}${n.toFixed(2)}%`:'Not available';
export default function M2Research({data,loading,error,retry}:{data:PublicM2Summary|null;loading:boolean;error:boolean;retry:()=>void}){
 const blocs=[...(data?.blocs??[])].sort((a,b)=>a.name.localeCompare(b.name));
 const largest=Math.max(1,...blocs.map(b=>finite(b.usdM2)?b.usdM2:0));
 return <article className={styles.page} data-economic-research="m2"><header className={styles.hero}><p className={styles.eyebrow}>Money supply in context</p><h1>Global M2 Intelligence</h1><p>Explore reported money supply across economic blocs, with the coverage and currency basis in view.</p><Link href="/tools/macro">Return to Macro Outlook</Link></header>
 {loading?<p role="status">Loading Global M2 observations…</p>:error?<div className={styles.panel} role="status"><h2>Global M2 unavailable</h2><p>The response could not be loaded.</p><button onClick={retry}>Try again</button></div>:!data?.enabled?<div className={styles.panel} role="status"><h2>Observations not collected</h2><p>Global M2 observations are not collected in this environment. No total or trend is inferred.</p></div>:<>
 <div className={styles.metrics}><section><h2>Reported total · USD</h2><strong>{blocs.length?money(data.totalUsd):'Not available'}</strong><p>Total for the available blocs</p></section><section><h2>Bloc coverage</h2><strong>{data.validBlocCount} / {data.validBlocCount+data.missingBlocCount}</strong><p>Blocs returned / expected</p></section><section><h2>One-month change</h2><strong>{pct(data.oneMonthPct)}</strong><p>Reported aggregate change</p></section><section><h2>Year over year</h2><strong>{pct(data.yoyPct)}</strong><p>Reported aggregate change</p></section></div>
 <section className={styles.panel}><div className={styles.heading}><div><p className={styles.eyebrow}>Composition, not a forecast</p><h2>Money supply by bloc</h2></div><span>USD equivalent · alphabetical order</span></div><p className={styles.note}>Different observation months may be combined. USD conversion also reflects exchange rates; these bars do not show price forecasts or liquidity flowing into markets.</p>
 <div className={styles.blocs}>{blocs.map(b=><div key={b.id} className={styles.bloc}><div><h3>{b.name}</h3><span>{b.observationMonth || 'Month not supplied'} · {b.classification}</span></div><div className={styles.bar} aria-hidden="true">{finite(b.usdM2)&&b.usdM2>=0?<i style={{width:`${b.usdM2/largest*100}%`}}/>:null}</div><strong>{money(b.usdM2)}</strong><p>Source: {b.provider || 'Not supplied'} · {b.stale?'Older saved observation':`Retrieval status: ${b.health}`} · 1M {pct(b.r1)} · YoY {pct(b.r12)}</p></div>)}</div>{!blocs.length?<p>No bloc observations are available.</p>:null}</section>
 <section className={styles.explanation}><h2>Coverage is part of the reading.</h2><p>{data.missingBlocCount} blocs missing. Calculation status: {data.calculationStatus}. Parity status: {data.parityStatus}.</p><p>Weighted coverage of included blocs: {finite(data.estimatedWeightedCoveragePercent)?data.estimatedWeightedCoveragePercent.toFixed(1):'Not supplied'}%. The existing calculation requires {data.weightedCoverageThreshold}% for interpretation eligibility; it is currently {data.interpretationEligible?'eligible':'ineligible'}. This coverage requirement is not a measure of confidence.</p>{data.missing.map(m=><p key={m.id}>{m.id}: {m.reason}</p>)}{data.excludedBlocs?.map(b=><p key={b.id}>{b.name} excluded from weighted coverage: {b.reason}</p>)}</section>
 <section className={styles.explanation}><h2>What the total means</h2><p>Lag-1 monthly USD M2, using the last valid month-end FX. Aggregate definitions differ between blocs; source classifications identify exact, alternative and proxy series. This response does not supply a historical total series or publication timestamps.</p><p>Calculated: {data.calculatedAt}. Calculation time is separate from the observation months shown above.</p><Link href="/learn">Build your understanding</Link></section>
 </>}
 </article>;
}
