-- =====================================================
-- 026_crypto_universe_tiers.sql
-- Purpose: Expand crypto universe for CoinGecko-only operation
-- Safe to run multiple times (idempotent)
-- =====================================================

INSERT INTO symbol_universe (symbol, asset_type, name, tier, enabled)
VALUES
  -- Tier 1 (20 coins, 60s cadence)
  ('BTC', 'crypto', 'Bitcoin', 1, TRUE),
  ('ETH', 'crypto', 'Ethereum', 1, TRUE),
  ('SOL', 'crypto', 'Solana', 1, TRUE),
  ('BNB', 'crypto', 'Binance Coin', 1, TRUE),
  ('XRP', 'crypto', 'Ripple', 1, TRUE),
  ('ADA', 'crypto', 'Cardano', 1, TRUE),
  ('DOGE', 'crypto', 'Dogecoin', 1, TRUE),
  ('AVAX', 'crypto', 'Avalanche', 1, TRUE),
  ('LINK', 'crypto', 'Chainlink', 1, TRUE),
  ('DOT', 'crypto', 'Polkadot', 1, TRUE),
  ('TRX', 'crypto', 'Tron', 1, TRUE),
  ('TON', 'crypto', 'Toncoin', 1, TRUE),
  ('SHIB', 'crypto', 'Shiba Inu', 1, TRUE),
  ('LTC', 'crypto', 'Litecoin', 1, TRUE),
  ('BCH', 'crypto', 'Bitcoin Cash', 1, TRUE),
  ('XLM', 'crypto', 'Stellar', 1, TRUE),
  ('HBAR', 'crypto', 'Hedera', 1, TRUE),
  ('SUI', 'crypto', 'Sui', 1, TRUE),
  ('APT', 'crypto', 'Aptos', 1, TRUE),
  ('NEAR', 'crypto', 'Near Protocol', 1, TRUE),

  -- Tier 2 (50 coins, 240s cadence)
  ('MATIC', 'crypto', 'Polygon', 2, TRUE),
  ('UNI', 'crypto', 'Uniswap', 2, TRUE),
  ('ATOM', 'crypto', 'Cosmos', 2, TRUE),
  ('ARB', 'crypto', 'Arbitrum', 2, TRUE),
  ('OP', 'crypto', 'Optimism', 2, TRUE),
  ('ETC', 'crypto', 'Ethereum Classic', 2, TRUE),
  ('XMR', 'crypto', 'Monero', 2, TRUE),
  ('ALGO', 'crypto', 'Algorand', 2, TRUE),
  ('FIL', 'crypto', 'Filecoin', 2, TRUE),
  ('ICP', 'crypto', 'Internet Computer', 2, TRUE),
  ('VET', 'crypto', 'VeChain', 2, TRUE),
  ('CRO', 'crypto', 'Cronos', 2, TRUE),
  ('MNT', 'crypto', 'Mantle', 2, TRUE),
  ('INJ', 'crypto', 'Injective', 2, TRUE),
  ('RENDER', 'crypto', 'Render', 2, TRUE),
  ('FET', 'crypto', 'Fetch.ai', 2, TRUE),
  ('TAO', 'crypto', 'Bittensor', 2, TRUE),
  ('STX', 'crypto', 'Stacks', 2, TRUE),
  ('IMX', 'crypto', 'Immutable', 2, TRUE),
  ('AAVE', 'crypto', 'Aave', 2, TRUE),
  ('GRT', 'crypto', 'The Graph', 2, TRUE),
  ('MKR', 'crypto', 'Maker', 2, TRUE),
  ('RUNE', 'crypto', 'THORChain', 2, TRUE),
  ('THETA', 'crypto', 'Theta Network', 2, TRUE),
  ('FLOW', 'crypto', 'Flow', 2, TRUE),
  ('EGLD', 'crypto', 'MultiversX', 2, TRUE),
  ('KAS', 'crypto', 'Kaspa', 2, TRUE),
  ('SEI', 'crypto', 'Sei', 2, TRUE),
  ('JUP', 'crypto', 'Jupiter', 2, TRUE),
  ('BONK', 'crypto', 'Bonk', 2, TRUE),
  ('PEPE', 'crypto', 'Pepe', 2, TRUE),
  ('WIF', 'crypto', 'dogwifhat', 2, TRUE),
  ('ENA', 'crypto', 'Ethena', 2, TRUE),
  ('PYTH', 'crypto', 'Pyth Network', 2, TRUE),
  ('PENDLE', 'crypto', 'Pendle', 2, TRUE),
  ('TIA', 'crypto', 'Celestia', 2, TRUE),
  ('JASMY', 'crypto', 'JasmyCoin', 2, TRUE),
  ('SAND', 'crypto', 'The Sandbox', 2, TRUE),
  ('MANA', 'crypto', 'Decentraland', 2, TRUE),
  ('AXS', 'crypto', 'Axie Infinity', 2, TRUE),
  ('COMP', 'crypto', 'Compound', 2, TRUE),
  ('SNX', 'crypto', 'Synthetix', 2, TRUE),
  ('CRV', 'crypto', 'Curve DAO Token', 2, TRUE),
  ('LDO', 'crypto', 'Lido DAO', 2, TRUE),
  ('DYDX', 'crypto', 'dYdX', 2, TRUE),
  ('ZEC', 'crypto', 'Zcash', 2, TRUE),
  ('DASH', 'crypto', 'Dash', 2, TRUE),
  ('NEO', 'crypto', 'Neo', 2, TRUE),
  ('KAVA', 'crypto', 'Kava', 2, TRUE),
  ('GMX', 'crypto', 'GMX', 2, TRUE),

  -- Tier 3 (100 coins, 1200s cadence)
  ('ROSE', 'crypto', 'Oasis', 3, TRUE),
  ('IOTA', 'crypto', 'IOTA', 3, TRUE),
  ('ZIL', 'crypto', 'Zilliqa', 3, TRUE),
  ('QTUM', 'crypto', 'Qtum', 3, TRUE),
  ('ONT', 'crypto', 'Ontology', 3, TRUE),
  ('ONE', 'crypto', 'Harmony', 3, TRUE),
  ('BAT', 'crypto', 'Basic Attention Token', 3, TRUE),
  ('ZRX', 'crypto', '0x', 3, TRUE),
  ('ANKR', 'crypto', 'Ankr', 3, TRUE),
  ('SKL', 'crypto', 'Skale', 3, TRUE),
  ('CELO', 'crypto', 'Celo', 3, TRUE),
  ('HOT', 'crypto', 'Holo', 3, TRUE),
  ('ENJ', 'crypto', 'Enjin Coin', 3, TRUE),
  ('KNC', 'crypto', 'Kyber Network', 3, TRUE),
  ('YFI', 'crypto', 'yearn.finance', 3, TRUE),
  ('SUSHI', 'crypto', 'Sushi', 3, TRUE),
  ('BAL', 'crypto', 'Balancer', 3, TRUE),
  ('BAND', 'crypto', 'Band Protocol', 3, TRUE),
  ('API3', 'crypto', 'API3', 3, TRUE),
  ('UMA', 'crypto', 'UMA', 3, TRUE),
  ('STORJ', 'crypto', 'Storj', 3, TRUE),
  ('OCEAN', 'crypto', 'Ocean Protocol', 3, TRUE),
  ('LRC', 'crypto', 'Loopring', 3, TRUE),
  ('ILV', 'crypto', 'Illuvium', 3, TRUE),
  ('CELR', 'crypto', 'Celer Network', 3, TRUE),
  ('CTSI', 'crypto', 'Cartesi', 3, TRUE),
  ('AUDIO', 'crypto', 'Audius', 3, TRUE),
  ('MASK', 'crypto', 'Mask Network', 3, TRUE),
  ('RLC', 'crypto', 'iExec RLC', 3, TRUE),
  ('ASTR', 'crypto', 'Astar', 3, TRUE),
  ('GLM', 'crypto', 'Golem', 3, TRUE),
  ('DENT', 'crypto', 'Dent', 3, TRUE),
  ('ICX', 'crypto', 'ICON', 3, TRUE),
  ('SC', 'crypto', 'Siacoin', 3, TRUE),
  ('AR', 'crypto', 'Arweave', 3, TRUE),
  ('WAVES', 'crypto', 'Waves', 3, TRUE),
  ('MINA', 'crypto', 'Mina', 3, TRUE),
  ('HNT', 'crypto', 'Helium', 3, TRUE),
  ('CFX', 'crypto', 'Conflux', 3, TRUE),
  ('FLR', 'crypto', 'Flare', 3, TRUE),
  ('BLUR', 'crypto', 'Blur', 3, TRUE),
  ('WLD', 'crypto', 'Worldcoin', 3, TRUE),
  ('ORDI', 'crypto', 'ORDI', 3, TRUE),
  ('SATS', 'crypto', 'SATS', 3, TRUE),
  ('GALA', 'crypto', 'Gala', 3, TRUE),
  ('CAKE', 'crypto', 'PancakeSwap', 3, TRUE),
  ('XDC', 'crypto', 'XDC Network', 3, TRUE),
  ('NEXO', 'crypto', 'Nexo', 3, TRUE),
  ('KSM', 'crypto', 'Kusama', 3, TRUE),
  ('SXP', 'crypto', 'Solar', 3, TRUE),
  ('RSR', 'crypto', 'Reserve Rights', 3, TRUE),
  ('CKB', 'crypto', 'Nervos Network', 3, TRUE),
  ('ACH', 'crypto', 'Alchemy Pay', 3, TRUE),
  ('TRB', 'crypto', 'Tellor', 3, TRUE),
  ('NMR', 'crypto', 'Numeraire', 3, TRUE),
  ('SFP', 'crypto', 'SafePal', 3, TRUE),
  ('COTI', 'crypto', 'COTI', 3, TRUE),
  ('IO', 'crypto', 'io.net', 3, TRUE),
  ('BRETT', 'crypto', 'Brett', 3, TRUE),
  ('TURBO', 'crypto', 'Turbo', 3, TRUE),
  ('MEME', 'crypto', 'Memecoin', 3, TRUE),
  ('POPCAT', 'crypto', 'Popcat', 3, TRUE),
  ('MEW', 'crypto', 'cat in a dogs world', 3, TRUE),
  ('GNO', 'crypto', 'Gnosis', 3, TRUE),
  ('XTZ', 'crypto', 'Tezos', 3, TRUE),
  ('BTT', 'crypto', 'BitTorrent', 3, TRUE),
  ('XYO', 'crypto', 'XYO', 3, TRUE),
  ('LSK', 'crypto', 'Lisk', 3, TRUE),
  ('ZEN', 'crypto', 'Horizen', 3, TRUE),
  ('RVN', 'crypto', 'Ravencoin', 3, TRUE),
  ('DGB', 'crypto', 'DigiByte', 3, TRUE),
  ('SYS', 'crypto', 'Syscoin', 3, TRUE),
  ('PHA', 'crypto', 'Phala Network', 3, TRUE),
  ('CHR', 'crypto', 'Chromia', 3, TRUE),
  ('HOOK', 'crypto', 'Hooked Protocol', 3, TRUE),
  ('MAGIC', 'crypto', 'Magic', 3, TRUE),
  ('ARPA', 'crypto', 'ARPA', 3, TRUE),
  ('STRK', 'crypto', 'Starknet', 3, TRUE),
  ('ZK', 'crypto', 'zkSync', 3, TRUE),
  ('SUPER', 'crypto', 'SuperVerse', 3, TRUE),
  ('RARE', 'crypto', 'SuperRare', 3, TRUE),
  ('SSV', 'crypto', 'SSV Network', 3, TRUE),
  ('TWT', 'crypto', 'Trust Wallet Token', 3, TRUE),
  ('OGN', 'crypto', 'Origin Protocol', 3, TRUE),
  ('ALICE', 'crypto', 'MyNeighborAlice', 3, TRUE),
  ('FTM', 'crypto', 'Fantom', 3, TRUE),
  ('SNT', 'crypto', 'Status', 3, TRUE),
  ('STG', 'crypto', 'Stargate Finance', 3, TRUE),
  ('AMP', 'crypto', 'Amp', 3, TRUE),
  ('FXS', 'crypto', 'Frax Share', 3, TRUE),
  ('SLP', 'crypto', 'Smooth Love Potion', 3, TRUE),
  ('C98', 'crypto', 'Coin98', 3, TRUE),
  ('JTO', 'crypto', 'Jito', 3, TRUE),
  ('ZRO', 'crypto', 'LayerZero', 3, TRUE),
  ('OM', 'crypto', 'MANTRA', 3, TRUE),
  ('BICO', 'crypto', 'Biconomy', 3, TRUE),
  ('REQ', 'crypto', 'Request', 3, TRUE),
  ('SPELL', 'crypto', 'Spell Token', 3, TRUE),
  ('NKN', 'crypto', 'NKN', 3, TRUE),
  ('CHZ', 'crypto', 'Chiliz', 3, TRUE)
ON CONFLICT (symbol)
DO UPDATE SET
  asset_type = EXCLUDED.asset_type,
  name = EXCLUDED.name,
  tier = EXCLUDED.tier,
  enabled = TRUE,
  updated_at = NOW();

-- Optional emergency switch (run manually if needed):
-- UPDATE symbol_universe
-- SET enabled = FALSE, updated_at = NOW()
-- WHERE asset_type <> 'crypto';
