/**
 * GENERATED by scoring-audit-work/p3-gen-calibration.py — do not edit by hand. Daily bars only.
 *
 * Empirical calibration of the canonical setups (Phase 3 validation, Sep 2026). Each cell is asset × setup ×
 * direction × structural reward:risk band, measured by simulating the engine's own bracket: entry at the next
 * bar's open, exit at invalidation or target (invalidation first when both print in one bar), else a time stop
 * after 20 bars; costs 10 bps (equity) / 25 bps (crypto) round trip.
 *   pHit  = share of trades that reached the target before the invalidation (shrunk toward the bucket rate, k=200)
 *   expR  = mean realised R after costs (shrunk toward the bucket mean, k=200)
 * `reference` holds 21 quantiles (0,5,…,100%) of the calibrated expR per direction — the display score is the
 * percentile of a candidate's expR within its own direction, so long and short setups are graded on the same curve.
 *
 * RESULT: Expanding-window yearly folds (equity test 2018–2026, crypto 2020–2026), 30-day purge; no setup×direction (with or without regime split, R:R ≥ 0/1.0/1.5) produced out-of-sample PASS trades with a 90% block-bootstrap CI above zero. The raw factor score was uninformative out of sample (corr with R ≈ 0).
 * Hence passValidated = false everywhere: the engine never issues PASS and shows factors + these calibrated
 * statistics only. See /workspace/code-fixer/scoring-validation.md (Phase 3 report).
 */
export const CALIBRATION_META = {
  "version": "msp.calibration.daily.2026-09",
  "generated": "2026-09-26",
  "horizonBars": 20,
  "costsBps": {
    "equity": 10,
    "crypto": 25
  },
  "rrBands": [
    0.75,
    1.5,
    2.5
  ],
  "sample": {
    "equity": "Yahoo daily OHLC, 101 US large caps + 20 ETFs, signals 2015-03 \u2192 2026-09",
    "crypto": "Binance spot daily klines, 20 coins, signals 2018-06 \u2192 2026-09"
  },
  "walkForward": "Expanding-window yearly folds (equity test 2018\u20132026, crypto 2020\u20132026), 30-day purge; no setup\u00d7direction (with or without regime split, R:R \u2265 0/1.0/1.5) produced out-of-sample PASS trades with a 90% block-bootstrap CI above zero."
} as const;

export interface CalibrationCell { maxRR: number | null; pHit: number; expR: number; n: number }
export interface CalibrationBucket { n: number; dates: number; meanR: number; ci90: [number, number]; hit: number; baselineR: number; passValidated: boolean; cells: CalibrationCell[] }
export interface AssetCalibration { buckets: Record<string, CalibrationBucket>; reference: { long: number[]; short: number[] } }

export const CALIBRATION: Record<'equity' | 'crypto', AssetCalibration> = {
  "equity": {
    "buckets": {
      "EXHAUSTION_FADE:long": {
        "n": 12410,
        "dates": 2143,
        "meanR": 0.129,
        "ci90": [
          0.03,
          0.221
        ],
        "hit": 0.307,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.311,
            "expR": 0.065,
            "n": 65
          },
          {
            "maxRR": 1.5,
            "pHit": 0.349,
            "expR": 0.021,
            "n": 561
          },
          {
            "maxRR": 2.5,
            "pHit": 0.381,
            "expR": 0.148,
            "n": 4305
          },
          {
            "maxRR": null,
            "pHit": 0.26,
            "expR": 0.131,
            "n": 7479
          }
        ]
      },
      "EXHAUSTION_FADE:short": {
        "n": 24556,
        "dates": 2501,
        "meanR": -0.179,
        "ci90": [
          -0.257,
          -0.108
        ],
        "hit": 0.234,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.26,
            "expR": -0.136,
            "n": 23
          },
          {
            "maxRR": 1.5,
            "pHit": 0.301,
            "expR": -0.21,
            "n": 732
          },
          {
            "maxRR": 2.5,
            "pHit": 0.283,
            "expR": -0.154,
            "n": 9274
          },
          {
            "maxRR": null,
            "pHit": 0.198,
            "expR": -0.194,
            "n": 14527
          }
        ]
      },
      "PULLBACK:long": {
        "n": 72497,
        "dates": 2873,
        "meanR": -0.011,
        "ci90": [
          -0.04,
          0.017
        ],
        "hit": 0.571,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.721,
            "expR": -0.018,
            "n": 37450
          },
          {
            "maxRR": 1.5,
            "pHit": 0.516,
            "expR": -0.012,
            "n": 17008
          },
          {
            "maxRR": 2.5,
            "pHit": 0.339,
            "expR": 0.012,
            "n": 11205
          },
          {
            "maxRR": null,
            "pHit": 0.28,
            "expR": -0.016,
            "n": 6834
          }
        ]
      },
      "PULLBACK:short": {
        "n": 39727,
        "dates": 2851,
        "meanR": -0.135,
        "ci90": [
          -0.178,
          -0.093
        ],
        "hit": 0.508,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.66,
            "expR": -0.09,
            "n": 20409
          },
          {
            "maxRR": 1.5,
            "pHit": 0.443,
            "expR": -0.137,
            "n": 9620
          },
          {
            "maxRR": 2.5,
            "pHit": 0.296,
            "expR": -0.194,
            "n": 5457
          },
          {
            "maxRR": null,
            "pHit": 0.211,
            "expR": -0.268,
            "n": 4241
          }
        ]
      },
      "SQUEEZE:long": {
        "n": 72882,
        "dates": 2867,
        "meanR": 0.01,
        "ci90": [
          -0.02,
          0.038
        ],
        "hit": 0.6,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.744,
            "expR": -0.006,
            "n": 41293
          },
          {
            "maxRR": 1.5,
            "pHit": 0.514,
            "expR": 0.007,
            "n": 16049
          },
          {
            "maxRR": 2.5,
            "pHit": 0.324,
            "expR": 0.063,
            "n": 10116
          },
          {
            "maxRR": null,
            "pHit": 0.294,
            "expR": 0.042,
            "n": 5424
          }
        ]
      },
      "SQUEEZE:short": {
        "n": 72774,
        "dates": 2871,
        "meanR": -0.106,
        "ci90": [
          -0.144,
          -0.071
        ],
        "hit": 0.502,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.672,
            "expR": -0.085,
            "n": 34940
          },
          {
            "maxRR": 1.5,
            "pHit": 0.449,
            "expR": -0.092,
            "n": 18060
          },
          {
            "maxRR": 2.5,
            "pHit": 0.306,
            "expR": -0.122,
            "n": 10154
          },
          {
            "maxRR": null,
            "pHit": 0.201,
            "expR": -0.194,
            "n": 9620
          }
        ]
      },
      "TREND_CONTINUATION:long": {
        "n": 145432,
        "dates": 2877,
        "meanR": 0.005,
        "ci90": [
          -0.022,
          0.034
        ],
        "hit": 0.507,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.749,
            "expR": -0.007,
            "n": 80167
          },
          {
            "maxRR": 1.5,
            "pHit": 0.484,
            "expR": -0.012,
            "n": 15888
          },
          {
            "maxRR": 2.5,
            "pHit": 0.11,
            "expR": 0.035,
            "n": 45443
          },
          {
            "maxRR": null,
            "pHit": 0.271,
            "expR": -0.051,
            "n": 3934
          }
        ]
      },
      "TREND_CONTINUATION:short": {
        "n": 62167,
        "dates": 2875,
        "meanR": -0.121,
        "ci90": [
          -0.156,
          -0.08
        ],
        "hit": 0.503,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.682,
            "expR": -0.075,
            "n": 38540
          },
          {
            "maxRR": 1.5,
            "pHit": 0.384,
            "expR": -0.194,
            "n": 8315
          },
          {
            "maxRR": 2.5,
            "pHit": 0.113,
            "expR": -0.167,
            "n": 12939
          },
          {
            "maxRR": null,
            "pHit": 0.196,
            "expR": -0.341,
            "n": 2373
          }
        ]
      }
    },
    "reference": {
      "long": [
        -0.051,
        -0.018,
        -0.018,
        -0.016,
        -0.012,
        -0.012,
        -0.007,
        -0.007,
        -0.007,
        -0.007,
        -0.007,
        -0.006,
        -0.006,
        -0.006,
        0.007,
        0.012,
        0.035,
        0.035,
        0.035,
        0.063,
        0.148
      ],
      "short": [
        -0.341,
        -0.194,
        -0.194,
        -0.194,
        -0.194,
        -0.167,
        -0.154,
        -0.137,
        -0.122,
        -0.092,
        -0.092,
        -0.09,
        -0.09,
        -0.085,
        -0.085,
        -0.085,
        -0.085,
        -0.075,
        -0.075,
        -0.075,
        -0.075
      ]
    }
  },
  "crypto": {
    "buckets": {
      "EXHAUSTION_FADE:long": {
        "n": 1608,
        "dates": 392,
        "meanR": 0.056,
        "ci90": [
          -0.107,
          0.221
        ],
        "hit": 0.218,
        "baselineR": -0.01,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.207,
            "expR": 0.054,
            "n": 25
          },
          {
            "maxRR": 1.5,
            "pHit": 0.25,
            "expR": 0.17,
            "n": 211
          },
          {
            "maxRR": 2.5,
            "pHit": 0.252,
            "expR": 0.106,
            "n": 860
          },
          {
            "maxRR": null,
            "pHit": 0.154,
            "expR": -0.083,
            "n": 512
          }
        ]
      },
      "EXHAUSTION_FADE:short": {
        "n": 3077,
        "dates": 974,
        "meanR": -0.183,
        "ci90": [
          -0.308,
          -0.05
        ],
        "hit": 0.226,
        "baselineR": -0.035,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.231,
            "expR": -0.188,
            "n": 17
          },
          {
            "maxRR": 1.5,
            "pHit": 0.285,
            "expR": -0.103,
            "n": 270
          },
          {
            "maxRR": 2.5,
            "pHit": 0.259,
            "expR": -0.168,
            "n": 1277
          },
          {
            "maxRR": null,
            "pHit": 0.179,
            "expR": -0.218,
            "n": 1513
          }
        ]
      },
      "PULLBACK:long": {
        "n": 9138,
        "dates": 1992,
        "meanR": -0.08,
        "ci90": [
          -0.152,
          0.005
        ],
        "hit": 0.475,
        "baselineR": -0.01,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.674,
            "expR": -0.054,
            "n": 4116
          },
          {
            "maxRR": 1.5,
            "pHit": 0.421,
            "expR": -0.09,
            "n": 2337
          },
          {
            "maxRR": 2.5,
            "pHit": 0.277,
            "expR": -0.093,
            "n": 1478
          },
          {
            "maxRR": null,
            "pHit": 0.202,
            "expR": -0.126,
            "n": 1207
          }
        ]
      },
      "PULLBACK:short": {
        "n": 9819,
        "dates": 2042,
        "meanR": -0.083,
        "ci90": [
          -0.145,
          -0.025
        ],
        "hit": 0.525,
        "baselineR": -0.035,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.679,
            "expR": -0.051,
            "n": 5320
          },
          {
            "maxRR": 1.5,
            "pHit": 0.422,
            "expR": -0.127,
            "n": 2364
          },
          {
            "maxRR": 2.5,
            "pHit": 0.318,
            "expR": -0.145,
            "n": 1231
          },
          {
            "maxRR": null,
            "pHit": 0.258,
            "expR": -0.059,
            "n": 904
          }
        ]
      },
      "SQUEEZE:long": {
        "n": 16096,
        "dates": 2439,
        "meanR": -0.034,
        "ci90": [
          -0.118,
          0.048
        ],
        "hit": 0.516,
        "baselineR": -0.01,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.709,
            "expR": -0.025,
            "n": 7494
          },
          {
            "maxRR": 1.5,
            "pHit": 0.464,
            "expR": -0.027,
            "n": 4004
          },
          {
            "maxRR": 2.5,
            "pHit": 0.308,
            "expR": -0.083,
            "n": 2317
          },
          {
            "maxRR": null,
            "pHit": 0.212,
            "expR": -0.023,
            "n": 2281
          }
        ]
      },
      "SQUEEZE:short": {
        "n": 16096,
        "dates": 2439,
        "meanR": -0.085,
        "ci90": [
          -0.148,
          -0.021
        ],
        "hit": 0.566,
        "baselineR": -0.035,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.714,
            "expR": -0.043,
            "n": 9749
          },
          {
            "maxRR": 1.5,
            "pHit": 0.418,
            "expR": -0.146,
            "n": 3585
          },
          {
            "maxRR": 2.5,
            "pHit": 0.305,
            "expR": -0.15,
            "n": 1601
          },
          {
            "maxRR": null,
            "pHit": 0.246,
            "expR": -0.14,
            "n": 1161
          }
        ]
      },
      "TREND_CONTINUATION:long": {
        "n": 12468,
        "dates": 2162,
        "meanR": 0.007,
        "ci90": [
          -0.064,
          0.077
        ],
        "hit": 0.523,
        "baselineR": -0.01,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.725,
            "expR": -0.014,
            "n": 6941
          },
          {
            "maxRR": 1.5,
            "pHit": 0.418,
            "expR": -0.048,
            "n": 2028
          },
          {
            "maxRR": 2.5,
            "pHit": 0.205,
            "expR": 0.102,
            "n": 2827
          },
          {
            "maxRR": null,
            "pHit": 0.247,
            "expR": -0.009,
            "n": 672
          }
        ]
      },
      "TREND_CONTINUATION:short": {
        "n": 18078,
        "dates": 2205,
        "meanR": -0.071,
        "ci90": [
          -0.128,
          -0.014
        ],
        "hit": 0.557,
        "baselineR": -0.035,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.697,
            "expR": -0.035,
            "n": 12400
          },
          {
            "maxRR": 1.5,
            "pHit": 0.376,
            "expR": -0.167,
            "n": 2753
          },
          {
            "maxRR": 2.5,
            "pHit": 0.161,
            "expR": -0.131,
            "n": 2324
          },
          {
            "maxRR": null,
            "pHit": 0.261,
            "expR": -0.108,
            "n": 601
          }
        ]
      }
    },
    "reference": {
      "long": [
        -0.126,
        -0.093,
        -0.09,
        -0.083,
        -0.054,
        -0.054,
        -0.054,
        -0.048,
        -0.027,
        -0.027,
        -0.025,
        -0.025,
        -0.025,
        -0.023,
        -0.023,
        -0.014,
        -0.014,
        -0.014,
        -0.009,
        0.102,
        0.17
      ],
      "short": [
        -0.218,
        -0.168,
        -0.167,
        -0.15,
        -0.146,
        -0.145,
        -0.131,
        -0.127,
        -0.059,
        -0.051,
        -0.051,
        -0.043,
        -0.043,
        -0.043,
        -0.043,
        -0.035,
        -0.035,
        -0.035,
        -0.035,
        -0.035,
        -0.035
      ]
    }
  }
} as any;
