/**
 * GENERATED by scoring-audit-work/p4-gen-calibration.py — do not edit by hand. Daily bars only.
 *
 * Empirical calibration of the canonical setups (Phase 3 validation, re-run after the setup/levels fix-forward, Sep 2026). Each cell is asset × setup ×
 * direction × structural reward:risk band (setups at or above the minimum R:R only), measured by simulating the engine's own bracket: entry at the next
 * bar's open, exit at invalidation or target (invalidation first when both print in one bar), else a time stop
 * after 20 bars; costs 10 bps (equity) / 25 bps (crypto) round trip.
 *   pHit  = share of trades that reached the target before the invalidation (shrunk toward the bucket rate, k=200)
 *   expR  = mean realised R after costs (shrunk toward the bucket mean, k=200)
 * `reference` holds 21 quantiles (0,5,…,100%) of the calibrated expR per direction — the display score is the
 * percentile of a candidate's expR within its own direction, so long and short setups are graded on the same curve.
 *
 * RESULT: Fix-forward re-run with the corrected setup classifier and structural levels (Sep 2026). Expanding-window yearly folds (equity test 2018–2026, crypto 2020–2026), 30-day purge; no setup×direction (with or without regime split, R:R ≥ 0/1.0/1.5) produced out-of-sample PASS trades with a 90% block-bootstrap CI above zero. Minimum R:R 1.0 kept (1.0–1.5 band no worse than ≥ 1.5). The raw factor score was uninformative out of sample (corr with R ≈ 0).
 * Hence passValidated = false everywhere: the engine never issues PASS and shows factors + these calibrated
 * statistics only. See /workspace/code-fixer/scoring-validation.md (Phase 3 report + fix-forward addendum).
 */
export const CALIBRATION_META = {
  "version": "msp.calibration.daily.2026-09-fix1",
  "generated": "2026-09-26",
  "horizonBars": 20,
  "costsBps": {
    "equity": 10,
    "crypto": 25
  },
  "rrBands": [
    0.75,
    1.5,
    2.5
  ],
  "sample": {
    "equity": "Yahoo daily OHLC, 101 US large caps + 20 ETFs, signals 2015-03 \u2192 2026-09",
    "crypto": "Yahoo SYMBOL-USD daily (aggregated, like the live CoinGecko feed), 20 coins, signals 2015-07 \u2192 2026-09"
  },
  "walkForward": "Fix-forward re-run with the corrected setup classifier and structural levels (Sep 2026). Expanding-window yearly folds (equity test 2018\u20132026, crypto 2020\u20132026), 30-day purge; no setup\u00d7direction (with or without regime split, R:R \u2265 0/1.0/1.5) produced out-of-sample PASS trades with a 90% block-bootstrap CI above zero. Minimum R:R 1.0 kept (1.0\u20131.5 band no worse than \u2265 1.5).",
  "minRR": 1.0
} as const;

export interface CalibrationCell { maxRR: number | null; pHit: number; expR: number; n: number }
export interface CalibrationBucket { n: number; dates: number; meanR: number; ci90: [number, number]; hit: number; baselineR: number; passValidated: boolean; cells: CalibrationCell[] }
export interface AssetCalibration { buckets: Record<string, CalibrationBucket>; reference: { long: number[]; short: number[] } }

export const CALIBRATION: Record<'equity' | 'crypto', AssetCalibration> = {
  "equity": {
    "buckets": {
      "EXHAUSTION_FADE:long": {
        "n": 6195,
        "dates": 1752,
        "meanR": 0.145,
        "ci90": [
          0.021,
          0.257
        ],
        "hit": 0.326,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.326,
            "expR": 0.145,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.378,
            "expR": 0.075,
            "n": 1002
          },
          {
            "maxRR": 2.5,
            "pHit": 0.353,
            "expR": 0.104,
            "n": 2245
          },
          {
            "maxRR": null,
            "pHit": 0.285,
            "expR": 0.203,
            "n": 2948
          }
        ]
      },
      "EXHAUSTION_FADE:short": {
        "n": 9065,
        "dates": 2121,
        "meanR": -0.196,
        "ci90": [
          -0.284,
          -0.105
        ],
        "hit": 0.238,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.238,
            "expR": -0.196,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.3,
            "expR": -0.188,
            "n": 1214
          },
          {
            "maxRR": 2.5,
            "pHit": 0.268,
            "expR": -0.174,
            "n": 3122
          },
          {
            "maxRR": null,
            "pHit": 0.201,
            "expR": -0.213,
            "n": 4729
          }
        ]
      },
      "PULLBACK:long": {
        "n": 4841,
        "dates": 1899,
        "meanR": 0.033,
        "ci90": [
          -0.025,
          0.091
        ],
        "hit": 0.398,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.398,
            "expR": 0.033,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.48,
            "expR": 0.053,
            "n": 2223
          },
          {
            "maxRR": 2.5,
            "pHit": 0.341,
            "expR": 0.018,
            "n": 2113
          },
          {
            "maxRR": null,
            "pHit": 0.306,
            "expR": 0.018,
            "n": 505
          }
        ]
      },
      "PULLBACK:short": {
        "n": 3038,
        "dates": 1204,
        "meanR": -0.315,
        "ci90": [
          -0.404,
          -0.212
        ],
        "hit": 0.268,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.268,
            "expR": -0.315,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.342,
            "expR": -0.23,
            "n": 1377
          },
          {
            "maxRR": 2.5,
            "pHit": 0.218,
            "expR": -0.373,
            "n": 1220
          },
          {
            "maxRR": null,
            "pHit": 0.198,
            "expR": -0.392,
            "n": 441
          }
        ]
      },
      "SQUEEZE:long": {
        "n": 10731,
        "dates": 2283,
        "meanR": 0.032,
        "ci90": [
          -0.019,
          0.087
        ],
        "hit": 0.358,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.358,
            "expR": 0.032,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.485,
            "expR": 0.021,
            "n": 4080
          },
          {
            "maxRR": 2.5,
            "pHit": 0.274,
            "expR": 0.039,
            "n": 6010
          },
          {
            "maxRR": null,
            "pHit": 0.329,
            "expR": 0.032,
            "n": 641
          }
        ]
      },
      "SQUEEZE:short": {
        "n": 3010,
        "dates": 1501,
        "meanR": -0.231,
        "ci90": [
          -0.312,
          -0.143
        ],
        "hit": 0.316,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.316,
            "expR": -0.231,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.387,
            "expR": -0.201,
            "n": 1526
          },
          {
            "maxRR": 2.5,
            "pHit": 0.249,
            "expR": -0.254,
            "n": 1245
          },
          {
            "maxRR": null,
            "pHit": 0.256,
            "expR": -0.275,
            "n": 239
          }
        ]
      },
      "TREND_CONTINUATION:long": {
        "n": 13749,
        "dates": 2485,
        "meanR": 0.019,
        "ci90": [
          -0.04,
          0.08
        ],
        "hit": 0.271,
        "baselineR": 0.058,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.271,
            "expR": 0.019,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.469,
            "expR": 0.044,
            "n": 3058
          },
          {
            "maxRR": 2.5,
            "pHit": 0.21,
            "expR": 0.015,
            "n": 10106
          },
          {
            "maxRR": null,
            "pHit": 0.258,
            "expR": -0.024,
            "n": 585
          }
        ]
      },
      "TREND_CONTINUATION:short": {
        "n": 5894,
        "dates": 1826,
        "meanR": -0.269,
        "ci90": [
          -0.353,
          -0.167
        ],
        "hit": 0.224,
        "baselineR": -0.114,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.224,
            "expR": -0.269,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.329,
            "expR": -0.242,
            "n": 1867
          },
          {
            "maxRR": 2.5,
            "pHit": 0.173,
            "expR": -0.262,
            "n": 3533
          },
          {
            "maxRR": null,
            "pHit": 0.181,
            "expR": -0.383,
            "n": 494
          }
        ]
      }
    },
    "reference": {
      "long": [
        -0.024,
        0.015,
        0.015,
        0.015,
        0.015,
        0.015,
        0.015,
        0.018,
        0.021,
        0.021,
        0.032,
        0.039,
        0.039,
        0.039,
        0.044,
        0.044,
        0.053,
        0.075,
        0.104,
        0.203,
        0.203
      ],
      "short": [
        -0.392,
        -0.373,
        -0.373,
        -0.262,
        -0.262,
        -0.262,
        -0.254,
        -0.242,
        -0.242,
        -0.23,
        -0.213,
        -0.213,
        -0.213,
        -0.213,
        -0.213,
        -0.201,
        -0.188,
        -0.188,
        -0.174,
        -0.174,
        -0.174
      ]
    }
  },
  "crypto": {
    "buckets": {
      "EXHAUSTION_FADE:long": {
        "n": 1303,
        "dates": 409,
        "meanR": 0.162,
        "ci90": [
          -0.06,
          0.345
        ],
        "hit": 0.242,
        "baselineR": 0.007,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.242,
            "expR": 0.162,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.268,
            "expR": 0.182,
            "n": 252
          },
          {
            "maxRR": 2.5,
            "pHit": 0.26,
            "expR": 0.194,
            "n": 520
          },
          {
            "maxRR": null,
            "pHit": 0.207,
            "expR": 0.117,
            "n": 531
          }
        ]
      },
      "EXHAUSTION_FADE:short": {
        "n": 1983,
        "dates": 913,
        "meanR": -0.207,
        "ci90": [
          -0.384,
          -0.02
        ],
        "hit": 0.221,
        "baselineR": -0.056,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.221,
            "expR": -0.207,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.288,
            "expR": -0.158,
            "n": 377
          },
          {
            "maxRR": 2.5,
            "pHit": 0.223,
            "expR": -0.245,
            "n": 735
          },
          {
            "maxRR": null,
            "pHit": 0.184,
            "expR": -0.201,
            "n": 871
          }
        ]
      },
      "PULLBACK:long": {
        "n": 937,
        "dates": 642,
        "meanR": -0.056,
        "ci90": [
          -0.212,
          0.129
        ],
        "hit": 0.305,
        "baselineR": 0.007,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.305,
            "expR": -0.056,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.38,
            "expR": -0.012,
            "n": 431
          },
          {
            "maxRR": 2.5,
            "pHit": 0.29,
            "expR": -0.044,
            "n": 327
          },
          {
            "maxRR": null,
            "pHit": 0.201,
            "expR": -0.146,
            "n": 179
          }
        ]
      },
      "PULLBACK:short": {
        "n": 766,
        "dates": 451,
        "meanR": -0.244,
        "ci90": [
          -0.386,
          -0.055
        ],
        "hit": 0.283,
        "baselineR": -0.056,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.283,
            "expR": -0.244,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.321,
            "expR": -0.223,
            "n": 376
          },
          {
            "maxRR": 2.5,
            "pHit": 0.271,
            "expR": -0.222,
            "n": 286
          },
          {
            "maxRR": null,
            "pHit": 0.232,
            "expR": -0.32,
            "n": 104
          }
        ]
      },
      "SQUEEZE:long": {
        "n": 895,
        "dates": 663,
        "meanR": -0.113,
        "ci90": [
          -0.273,
          0.041
        ],
        "hit": 0.346,
        "baselineR": 0.007,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.346,
            "expR": -0.113,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.392,
            "expR": -0.099,
            "n": 441
          },
          {
            "maxRR": 2.5,
            "pHit": 0.324,
            "expR": -0.097,
            "n": 359
          },
          {
            "maxRR": null,
            "pHit": 0.289,
            "expR": -0.175,
            "n": 95
          }
        ]
      },
      "SQUEEZE:short": {
        "n": 1329,
        "dates": 700,
        "meanR": -0.158,
        "ci90": [
          -0.311,
          0.039
        ],
        "hit": 0.318,
        "baselineR": -0.056,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.318,
            "expR": -0.158,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.351,
            "expR": -0.206,
            "n": 692
          },
          {
            "maxRR": 2.5,
            "pHit": 0.293,
            "expR": -0.094,
            "n": 549
          },
          {
            "maxRR": null,
            "pHit": 0.284,
            "expR": -0.18,
            "n": 88
          }
        ]
      },
      "TREND_CONTINUATION:long": {
        "n": 1520,
        "dates": 951,
        "meanR": -0.058,
        "ci90": [
          -0.187,
          0.078
        ],
        "hit": 0.287,
        "baselineR": 0.007,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.287,
            "expR": -0.058,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.387,
            "expR": 0.012,
            "n": 567
          },
          {
            "maxRR": 2.5,
            "pHit": 0.253,
            "expR": -0.064,
            "n": 742
          },
          {
            "maxRR": null,
            "pHit": 0.181,
            "expR": -0.174,
            "n": 211
          }
        ]
      },
      "TREND_CONTINUATION:short": {
        "n": 1639,
        "dates": 783,
        "meanR": -0.197,
        "ci90": [
          -0.353,
          -0.038
        ],
        "hit": 0.248,
        "baselineR": -0.056,
        "passValidated": false,
        "cells": [
          {
            "maxRR": 0.75,
            "pHit": 0.248,
            "expR": -0.197,
            "n": 0
          },
          {
            "maxRR": 1.5,
            "pHit": 0.323,
            "expR": -0.178,
            "n": 678
          },
          {
            "maxRR": 2.5,
            "pHit": 0.201,
            "expR": -0.178,
            "n": 814
          },
          {
            "maxRR": null,
            "pHit": 0.195,
            "expR": -0.296,
            "n": 147
          }
        ]
      }
    },
    "reference": {
      "long": [
        -0.175,
        -0.174,
        -0.146,
        -0.099,
        -0.097,
        -0.097,
        -0.064,
        -0.064,
        -0.064,
        -0.044,
        -0.044,
        -0.012,
        0.012,
        0.012,
        0.012,
        0.117,
        0.117,
        0.182,
        0.194,
        0.194,
        0.194
      ],
      "short": [
        -0.32,
        -0.245,
        -0.245,
        -0.245,
        -0.223,
        -0.222,
        -0.206,
        -0.206,
        -0.206,
        -0.201,
        -0.201,
        -0.201,
        -0.178,
        -0.178,
        -0.178,
        -0.178,
        -0.178,
        -0.158,
        -0.158,
        -0.094,
        -0.094
      ]
    }
  }
} as any;
