import type { AdminSymbolIntelligence, ScannerHit, SystemHealth } from "./types";

export const mockSystemHealth: SystemHealth = {
  feed: "HEALTHY",
  websocket: "CONNECTED",
  scanner: "RUNNING",
  cache: "OK",
  api: "LOW_LATENCY",
};

export const mockScannerHits: ScannerHit[] = [
  {
    symbol: "ADA",
    bias: "LONG",
    regime: "TREND_EXPANSION",
    permission: "BLOCK",
    confidence: 68.5,
    symbolTrust: 53,
    sizeMultiplier: 0,
  },
  {
    symbol: "SUI",
    bias: "LONG",
    regime: "TREND_CONTINUATION",
    permission: "BLOCK",
    confidence: 68.0,
    symbolTrust: 52,
    sizeMultiplier: 0,
  },
  {
    symbol: "MATIC",
    bias: "LONG",
    regime: "TREND_CONTINUATION",
    permission: "BLOCK",
    confidence: 67.7,
    symbolTrust: 50,
    sizeMultiplier: 0,
  },
  {
    symbol: "FET",
    bias: "LONG",
    regime: "TREND_EXPANSION",
    permission: "WAIT",
    confidence: 66.8,
    symbolTrust: 51,
    sizeMultiplier: 0.3,
  },
];

export const mockSymbol: AdminSymbolIntelligence = {
  symbol: "ADA",
  timeframe: "15m",
  session: "FULL",
  price: 1.234,
  changePercent: 2.14,
  bias: "LONG",
  regime: "TREND_EXPANSION",
  permission: "BLOCK",
  confidence: 68.5,
  symbolTrust: 53,
  sizeMultiplier: 0,
  lastScanAt: "2026-04-01T19:32:00Z",
  blockReasons: ["LOW_LIQUIDITY", "WAIT_ZONE"],
  penalties: ["LOW_LIQUIDITY", "TIMING_NOT_CONFIRMED"],
  indicators: {
    ema20: 1.22,
    ema50: 1.19,
    ema200: 1.11,
    vwap: 1.225,
    atr: 0.034,
    bbwpPercentile: 81,
    adx: 28,
    rvol: 1.6,
  },
  dve: {
    state: "EXPANSION",
    direction: "BULLISH",
    persistence: 0.71,
    breakoutReadiness: 74,
    trap: false,
    exhaustion: false,
  },
  timeConfluence: {
    score: 72,
    hotWindow: true,
    alignmentCount: 4,
    nextClusterAt: "2026-04-01T19:45:00Z",
  },
  levels: {
    pdh: 1.245,
    pdl: 1.188,
    weeklyHigh: 1.29,
    weeklyLow: 1.14,
    monthlyHigh: 1.34,
    monthlyLow: 1.03,
    midpoint: 1.216,
    vwap: 1.225,
  },
  targets: {
    entry: 1.236,
    invalidation: 1.205,
    target1: 1.252,
    target2: 1.268,
    target3: 1.289,
  },
};
