vi.mock('@/lib/admin/cryptoOpsAlerts',()=>({reportCryptoCycleHealth:vi.fn(async()=>({ok:true}))}));
vi.mock('@/lib/admin/cryptoAutomation',()=>({runCryptoAutomation:vi.fn(async()=>({enabled:false,skipped:true}))}));
vi.mock('@/lib/admin/cryptoBreakoutVerdict',()=>({saveBreakoutVerdicts:vi.fn(async()=>({ok:true,saved:0,asOf:'2026-10-03T04:30:00.000Z',stale:false}))}));
import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {NextRequest} from 'next/server';
vi.mock('@/lib/adminAuth',()=>({requireAdmin:vi.fn(async()=>({ok:false}))}));
vi.mock('@/lib/admin/cryptoPaper',()=>({runCryptoPaperAll:vi.fn(async()=>({ok:true,accounts:0}))}));
vi.mock('@/lib/admin/cryptoPaperBase',()=>({runCryptoBaseSleeveAll:vi.fn(async()=>({ok:true,accounts:0}))}));
vi.mock('@/lib/db',()=>({q:vi.fn(async()=>[])}));
vi.mock('@/lib/admin/portfolio-lab/simulateCycle',()=>({simulateArcaCycle:vi.fn()}));
vi.mock('@/lib/admin/notifyAdmin',()=>({notifyAdmin:vi.fn()}));
import {runCryptoAutomation} from '@/lib/admin/cryptoAutomation';
import {runCryptoPaperAll} from '@/lib/admin/cryptoPaper';
import {runCryptoBaseSleeveAll} from '@/lib/admin/cryptoPaperBase';
import {saveBreakoutVerdicts} from '@/lib/admin/cryptoBreakoutVerdict';
import {q} from '@/lib/db';
import {POST} from '@/app/api/cron/arca-cycle/route';
const call=()=>POST(new NextRequest('https://example.test/api/cron/arca-cycle',{method:'POST',headers:{'x-cron-secret':'test-only-secret'}}));
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('ADMIN_DISCOVERY_ONLY','true');vi.stubEnv('CRON_SECRET','test-only-secret');});
afterEach(()=>vi.unstubAllEnvs());
it('stamps verdicts after paper entries and does not let a stamp failure change the cycle',async()=>{
 const ok=await call();
 expect(ok.status).toBe(200);
 expect(saveBreakoutVerdicts).toHaveBeenCalledTimes(1);
 expect(vi.mocked(runCryptoPaperAll).mock.invocationCallOrder[1]).toBeLessThan(vi.mocked(saveBreakoutVerdicts).mock.invocationCallOrder[0]);
 expect(vi.mocked(runCryptoBaseSleeveAll).mock.invocationCallOrder[1]).toBeLessThan(vi.mocked(saveBreakoutVerdicts).mock.invocationCallOrder[0]);
 expect(vi.mocked(runCryptoAutomation).mock.invocationCallOrder[0]).toBeLessThan(vi.mocked(saveBreakoutVerdicts).mock.invocationCallOrder[0]);
 expect((await ok.json()).breakoutVerdicts).toMatchObject({ok:true,saved:0});
 expect(q).not.toHaveBeenCalled();
 vi.mocked(saveBreakoutVerdicts).mockRejectedValueOnce(Error('redis down'));
 const still=await call();
 const stillBody=await still.json();
 expect(still.status).toBe(200);
 expect(stillBody.ok).toBe(true);
 expect(stillBody.breakoutVerdicts).toEqual({ok:false,error:'Breakout verdicts failed',saved:0});
});
it('does not stamp before auth, and a scan failure still attempts the advisory stamp without opening entries',async()=>{
 expect((await POST(new NextRequest('https://example.test/api/cron/arca-cycle',{method:'POST'}))).status).toBe(401);
 expect(saveBreakoutVerdicts).not.toHaveBeenCalled();
 vi.mocked(runCryptoAutomation).mockRejectedValueOnce(Error('scan offline'));
 const response=await call();
 expect(response.status).toBe(503);
 expect(runCryptoPaperAll).toHaveBeenCalledTimes(1);
 expect(runCryptoBaseSleeveAll).toHaveBeenCalledTimes(1);
 expect(saveBreakoutVerdicts).toHaveBeenCalledTimes(1);
});
it('pauses scans and CoinGecko work with HTTP 200 while exit checks still run',async()=>{
 vi.stubEnv('CRYPTO_MARKETS_PAUSED','true');
 const res=await call();
 expect(res.status).toBe(200);
 expect(await res.json()).toMatchObject({ok:true,paused:true,skipped:true,reason:'crypto_markets_paused',exitsPaused:false});
 expect(runCryptoAutomation).not.toHaveBeenCalled();
 expect(saveBreakoutVerdicts).not.toHaveBeenCalled();
 expect(runCryptoPaperAll).toHaveBeenCalledTimes(1);
 expect(runCryptoPaperAll).toHaveBeenCalledWith(true);
 expect(runCryptoBaseSleeveAll).toHaveBeenCalledTimes(1);
 expect(runCryptoBaseSleeveAll).toHaveBeenCalledWith(true);
});
it('CRYPTO_MARKETS_PAUSE_EXITS does nothing unless the main switch is on',async()=>{
 vi.stubEnv('CRYPTO_MARKETS_PAUSE_EXITS','true');
 const alone=await call();
 expect(alone.status).toBe(200);
 expect(runCryptoAutomation).toHaveBeenCalledTimes(1);
 expect(runCryptoPaperAll).toHaveBeenCalled();
});
it('both flags skip paper exit checks as well as scans',async()=>{
 vi.stubEnv('CRYPTO_MARKETS_PAUSED','true');
 vi.stubEnv('CRYPTO_MARKETS_PAUSE_EXITS','true');
 const both=await call();
 expect(both.status).toBe(200);
 expect((await both.json()).exitsPaused).toBe(true);
 expect(runCryptoPaperAll).not.toHaveBeenCalled();
 expect(runCryptoBaseSleeveAll).not.toHaveBeenCalled();
 expect(runCryptoAutomation).not.toHaveBeenCalled();
 expect(saveBreakoutVerdicts).not.toHaveBeenCalled();
});
it('keeps the hook inside the existing cron and out of execution modules',()=>{
 const route=readFileSync('app/api/cron/arca-cycle/route.ts','utf8');
 expect(route).toMatch(/saveBreakoutVerdicts\(\)/);
 expect(route).not.toMatch(/render\.yaml|new Cron|schedule\(/);
 const paper=readFileSync('lib/admin/cryptoPaper.ts','utf8')+readFileSync('lib/admin/cryptoPaperBase.ts','utf8');
 expect(paper).not.toMatch(/saveBreakoutVerdicts|BREAKOUT_VERDICT_KEY/);
});
