import {it,expect} from 'vitest';
import {parseExchangeCandles,selectCoinbasePair,exchangeVolumeReview} from '@/lib/admin/cryptoExchangeVolume';
const H=3600000,D=24*H,now=Date.parse('2026-09-28T12:30Z'),end=Math.floor(now/(4*H))*4*H;
it('uses identity-matched venue pair, not a guessed symbol',()=>{expect(selectCoinbasePair([{exchange:'gdax',pair:'MANTLE/USD',volumeUsd:1e6,spreadPct:.1,observedAt:new Date(now).toISOString()}],now)).toBe('MANTLE-USD');expect(selectCoinbasePair([{exchange:'binance',pair:'MNT/USDT',volumeUsd:1e6,spreadPct:.1,observedAt:new Date(now).toISOString()}],now)).toBeNull();});
it('converts Coinbase start seconds to close milliseconds and drops unfinished bars',()=>{const raw=[[end/1000,9,12,10,11,7],[(end-H)/1000,9,12,10,11,5]];expect(parseExchangeCandles(raw,H,end-H,end)).toEqual([{t:end,o:10,h:12,l:9,c:11,v:5}]);});
it('rejects negative volume, gaps and conflicting duplicates',()=>{expect(()=>parseExchangeCandles([[(end-H)/1000,9,12,10,11,-1]],H,end-H,end)).toThrow(/volume/);expect(()=>parseExchangeCandles([[(end-H)/1000,9,12,10,11,1],[(end-3*H)/1000,9,12,10,11,1]],H,end-3*H,end)).toThrow(/Missing/);expect(()=>parseExchangeCandles([[(end-H)/1000,9,12,10,11,1],[(end-H)/1000,9,12,10,11,2]],H,end-H,end)).toThrow(/Conflicting/);});
function fixture(){return {hourly:Array.from({length:120},(_,i)=>({t:end-(119-i)*H,o:100,h:101,l:99,c:100,v:i>=116?30:10})),daily:Array.from({length:40},(_,i)=>({t:Math.floor(now/D)*D-(39-i)*D,o:100,h:102,l:98,c:100,v:i>=33?50:100}))};}
it('sums actual 4h candle volume and excludes signal volume from baseline',()=>{const f=fixture(),r=exchangeVolumeReview('test','TEST-USD',f.hourly,f.daily,now);expect(r.latestVolume).toBe(120);expect(r.averageVolume).toBe(40);expect(r.relativeVolume).toBe(3);expect(r.contractionRatio).toBe(.5);expect(r.priceAndVolumeBreakout).toBe(false);});
it('requires both a fresh base crossing and contraction for a complete pattern',()=>{const f=fixture();f.hourly[119]={...f.hourly[119],h:104,c:103};expect(exchangeVolumeReview('test','TEST-USD',f.hourly,f.daily,now).priceAndVolumeBreakout).toBe(true);f.daily=f.daily.map(b=>({...b,v:100}));expect(exchangeVolumeReview('test','TEST-USD',f.hourly,f.daily,now).priceAndVolumeBreakout).toBe(false);});
