import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {CATALYST,CATALYST_QUESTIONS,attachCatalystShadow,cgTime,parseHeadlines} from '@/lib/admin/cryptoJevCatalyst';
import {catalystSideLabel,catalystFromReason,buildCalibration,paperObservations} from '@/lib/admin/cryptoCalibration';
import {catalystText} from '@/lib/admin/cryptoJevEvidence';
const now=Date.UTC(2026,9,1,8,5);
const savedKey=process.env.AI_GATEWAY_API_KEY;
const flat=(title:string,hoursAgo:number,related:string[]=['axie-infinity'])=>({title,url:'https://x.y/z',image:'',author:'',posted_at:new Date(now-hoursAgo*3600000).toISOString(),type:'news',source_name:'CoinDesk',related_coin_ids:related});
function store(){const m=new Map<string,unknown>();return {m,redis:{get:async(k:string)=>m.get(k)??null,set:async(k:string,v:unknown)=>{m.set(k,v);return 'OK';}} as never};}
const row=(id:string,stage='VOLUME_WATCH')=>({id,symbol:id.slice(0,3).toUpperCase(),stage,asOf:'2026-10-01T04:00:00.000Z',kind:'BREAKOUT' as const});
const notPaused=async()=>false;
beforeEach(()=>{process.env.AI_GATEWAY_API_KEY='jev-key';});
afterEach(()=>{vi.unstubAllGlobals();if(savedKey===undefined)delete process.env.AI_GATEWAY_API_KEY;else process.env.AI_GATEWAY_API_KEY=savedKey;});
it('parses both CoinGecko news shapes, keeps only coin-tagged items inside the window, newest first, capped',()=>{
 expect(cgTime('2026-10-01T08:00:00Z')).toBe(Date.UTC(2026,9,1,8));
 expect(cgTime(1759305600)).toBe(1759305600000);
 expect(cgTime('bad')).toBeNull();
 const feed=[flat('old',60),flat('future',-1),flat('other coin',2,['bitcoin']),flat('untagged',2,[]),...Array.from({length:12},(_,i)=>flat(`h${i}`,i+1))];
 const out=parseHeadlines(feed,'axie-infinity',now);
 expect(out).toHaveLength(CATALYST.maxHeadlines);
 expect(out[0].title).toBe('h0');
 expect(out.map(h=>h.title)).not.toContain('old');
 expect(out.map(h=>h.title)).not.toContain('other coin');
 expect(out.map(h=>h.title)).toContain('untagged');
 const wrapped={data:[{id:'1',type:'news',attributes:{title:'Wrapped item',news_site:'The Block',created_at:Math.floor((now-3600000)/1000)}}]};
 expect(parseHeadlines(wrapped,'axie-infinity',now)).toEqual([{title:'Wrapped item',source:'The Block',publishedAt:new Date(now-3600000).toISOString()}]);
 expect(parseHeadlines({nope:true},'axie-infinity',now)).toEqual([]);
});
it('sends the headlines and the five fixed questions, stores probabilities, and never changes a stage',async()=>{
 const fetcher=vi.fn(async()=>[flat('AXS listed on Coinbase',3)]);
 const fetch=vi.fn(async()=>({ok:true,json:async()=>({model:'jev-1.13.0',answers:{listingNews:{probability:.91},supplyEvent:{probability:.05},exploitOrOutage:{probability:.02},regulatoryNegative:{probability:.03},narrativeOnly:{probability:.2}},usage:{input_tokens:412}})}));
 vi.stubGlobal('fetch',fetch);
 const {redis}=store();
 const named=row('axie-infinity'),silent=row('nope','NO_SIGNAL');
 await attachCatalystShadow(redis,[named,silent],now,{fetcher,budgetPaused:notPaused});
 expect(named.stage).toBe('VOLUME_WATCH');
 expect(named.catalyst).toMatchObject({rule:'jev-catalyst-v2',status:'scored',source:'coingecko:/news?coin_id',headlines:1,listingNews:.91,narrativeOnly:.2,model:'jev-1.13.0',inputTokens:412});
 expect(silent.catalyst).toBeUndefined();
 expect(fetcher).toHaveBeenCalledWith('axie-infinity');
 const body=JSON.parse((fetch.mock.calls[0] as unknown as [string,{body:string}])[1].body);
 expect(body.questions).toEqual(CATALYST_QUESTIONS);
 expect(body.state).toMatchObject({coin:'AXI',coinId:'axie-infinity',stage:'VOLUME_WATCH',windowHours:48,headlines:[{title:'AXS listed on Coinbase',source:'CoinDesk'}]});
 expect(catalystText(named.catalyst,true)).toBe('1 headline · listing 0.91');
 await attachCatalystShadow(redis,[named],now,{fetcher,budgetPaused:notPaused});
 expect(fetch).toHaveBeenCalledTimes(1);
});
it('a coin with no headlines is no-headlines, Jev is not called, and the CoinGecko answer is cached',async()=>{
 const fetcher=vi.fn(async()=>[]);
 const fetch=vi.fn();vi.stubGlobal('fetch',fetch);
 const {redis}=store();
 const a=row('mew');await attachCatalystShadow(redis,[a],now,{fetcher,budgetPaused:notPaused});
 expect(a.catalyst?.status).toBe('no-headlines');
 expect(fetch).not.toHaveBeenCalled();
 const b=row('mew','EXTENDED');await attachCatalystShadow(redis,[b],now,{fetcher,budgetPaused:notPaused});
 expect(fetcher).toHaveBeenCalledTimes(1);
 expect(catalystSideLabel('listingNews',a.catalyst)).toBe('no headlines');
});
it('respects the per-batch CoinGecko budget and leaves unbudgeted rows for the next batch',async()=>{
 const fetcher=vi.fn(async()=>[]);
 const {redis}=store();
 const rows=Array.from({length:CATALYST.providerCallsPerBatch+5},(_,i)=>row(`coin-${i}`));
 await attachCatalystShadow(redis,rows,now,{fetcher,budgetPaused:notPaused});
 expect(fetcher).toHaveBeenCalledTimes(CATALYST.providerCallsPerBatch);
 expect(rows.filter(r=>!r.catalyst)).toHaveLength(5);
 expect(rows.every(r=>r.stage==='VOLUME_WATCH')).toBe(true);
});
it('makes no CoinGecko call while the shared credit budget says pause, and records why',async()=>{
 const fetcher=vi.fn();
 const {redis}=store();
 const a=row('sol');await attachCatalystShadow(redis,[a],now,{fetcher,budgetPaused:async()=>true});
 expect(fetcher).not.toHaveBeenCalled();
 expect(a.catalyst).toMatchObject({status:'unavailable',reason:'cg-paused'});
});
it('records CoinGecko failures, a missing Jev key, and Jev failures as unavailable with a reason',async()=>{
 const {redis}=store();
 const nul=row('q');await attachCatalystShadow(redis,[nul],now,{fetcher:async()=>null,budgetPaused:notPaused});
 expect(nul.catalyst).toMatchObject({status:'unavailable',reason:'cg-unavailable'});
 const thrown=row('t');await attachCatalystShadow(redis,[thrown],now,{fetcher:async()=>{throw new Error('429 from CoinGecko');},budgetPaused:notPaused});
 expect(thrown.catalyst).toMatchObject({status:'unavailable',reason:'cg-error',detail:'429 from CoinGecko'});
 const shape=row('s');await attachCatalystShadow(redis,[shape],now,{fetcher:async()=>({unexpected:true}),budgetPaused:notPaused});
 expect(shape.catalyst).toMatchObject({status:'unavailable',reason:'cg-bad-shape'});
 delete process.env.AI_GATEWAY_API_KEY;
 const noJev=row('j');await attachCatalystShadow(redis,[noJev],now,{fetcher:async()=>[flat('x',1,['j'])],budgetPaused:notPaused});
 expect(noJev.catalyst).toMatchObject({status:'unavailable',reason:'no-key',headlines:1});
 process.env.AI_GATEWAY_API_KEY='jev-key';
 vi.stubGlobal('fetch',vi.fn(async()=>({ok:false,status:500,json:async()=>({})})));
 const failed=row('f');await attachCatalystShadow(redis,[failed],now,{fetcher:async()=>[flat('y',1,['f'])],budgetPaused:notPaused});
 expect(failed.catalyst).toMatchObject({status:'unavailable',reason:'http-500'});
});
it('calibration reads the catalyst stamp from createdReason and grades no-headlines as a real side',()=>{
 const stamp=(p:number)=>({rule:'jev-catalyst-v2',status:'scored',source:'coingecko:/news?coin_id',windowHours:48,headlines:2,newestAt:null,listingNews:p,supplyEvent:.1,exploitOrOutage:.1,regulatoryNegative:.1,narrativeOnly:.5,model:'m',checkedAt:'2026-09-01T00:00:00Z'});
 const none={...stamp(0),status:'no-headlines',headlines:0,listingNews:null,supplyEvent:null,exploitOrOutage:null,regulatoryNegative:null,narrativeOnly:null,model:null};
 const mk=(i:number,r:number,c:unknown)=>({r_multiple:r,entry_time:new Date(Date.UTC(2026,8,1)+i*86400000).toISOString(),exit_reason:'x',instrument_type:'coinbase:X-USD',created_reason:'k|'+JSON.stringify({catalyst:c})});
 expect(catalystFromReason(mk(0,1,stamp(.9)).created_reason)?.listingNews).toBe(.9);
 const rows=[...Array.from({length:35},(_,i)=>mk(i,1,stamp(.9))),...Array.from({length:35},(_,i)=>mk(100+i,-1,none)),mk(500,0,undefined)];
 const ledger=buildCalibration(paperObservations(rows),[],{closedTrades:rows.length,forwardRows:0});
 const field=ledger.fields.find(f=>f.id==='catalyst.listingNews')!;
 expect(field.ruleVersion).toBe('jev-catalyst-v2');
 const high=field.sides.find(s=>s.side==='listing news ≥0.50')!,noneSide=field.sides.find(s=>s.side==='no headlines')!,nr=field.sides.find(s=>s.side==='NOT_RECORDED')!;
 expect(high.n).toBe(35);expect(noneSide.n).toBe(35);expect(noneSide.informational).toBe(false);expect(nr.informational).toBe(true);
 expect(high.lift).toBeGreaterThan(0);expect(noneSide.lift).toBeLessThan(0);
});
it('the crypto desk makes no Alpha Vantage call from any Jev or learning module',()=>{
 for(const f of ['lib/admin/cryptoJevCatalyst.ts','lib/admin/cryptoJev.ts','lib/admin/cryptoCalibration.ts','lib/admin/learningStatus.ts','lib/admin/cryptoJevEvidence.ts'])expect(readFileSync(f,'utf8')).not.toMatch(/avFetch|alphavantage|ALPHA_VANTAGE|equityNewsJev|transcriptJevAudit/);
 // The crypto cron may host the equity news daily step (DB + Jev only, owner-approved) but must never reach Alpha Vantage itself.
 expect(readFileSync('app/api/cron/arca-cycle/route.ts','utf8')).not.toMatch(/avFetch|alphavantage|ALPHA_VANTAGE|transcriptJevAudit/);
 expect(readFileSync('lib/admin/equityNewsJev.ts','utf8')).not.toMatch(/avFetch|alphavantage\.co/);
 expect(readFileSync('lib/admin/cryptoPaperMarket.ts','utf8')).not.toMatch(/cryptoJevCatalyst|catalyst/i);
 expect(readFileSync('lib/admin/cryptoAutomation.ts','utf8')).not.toMatch(/cryptoJevCatalyst|attachCatalystShadow/);
});
