import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
const avFetch=vi.fn();
vi.mock('@/lib/avRateGovernor',()=>({avFetch:(...a:unknown[])=>avFetch(...a)}));
import {CATALYST,CATALYST_QUESTIONS,attachCatalystShadow,avTime,parseHeadlines} from '@/lib/admin/cryptoJevCatalyst';
import {catalystSideLabel,catalystFromReason,buildCalibration,paperObservations} from '@/lib/admin/cryptoCalibration';
import {catalystText} from '@/lib/admin/cryptoJevEvidence';
const now=Date.UTC(2026,9,1,8,5);
const saved={av:process.env.ALPHA_VANTAGE_API_KEY,jev:process.env.AI_GATEWAY_API_KEY};
const feedItem=(title:string,hoursAgo:number,relevance='0.8',ticker='CRYPTO:AXS')=>({title,summary:`${title} summary`,source:'CoinDesk',time_published:new Date(now-hoursAgo*3600000).toISOString().replace(/[-:]/g,'').slice(0,15),ticker_sentiment:[{ticker,relevance_score:relevance}]});
function store(){const m=new Map<string,unknown>();return {m,redis:{get:async(k:string)=>m.get(k)??null,set:async(k:string,v:unknown)=>{m.set(k,v);return 'OK';}} as never};}
const row=(symbol:string,stage='VOLUME_WATCH')=>({id:symbol.toLowerCase(),symbol,stage,asOf:'2026-10-01T04:00:00.000Z',kind:'BREAKOUT' as const});
beforeEach(()=>{avFetch.mockReset();process.env.ALPHA_VANTAGE_API_KEY='av-key';process.env.AI_GATEWAY_API_KEY='jev-key';});
afterEach(()=>{vi.unstubAllGlobals();for(const [k,v] of [['ALPHA_VANTAGE_API_KEY',saved.av],['AI_GATEWAY_API_KEY',saved.jev]] as const){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
it('parses AV timestamps and keeps only coin-tagged headlines inside the window, newest first, capped',()=>{
 expect(avTime('20261001T080000')).toBe(Date.UTC(2026,9,1,8));
 expect(avTime('bad')).toBeNull();
 const feed=[feedItem('old',60),feedItem('future',-1),feedItem('low',2,'0.1'),feedItem('other coin',2,'0.9','CRYPTO:BTC'),...Array.from({length:12},(_,i)=>feedItem(`h${i}`,i+1))];
 const out=parseHeadlines({feed},'axs',now);
 expect(out).toHaveLength(CATALYST.maxHeadlines);
 expect(out[0].title).toBe('h0');
 expect(out.map(h=>h.title)).not.toContain('old');
 expect(out.map(h=>h.title)).not.toContain('low');
 expect(out.map(h=>h.title)).toContain('other coin');
 expect(out[0].summary.length).toBeLessThanOrEqual(CATALYST.summaryChars);
});
it('sends the headlines and the five fixed questions, stores probabilities, and never changes a stage',async()=>{
 avFetch.mockResolvedValue({feed:[feedItem('AXS listed on Coinbase',3)]});
 const fetch=vi.fn(async()=>({ok:true,json:async()=>({model:'jev-1.13.0',answers:{listingNews:{probability:.91},supplyEvent:{probability:.05},exploitOrOutage:{probability:.02},regulatoryNegative:{probability:.03},narrativeOnly:{probability:.2}},usage:{input_tokens:512}})}));
 vi.stubGlobal('fetch',fetch);
 const {redis}=store();
 const named=row('AXS'),silent=row('NO','NO_SIGNAL');
 await attachCatalystShadow(redis,[named,silent],now);
 expect(named.stage).toBe('VOLUME_WATCH');
 expect(named.catalyst).toMatchObject({rule:'jev-catalyst-v1',status:'scored',headlines:1,listingNews:.91,narrativeOnly:.2,model:'jev-1.13.0',inputTokens:512,source:'alphavantage:NEWS_SENTIMENT'});
 expect(silent.catalyst).toBeUndefined();
 expect(avFetch).toHaveBeenCalledTimes(1);
 expect(String(avFetch.mock.calls[0][0])).toContain('tickers=CRYPTO%3AAXS');
 expect(String(avFetch.mock.calls[0][0])).toContain('function=NEWS_SENTIMENT');
 const body=JSON.parse((fetch.mock.calls[0] as unknown as [string,{body:string}])[1].body);
 expect(body.questions).toEqual(CATALYST_QUESTIONS);
 expect(body.state).toMatchObject({coin:'AXS',stage:'VOLUME_WATCH',kind:'BREAKOUT',windowHours:48,headlines:[{title:'AXS listed on Coinbase',source:'CoinDesk'}]});
 expect(body.state.headlines[0]).not.toHaveProperty('relevance');
 expect(catalystText(named.catalyst,true)).toBe('1 headline · listing 0.91');
 await attachCatalystShadow(redis,[named],now);
 expect(fetch).toHaveBeenCalledTimes(1);
});
it('a coin with no coin-tagged headlines is no-headlines and Jev is not called; the headline fetch is cached',async()=>{
 avFetch.mockResolvedValue({feed:[]});
 const fetch=vi.fn();vi.stubGlobal('fetch',fetch);
 const {redis}=store();
 const a=row('MEW');
 await attachCatalystShadow(redis,[a],now);
 expect(a.catalyst?.status).toBe('no-headlines');
 expect(fetch).not.toHaveBeenCalled();
 const b=row('MEW','EXTENDED');
 await attachCatalystShadow(redis,[b],now);
 expect(avFetch).toHaveBeenCalledTimes(1);
 expect(catalystSideLabel('listingNews',a.catalyst)).toBe('no headlines');
});
it('respects the per-batch provider budget and leaves unbudgeted rows unstamped for the next batch',async()=>{
 avFetch.mockResolvedValue({feed:[]});
 const {redis}=store();
 const rows=Array.from({length:CATALYST.providerCallsPerBatch+5},(_,i)=>row(`C${i}`));
 await attachCatalystShadow(redis,rows,now);
 expect(avFetch).toHaveBeenCalledTimes(CATALYST.providerCallsPerBatch);
 expect(rows.filter(r=>!r.catalyst)).toHaveLength(5);
 expect(rows.every(r=>r.stage==='VOLUME_WATCH')).toBe(true);
});
it('records provider quota, missing keys, and Jev failures as unavailable with a reason',async()=>{
 const {redis,m}=store();
 avFetch.mockResolvedValueOnce({Note:'Thank you for using Alpha Vantage'});
 const quota=row('Q');await attachCatalystShadow(redis,[quota],now);
 expect(quota.catalyst).toMatchObject({status:'unavailable',reason:'av-quota'});
 delete process.env.ALPHA_VANTAGE_API_KEY;
 const noAv=row('N');await attachCatalystShadow(redis,[noAv],now);
 expect(noAv.catalyst).toMatchObject({status:'unavailable',reason:'no-av-key'});
 process.env.ALPHA_VANTAGE_API_KEY='av-key';delete process.env.AI_GATEWAY_API_KEY;
 avFetch.mockResolvedValueOnce({feed:[feedItem('x',1,'0.9','CRYPTO:J')]});
 const noJev=row('J');await attachCatalystShadow(redis,[noJev],now);
 expect(noJev.catalyst).toMatchObject({status:'unavailable',reason:'no-key',headlines:1});
 process.env.AI_GATEWAY_API_KEY='jev-key';
 vi.stubGlobal('fetch',vi.fn(async()=>({ok:false,status:500,json:async()=>({})})));
 avFetch.mockResolvedValueOnce({feed:[feedItem('y',1,'0.9','CRYPTO:F')]});
 const failed=row('F');await attachCatalystShadow(redis,[failed],now);
 expect(failed.catalyst).toMatchObject({status:'unavailable',reason:'http-500'});
 expect([...m.keys()].some(k=>k.includes('catalyst-news'))).toBe(true);
});
it('calibration reads the catalyst stamp from createdReason and grades no-headlines as a real side',()=>{
 const stamp=(p:number)=>({rule:'jev-catalyst-v1',status:'scored',source:'alphavantage:NEWS_SENTIMENT',windowHours:48,headlines:2,newestAt:null,listingNews:p,supplyEvent:.1,exploitOrOutage:.1,regulatoryNegative:.1,narrativeOnly:.5,model:'m',checkedAt:'2026-09-01T00:00:00Z'});
 const none={...stamp(0),status:'no-headlines',headlines:0,listingNews:null,supplyEvent:null,exploitOrOutage:null,regulatoryNegative:null,narrativeOnly:null,model:null};
 const mk=(i:number,r:number,c:unknown)=>({r_multiple:r,entry_time:new Date(Date.UTC(2026,8,1)+i*86400000).toISOString(),exit_reason:'x',instrument_type:'coinbase:X-USD',created_reason:'k|'+JSON.stringify({catalyst:c})});
 expect(catalystFromReason(mk(0,1,stamp(.9)).created_reason)?.listingNews).toBe(.9);
 const rows=[...Array.from({length:35},(_,i)=>mk(i,1,stamp(.9))),...Array.from({length:35},(_,i)=>mk(100+i,-1,none)),mk(500,0,undefined)];
 const ledger=buildCalibration(paperObservations(rows),[],{closedTrades:rows.length,forwardRows:0});
 const field=ledger.fields.find(f=>f.id==='catalyst.listingNews')!;
 const high=field.sides.find(s=>s.side==='listing news ≥0.50')!,noneSide=field.sides.find(s=>s.side==='no headlines')!,nr=field.sides.find(s=>s.side==='NOT_RECORDED')!;
 expect(high.n).toBe(35);expect(noneSide.n).toBe(35);expect(noneSide.informational).toBe(false);expect(nr.informational).toBe(true);
 expect(high.lift).toBeGreaterThan(0);expect(noneSide.lift).toBeLessThan(0);
});
it('the catalyst stamp never reaches the planner, the recommendations store, or the scheduler',()=>{
 expect(readFileSync('lib/admin/cryptoPaperMarket.ts','utf8')).not.toMatch(/cryptoJevCatalyst|catalyst/i);
 expect(readFileSync('lib/admin/cryptoRecommendations.ts','utf8')).not.toMatch(/cryptoJevCatalyst/);
 expect(readFileSync('lib/admin/cryptoAutomation.ts','utf8')).not.toMatch(/cryptoJevCatalyst|attachCatalystShadow/);
 expect(readFileSync('lib/admin/cryptoJevCatalyst.ts','utf8')).toMatch(/avFetch(<[^>]*>)?\(/);
 expect(readFileSync('lib/admin/cryptoJevCatalyst.ts','utf8')).not.toMatch(/avFetchAdmin/);
});
