export const COPY={
 top:{title:'Crypto at a glance',sourceUnavailable:'Source unavailable',priceUnavailable:'Price unavailable',unavailable:'—',change24h:'Change vs 24h ago',
  price:(v:number)=>'$'+v.toLocaleString('en-US',{minimumFractionDigits:v<1?0:2,maximumFractionDigits:v<1?8:2}),
  signedPercent:(v:number)=>`${v>0?'+':''}${v.toFixed(1)}%`,
  chartUnavailable:'Chart unavailable: daily bars missing.',baseLowUnavailable:'Base low unavailable',
  baseHigh:'Base high',baseLow:'Base low',ruleStop:'Rule stop',
  chartCaption:(date:string,baseDays:number)=>`Daily closes, last 90 completed UTC days · CoinGecko aggregate daily OHLC · last bar ${date}. Box = the ${baseDays}-day base the rule uses. Rule stop is the rule's definition, not a recommendation.`,
  chartLevel:(name:string,price:string)=>`${name} ${price}`,
  chipNames:['Base','Volume','Breakout','Extension'],met:'meets rule',notMet:'does not meet rule',insufficient:'not enough data',
  percent:(v:number)=>`${v.toFixed(1)}%`,multiple:(v:number)=>`${v.toFixed(2)}x`,atr:(v:number)=>`${v.toFixed(2)} ATR`,ratio:(v:number)=>v.toFixed(3),
  insufficientLine:(n:number,required:number)=>`Not enough data: has ${n} daily bars, needs ${required}.`,
  noBase:(range:string,limit:number,volume:string,volLimit:number)=>`No base: range ${range} vs the ${limit}% limit. Volume ${volume} the base median (rule: ${volLimit}x).`,
  watch:(range:string,limit:number,distance:string,price:string)=>`Base in place: range ${range} (limit ${limit}%). Last close is ${distance} below the base high; the rule close is ${price}.`,
  brokeOut:(failures:string)=>`Closed above the base high; rule not met: ${failures}.`,
  failedRule:(name:string,value:string,limit:string)=>`${name} ${value} (rule: ${limit})`,
  meets:(date:string)=>`Meets rules 1 to 4 at the last close (${date}). Research rule; no proven edge.`,
  extended:(value:string,limit:number)=>`Extended: ${value} above the base high (limit ${limit}).`,
  fellBack:'Fell back: closed below the base high within 5 days of meeting the rules.',
  lastBar:(date:string)=>`Last completed bar: ${date} (UTC day).`,
  utcDay:(date:string)=>`${date} UTC`,
  maxLimit:(v:string)=>`≤ ${v}`,minLimit:(v:string)=>`≥ ${v}`,
  chipSummary:(name:string,value:string,limit:string,state:string)=>`${name}: ${value}; rule ${limit}; ${state}`,

 },
 intro:'Facts and rule status only. Not a trade instruction.',footer:'Research snapshot. Not a trade instruction. The rules shown are research rules; none has a proven edge.',
 titles:{price:'Price',ruleCheck:'Rule check',earlyContext:'Early context',marketContext:'Market context',derivatives:'Derivatives',liquidity:'Liquidity',supply:'Supply',levels:'Levels',risks:'Risks and warnings',sourcesCheck:'Sources check',notes:'Notes'},
 daily:'Daily rule. The existing charts and tabs below retain their selected timeframe.',
 loading:'Loading crypto breakdown…',error:'Crypto breakdown unavailable.',refresh:'Refresh',empty:'Data unavailable for this section.',unknown:'time unknown',unavailable:'— · not reported or unavailable',
 coinId:'CoinGecko id',rank:'Market-cap rank',matches:'coins share this symbol',identityUnchecked:'Symbol uniqueness not checked for static-map or explicit-id resolution.',
 capped:'CoinGecko daily limit reached; showing cached observations with their original times.',budgetUnavailable:'CoinGecko accounting unavailable; showing cached data only.',
 marketWide:'Market-wide derivatives',journal:'Log to journal (draft)',watchlist:'Add to watchlist (draft)',drafts:'These links open draft forms. Nothing is saved until you choose Save.',
 statusTitle:'Rule status',statusHeaders:['Rule / idea','Verdict','Evidence and source'],yes:'yes',no:'no',
};
