'use client';
import type {CryptoPaperDecision} from '@/lib/admin/cryptoPaper';
import type {CryptoReconciliation} from '@/lib/admin/cryptoPaperReconciliation';
import {useEffect,useState} from 'react';
import type {ArcaPortfolio,ArcaPosition,ArcaTrade,ArcaJournalEntry} from '@/lib/admin/portfolio-lab/types';
import type {CryptoPaperStats as Stats,ExitPlanComparison} from '@/lib/admin/cryptoPaperStats';
import type {BtcRegime} from '@/lib/admin/cryptoBtcRegime';
import CryptoPaperStats from './CryptoPaperStats';
import {publishPaperSnapshot,usePaperSnapshot} from './cryptoPaperSnapshot';
type Limits={clusterRiskPct?:number;riskPerTradePct:number;notionalPct:number;maxPairVolumePct:number;maxVolumeAgeHours:number;positions:number;openRiskPct:number;dailyEntries:number;lossFromStartPct:number};
type State={trending?:{at:string;ids:string[];source:string}|null;limits?:Limits;btcRegime?:BtcRegime|null;stats?:Stats|null;exitPlans?:ExitPlanComparison|null;reconciliation?:CryptoReconciliation;automation?:{enabled:boolean;last?:{ok:boolean;at:string;error?:string}};portfolio:ArcaPortfolio|null;positions:ArcaPosition[];trades:ArcaTrade[];journal:ArcaJournalEntry[]};
const money=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
export default function CryptoPaperAccount({now,refreshVersion=0,onRefresh}:{now:number;refreshVersion?:number;onRefresh?:()=>void}){
 const [data,setData]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(action?:'enable'|'pause'|'cycle'|'auto_enable'|'auto_pause'){
  setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/admin/crypto-markets/paper',{method:action?'POST':'GET',cache:'no-store',...(action?{headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}:{})}),b=await r.json();if(!r.ok)throw Error(b.error||'Paper account unavailable');setData(b);publishPaperSnapshot(b);if(b.cycle?.reason)setNotice(b.cycle.reason);}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 useEffect(()=>{void load();},[refreshVersion]);
 // Adopt newer snapshots loaded by the attention strip so the summary and this table always match.
 const shared=usePaperSnapshot();
 useEffect(()=>{if(shared?.data?.portfolio!==undefined&&shared.data!==data)setData(d=>({...shared.data,cycle:(d as {cycle?:unknown}|null)?.cycle}));},[shared]);
 const decisions:CryptoPaperDecision[]=[];
 for(const j of data?.journal??[])for(const evidence of j.evidence??[]){try{const report=JSON.parse(evidence);if(Array.isArray(report.decisions))decisions.push(...report.decisions);}catch{}}
 const p=data?.portfolio,last=data?.journal.find(j=>j.title==='Crypto paper cycle completed');
 return <section id="crypto-paper" aria-label="Crypto paper account" className="space-y-3 rounded border border-violet-700 p-4 scroll-mt-4">
  <h2 className="text-xl">Crypto paper account · SIMULATED</h2>
  <p>Independent $200,000 paper ledger. Coinbase USD and OKX USDT momentum breakouts and continuations; no daily base requirement. OKX prices are converted into USD using observed Coinbase USDT/USD quotes. Other venues remain research-only.</p>
  {data?.limits&&<p className="text-xs text-slate-400">BETA DATA-COLLECTION LIMITS: {data.limits.riskPerTradePct}% risk per trade, reduced by 1/√(1+n) when n open positions have ≥0.7 correlation over the last 30 4h returns (minimum 25%; missing history counts as correlated){data.limits.clusterRiskPct!=null?<> · combined risk of any correlated cluster (a new entry plus the open positions correlated with it) capped at {data.limits.clusterRiskPct}% of equity; existing positions are never resized, an over-cap cluster is logged and blocks new correlated entries</>:null} · targets 2R from the actual fill (rule fill-2R-v1; earlier trades used 2R above the signal close) · {data.limits.notionalPct}% maximum notional per position · at most {data.limits.maxPairVolumePct}% of the pair's 24h volume (volume evidence under {data.limits.maxVolumeAgeHours}h old or no entry) · {data.limits.positions} open positions · {data.limits.openRiskPct}% open-risk cap · {data.limits.dailyEntries} entries per day · pause new entries below {100-data.limits.lossFromStartPct}% of starting equity. Raised to collect more trade outcomes; open positions are often correlated, so account-level drawdown is not representative of a live allocation. Judge the strategy by expectancy in R below.</p>}
  {(()=>{let c:{coins:string[];riskUsd:number;capUsd:number;overCap:boolean}[]|null|undefined;try{c=last?.evidence?.[0]?JSON.parse(last.evidence[0]).clusters:undefined;}catch{c=undefined;}
   return c===undefined?null:<p className="text-sm">Correlated clusters (latest cycle, all open positions): {c===null?'recheck unavailable':!c.length?'none at ≥0.7':c.map(x=><span key={x.coins.join()} className={x.overCap?'text-red-300':''}>{x.coins.join(' + ')} · risk {money(x.riskUsd)} of {money(x.capUsd)} cap{x.overCap?' · OVER CAP (not resized; new correlated entries blocked)':''}; </span>)}</p>;})()}
  <p>BTC daily trend: {data?.btcRegime?<>{data.btcRegime.state}{data.btcRegime.state!=='UNAVAILABLE'&&<> · close {data.btcRegime.close?.toLocaleString()} vs 20d {data.btcRegime.sma20?.toFixed(0)} / 50d {data.btcRegime.sma50?.toFixed(0)}</>} · 200-day regime {data.btcRegime.longTrend??'NOT_RECORDED'} · {data.btcRegime.reason} · {data.btcRegime.source}, candle {data.btcRegime.asOf??'—'} · checked {new Date(data.btcRegime.checkedAt).toLocaleString()}{now-Date.parse(data.btcRegime.checkedAt)>26*3600000?' · STALE':''}</>:'Not checked yet (checked during the next entry cycle with candidates)'}. Recorded on each entry for comparison; it does not block entries during beta.</p>
  <p className="text-xs text-slate-400">Estimated fee and slippage: 0.05% each per side for Coinbase; 0.10% each per side for OKX including the conversion leg. No real orders.</p>
  <p>Background scans: {data?.automation?.enabled?'ENABLED':'OFF'} · Manual scans remain available.</p>
  {data?.automation?.last&&<p>Last background scan batch: {new Date(data.automation.last.at).toLocaleString()} · {data.automation.last.ok?'Completed':'FAILED'} {data.automation.last.error??''}</p>}
  <button disabled={busy||!data} onClick={()=>void load(data?.automation?.enabled?'auto_pause':'auto_enable')} className="rounded border px-3 py-2">{data?.automation?.enabled?'Pause background scans':'Enable background scans'}</button>
  <p className="text-xs text-slate-400">When enabled, the 15-minute schedule advances up to 100 momentum coins and 20 daily-base coins per run. A new momentum scan starts each UTC 4h window; bases restart daily. Discovery refreshes when a new scan needs fresh coverage. A 300-coin momentum scan takes about 30–45 minutes. Turning this off does not pause paper exits.</p>
  <div className="flex flex-wrap gap-3">
   <button disabled={busy} onClick={()=>void load(p?.status==='ACTIVE'?'pause':'enable')} className="rounded bg-violet-800 px-3 py-2 disabled:opacity-50">{p?.status==='ACTIVE'?'Pause paper entries':p?'Resume paper entries':'Enable crypto paper account'}</button>
   {p&&<button disabled={busy} onClick={()=>void load('cycle')} className="rounded border px-3 py-2">Run paper cycle</button>}
   <button disabled={busy} onClick={()=>onRefresh?onRefresh():void load()} className="rounded border px-3 py-2">Refresh paper account</button>
  </div>
  {busy&&<p>Updating paper account…</p>}{error&&<p role="alert" className="text-red-300">{error}</p>}{notice&&<p>{notice}</p>}
  <details className="rounded border border-slate-700 p-3"><summary className="cursor-pointer text-sm">How the paper account works (schedule, exits, conversion)</summary>
  <p className="text-xs text-slate-400"><b>Target rule (fill-2R-v1):</b> the target is 2× the fill-to-stop distance above the actual fill, the same rule the backtest uses, so reward at the target (about 1.93R after costs) no longer depends on how long after the signal the entry filled. Positions opened before this change keep their original targets. <b>OKX target rule:</b> an OKX target counts only when the OKX high converted at the lowest Coinbase USDT/USD price in that 15-minute candle reaches it; a USD holder must convert, and the two venues&apos; extremes need not coincide. Touches that only reach the target at the best USDT/USD rate are reported as near-misses in the cycle notes, never filled.</p>
  <p className="text-xs text-slate-400">The scheduled paper cycle checks positions every 15 minutes, including when this page is closed. Pausing entries keeps exit monitoring active. Scheduled runs monitor exits first, advance the scan, then recheck positions and evaluate entries in the same run. New entries use the saved 4h momentum scan and a freshly rechecked setup plus bid/ask. Scans refresh automatically only when background scans are enabled above. Missing exit data blocks further entries.</p>
  <p className="text-xs text-slate-400">Stops and targets use completed 15-minute candles plus the latest quote. Both touched in one candle: stop first. Partial entry candle: a possible stop is charged conservatively; its target high is never credited. Gaps can lose more than planned risk. These are simulated results, not exchange fills.</p>
  <p className="text-xs text-slate-400">All paper prices and levels below are USD. Conversion costs are model estimates; no cross-exchange transfers or real orders occur. OKX stops and targets are fixed USD levels. Historical conversion uses matching 15-minute USDT/USD candles: possible stops and gap losses are charged conservatively; targets require a lower bound proving the level was reached. This can overstate stop hits or miss targets; it is not exact cross-exchange execution. Missing conversion history blocks monitoring and new entries. A USDT deviation over 2% blocks new OKX entries, while exits continue.</p>
  </details>
  {p&&<>
   <p>Entries: {p.status} · Equity {money(p.totalEquity)} · Cash {money(p.currentCash)} · Realised {money(p.realisedPnl)} · Open P&amp;L {money(p.unrealisedPnl)} (before exit costs)</p>
   <p>{last?`Last cycle ${new Date(last.createdAt).toLocaleString()}${now-Date.parse(last.createdAt)>25*60000?' · OVERDUE — check monitoring':''}`:'No completed cycle recorded yet'}</p>
   {last?.arcaReasoning&&<p className="text-sm text-slate-400">{last.arcaReasoning}</p>}
   <CryptoPaperStats stats={data?.stats} exitPlans={data?.exitPlans} />
   {data?.reconciliation&&<section aria-label="Paper account reconciliation" className="rounded border border-slate-700 p-3">
    <h3>Account reconciliation: {data.reconciliation.status}</h3>
    <p>Read-only check against starting cash, open-position costs and all closed trades. No balancing adjustment is made. Tolerance: $0.05.</p>
    {data.reconciliation.expectedCash!==undefined&&<p>Expected cash {money(data.reconciliation.expectedCash)} · Expected equity {money(data.reconciliation.expectedEquity!)} · Cash difference {money(data.reconciliation.cashDifference!)} · Equity difference {money(data.reconciliation.equityDifference!)} · Realised difference {money(data.reconciliation.realisedDifference!)}</p>}
    <p>Closed trades checked: {data.reconciliation.closedTrades??'—'} · Closed-trade fees: {data.reconciliation.closedFees===undefined?'—':money(data.reconciliation.closedFees)} · Open entry fees: {data.reconciliation.openEntryFees===undefined?'—':money(data.reconciliation.openEntryFees)} · Closed-trade mismatches: {data.reconciliation.invalidClosedTrades??'—'}</p>
    <p>{data.reconciliation.reason??'A matched ledger does not prove execution quality or profitability. Checks use a consistent account snapshot.'}</p>
   </section>}
   <details><summary>Recent setup decisions ({decisions.length})</summary>
    {!decisions.length?<p>Decision records appear after the next entry cycle.</p>:<div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Coin / venue','Decision','Reason','Observed bid / ask (USD)','Quote time','Checked'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{decisions.slice(0,100).map((d,i)=><tr key={i}><td>{d.coin} · {d.venue} · {d.product}</td><td>{d.status}</td><td>{d.reason}</td><td>{d.bid??'Not requested'} / {d.ask??'Not requested'}{d.conversion&&<><br/>USDT/USD {d.conversion.bid} / {d.conversion.ask}<br/>FX at {d.conversion.at}</>}</td><td>{d.quoteAt??'—'}</td><td>{new Date(d.checkedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
   </details>
   <h3 className="font-semibold">Open paper positions ({data!.positions.length})</h3>
   {!data!.positions.length?<p>No open paper positions. Entries require a qualifying setup and a valid current entry price.</p>:<div className="overflow-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{['Coin / source','Entry USD','Last mark USD','Stop USD','Target USD','Quantity','Open P&L','Marked at'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data!.positions.map(x=><tr key={x.id} className="border-t border-slate-700"><td className="p-2">{x.symbol}<br/>{x.instrumentType}{data!.trending?.ids.includes(x.symbol)&&<><br/><span className="text-amber-300" title={`${data!.trending.source} · ${new Date(data!.trending.at).toLocaleString()}`}>TRENDING · possible crowding</span></>}</td><td className="p-2">{x.averageEntry.toPrecision(6)}</td><td className="p-2">{x.currentPrice?.toPrecision(6)??'—'}</td><td className="p-2">{x.stopLoss?.toPrecision(6)}</td><td className="p-2">{x.takeProfit1?.toPrecision(6)}</td><td className="p-2">{x.quantity}</td><td className="p-2">{money(x.unrealisedPnl)}</td><td className="p-2">{x.lastMarkAt??'Not yet checked'}</td></tr>)}</tbody></table></div>}
   <p><a href="/api/admin/crypto-markets/paper?format=csv" className="underline">Download full trade log (CSV)</a> <span className="text-xs text-slate-400">Every paper entry: why it was taken (setup, signal, volume, BTC trend, funding, correlation, liquidity cap), its levels and size, and the outcome, including the shadow exit plan. SIMULATED.</span></p>
   <h3 className="font-semibold">Closed paper trades (latest 100)</h3>
   {!data!.trades.length?<p>No closed trades yet.</p>:<div className="overflow-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{['Coin','Entry','Exit','Net P&L','R','Reason','Closed at'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data!.trades.map(x=><tr key={x.id} className="border-t border-slate-700"><td className="p-2">{x.symbol}</td><td className="p-2">{x.entryPrice.toPrecision(6)}</td><td className="p-2">{x.exitPrice.toPrecision(6)}</td><td className="p-2">{money(x.realisedPnl)}</td><td className="p-2">{x.rMultiple?.toFixed(2)??'—'}</td><td className="p-2">{x.exitReason}</td><td className="p-2">{new Date(x.exitTime).toLocaleString()}</td></tr>)}</tbody></table></div>}
  </>}
 </section>;
}
