'use client';
import type {CryptoPaperDecision} from '@/lib/admin/cryptoPaper';
import type {CryptoReconciliation} from '@/lib/admin/cryptoPaperReconciliation';
import {useEffect,useState} from 'react';
import type {ArcaPortfolio,ArcaPosition,ArcaTrade,ArcaJournalEntry} from '@/lib/admin/portfolio-lab/types';
import type {CryptoPaperStats as Stats,ExitPlanComparison} from '@/lib/admin/cryptoPaperStats';
import type {BtcRegime} from '@/lib/admin/cryptoBtcRegime';
import CryptoPaperStats from './CryptoPaperStats';
import type {GiveBackView} from '@/lib/admin/cryptoPaperExcursion';
import type {LockState} from '@/lib/admin/cryptoPaperLock';
type LedgerView={rule:string;horizonDays:number;counts:{decision:string;status:string;n:number}[];skippedByReason:{reason:string;signals:number;avgR:number;winRate:number}[];variantE?:{signals:number;closed:number;open:number;avgR:number|null;winRate:number|null;openMarkR:number}};
import {publishPaperSnapshot,usePaperSnapshot} from './cryptoPaperSnapshot';
import {latestCryptoCycle} from '@/lib/admin/cryptoCycleReport';
type Limits={clusterRiskPct?:number;riskPerTradePct:number;notionalPct:number;maxPairVolumePct:number;maxVolumeAgeHours:number;positions:number;openRiskPct:number;dailyEntries:number;lossFromStartPct:number};
type Sleeve={mode:'SIMULATED';portfolio?:ArcaPortfolio|null;positions?:ArcaPosition[];giveBack?:GiveBackView|null;lock?:LockState|null};
type BaseSleeve=Sleeve&{trades?:ArcaTrade[];limits?:{positions:number;openRiskPct:number;dailyEntries:number;timeStopHours:number;timeStopMinR:number;riskPerTradePct:number}};
type State={trending?:{at:string;ids:string[];source:string}|null;limits?:Limits;btcRegime?:BtcRegime|null;stats?:Stats|null;exitPlans?:ExitPlanComparison[]|null;reconciliation?:CryptoReconciliation;automation?:{enabled:boolean;last?:{ok:boolean;at:string;error?:string}};portfolio:ArcaPortfolio|null;positions:ArcaPosition[];trades:ArcaTrade[];journal:ArcaJournalEntry[];research?:Sleeve;live?:Sleeve;base?:BaseSleeve;giveBack?:GiveBackView|null;lock?:LockState|null;signalLedger?:LedgerView|null};
const money=(n:number)=>n.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const qty=(n:number)=>n.toLocaleString(undefined,{maximumSignificantDigits:6});
const when=(iso:string|null|undefined)=>{const t=iso?Date.parse(iso):NaN;return Number.isFinite(t)?new Date(t).toLocaleString():iso??'Not yet checked';};
const rr=(n:number|null|undefined)=>n==null?'—':`${n>=0?'+':''}${n.toFixed(2)}R`;
function PositionsTable({positions,trending,giveBack}:{positions:ArcaPosition[];trending?:State['trending'];giveBack?:GiveBackView|null}){
 const gb=new Map((giveBack?.open??[]).map(o=>[o.positionId,o]));
 return <div className="overflow-auto"><table className="w-full min-w-[900px] text-left text-sm tabular-nums"><thead><tr>{['Coin / source','Entry USD','Last mark USD','Stop USD','Target USD','Quantity','Open P&L','Best / worst so far','Marked at'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{positions.map(x=><tr key={x.id} className="border-t border-slate-700"><td className="p-2">{x.symbol}<br/><span className="text-slate-400">{x.instrumentType}</span>{trending?.ids.includes(x.symbol)&&<><br/><span className="text-amber-300" title={`${trending.source} · ${new Date(trending.at).toLocaleString()}`}>TRENDING · possible crowding</span></>}</td><td className="p-2">{x.averageEntry.toPrecision(6)}</td><td className="p-2">{x.currentPrice?.toPrecision(6)??'—'}</td><td className="p-2">{x.stopLoss?.toPrecision(6)}</td><td className="p-2">{x.takeProfit1?.toPrecision(6)}</td><td className="p-2" title={String(x.quantity)}>{qty(x.quantity)}</td><td className={`p-2 ${x.unrealisedPnl<0?'text-red-300':'text-emerald-300'}`}>{money(x.unrealisedPnl)}</td><td className="p-2" title="MFE / MAE: best and worst net R from completed 15m candles since entry; give-back = share of the best open profit since lost">{(o=>o&&o.status!=='NOT_TRACKED'?<>{rr(o.mfeR)} / {rr(o.maeR)}{o.giveBack!=null&&<><br/><span className="text-slate-400">gave back {Math.round(o.giveBack*100)}%</span></>}</>:<span className="text-slate-500">Not tracked yet</span>)(gb.get(x.id))}</td><td className="p-2" title={x.lastMarkAt??undefined}>{when(x.lastMarkAt)}</td></tr>)}</tbody></table></div>;
}
/** Book-level give-back: open profit now vs the sum of each open position's best open profit, and the open P&L peak since tracking began. */
function BookGiveBack({view}:{view?:GiveBackView|null}){
 if(!view)return <p className="text-xs text-slate-400">Give-back tracking: not available yet (tables are created on the next paper cycle).</p>;
 const b=view.book,pk=view.openPnlPeak;
 return <p className="text-xs text-slate-300 tabular-nums">Give-back · open positions have given back {b.givenBackPct==null?'—':`${Math.round(b.givenBackPct*100)}%`} of their best open profit ({money(b.givenBackUsd)} of {money(b.peakOpenProfitUsd)}). Book open P&amp;L peak {pk.peak?`${money(pk.peak.value)} at ${new Date(pk.peak.at).toLocaleString()}`:'—'}; now {pk.last?money(pk.last.value):'—'}{pk.fromPeak!=null?` (${money(pk.fromPeak)} from peak)`:''}. Tracked since {pk.trackedSince?new Date(pk.trackedSince).toLocaleString():'—'} at 15-minute cycle marks; {view.counts.closed} closed trades measured, {view.counts.unavailable} unavailable. Research only.</p>;
}
/** Signal ledger: every 4h signal, taken or skipped; skipped ones replayed after the horizon (research only). */
function SignalLedger({view}:{view?:LedgerView|null}){
 if(!view)return <p className="text-xs text-slate-400">Signal ledger: starts recording on the next entry cycle.</p>;
 const n=(d:string,st?:string)=>view.counts.filter(c=>c.decision===d&&(!st||c.status===st)).reduce((a,c)=>a+c.n,0);
 return <details className="text-xs"><summary>Signal ledger · {n('TAKEN')} taken · {n('SKIPPED')} skipped ({n('SKIPPED','RESOLVED')} replayed, {n('SKIPPED','PENDING')} waiting {view.horizonDays} days, {n('SKIPPED','UNAVAILABLE')} unavailable)</summary>
  {view.variantE&&<p className="mt-1">Variant E in shadow (daily signals, BTC above its 200-day average, daily trend exits; no paper orders): {view.variantE.signals} signals · {view.variantE.closed} closed{view.variantE.avgR!=null?` · avg ${view.variantE.avgR>=0?'+':''}${view.variantE.avgR.toFixed(2)}R · win ${Math.round((view.variantE.winRate??0)*100)}%`:''} · {view.variantE.open} open (marked {view.variantE.openMarkR>=0?'+':''}{view.variantE.openMarkR.toFixed(2)}R total).{view.variantE.closed<30?' Under 30 closed: not yet meaningful.':''}</p>}
  <p className="mt-1 text-slate-400">Skipped signals are replayed as if entered at the decision quote (or the next 15m open) through the same fixed-2R plan and every shadow plan. Entry-zone and chase checks are bypassed so filters can be judged; each row records whether the zone would have passed. Research only.</p>
  {view.skippedByReason.length?<div className="overflow-auto"><table className="w-full min-w-[520px] text-left tabular-nums"><thead><tr>{['Skip reason','Replayed','Avg R (fixed 2R)','Win rate'].map(h=><th className="p-1" key={h}>{h}</th>)}</tr></thead><tbody>{view.skippedByReason.map(g=><tr key={g.reason} className="border-t border-slate-700"><td className="p-1">{g.reason}</td><td className="p-1">{g.signals}{g.signals<10?<span className="text-amber-300"> · few</span>:null}</td><td className={`p-1 ${g.avgR>0?'text-emerald-300':'text-red-300'}`}>{g.avgR>=0?'+':''}{g.avgR.toFixed(2)}R</td><td className="p-1">{Math.round(g.winRate*100)}%</td></tr>)}</tbody></table></div>:<p className="mt-1 text-slate-400">No skipped signals replayed yet.</p>}
 </details>;
}
/** Shadow portfolio lock: research only; it never moves a paper stop. */
function ShadowLock({lock}:{lock?:LockState|null}){
 if(!lock)return <p className="text-xs text-slate-400">Shadow portfolio lock: starts on the next paper cycle.</p>;
 const e=lock.episode,done=lock.completed,lockSum=done.reduce((a,c)=>a+c.lockTotalR,0),ledgerSum=done.reduce((a,c)=>a+c.ledgerTotalR,0);
 return <p className="text-xs text-slate-300 tabular-nums">Shadow portfolio lock (arms at open P&amp;L {money(lock.armUsd)}, triggers on a 40% fall from peak; tightens stops in shadow only): {lock.phase==='TRIGGERED'&&e?<>triggered {new Date(e.triggeredAt).toLocaleString()} (peak {money(e.peakOpenPnl)} → {money(e.triggerOpenPnl)}); {e.positions.filter(p=>p.status!=='OPEN').length} of {e.positions.length} locked positions resolved.</>:<>watching · peak {money(lock.peakOpenPnl)} since {new Date(lock.since).toLocaleString()} · {lock.peakOpenPnl>=lock.armUsd?'armed':'not armed'}.</>} {done.length?<>Completed episodes: {done.length} · lock {lockSum>=0?'+':''}{lockSum.toFixed(2)}R vs ledger {ledgerSum>=0?'+':''}{ledgerSum.toFixed(2)}R on the same positions.</>:'No completed episodes yet.'}</p>;
}
export default function CryptoPaperAccount({now,refreshVersion=0,onRefresh}:{now:number;refreshVersion?:number;onRefresh?:()=>void}){
 const [data,setData]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(action?:'enable'|'pause'|'cycle'|'auto_enable'|'auto_pause'){
  setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/admin/crypto-markets/paper',{method:action?'POST':'GET',cache:'no-store',...(action?{headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}:{})}),b=await r.json();if(!r.ok)throw Error(b.error||'Paper account unavailable');setData(b);publishPaperSnapshot(b);if(b.cycle?.reason)setNotice(b.cycle.reason);}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 useEffect(()=>{void load();},[refreshVersion]);
 // Adopt newer snapshots loaded by the attention strip so the summary and this table always match.
 const shared=usePaperSnapshot();
 useEffect(()=>{if(shared?.data?.portfolio!==undefined&&shared.data!==data)setData(d=>({...shared.data,cycle:(d as {cycle?:unknown}|null)?.cycle}));},[shared]);
 const decisions:CryptoPaperDecision[]=[];
 for(const j of data?.journal??[])for(const evidence of j.evidence??[]){try{const report=JSON.parse(evidence);if(Array.isArray(report.decisions))decisions.push(...report.decisions);}catch{}}
 const p=data?.portfolio,last=latestCryptoCycle(data?.journal??[]);
 const withR=data?.stats?.overall.withR??0;
 const noise=!data?.stats||withR<30;
 const openRiskUsd=(data?.positions??[]).reduce((sum,position)=>sum+(Number(position.openRisk)||0),0);
 const cycleOverdue=!!last&&now-Date.parse(last.createdAt)>25*60000;
 // The cycle note arrives as one semicolon-joined string; each clause is its own finding.
 const noticeLines=notice.split(/;\s+(?=[a-z])/i).map(s=>s.trim()).filter(Boolean);
 let clusters:{coins:string[];riskUsd:number;capUsd:number;overCap:boolean}[]|null|undefined;
 try{clusters=last?.evidence?.[0]?JSON.parse(last.evidence[0]).clusters:undefined;}catch{clusters=undefined;}
 return <section id="crypto-paper" aria-label="Crypto paper account" className="space-y-3 rounded border border-violet-700 p-4 scroll-mt-4">
  <h2 className="text-xl">Crypto paper account <span className="text-sm font-normal text-slate-400">· two independent $200,000 ledgers · SIMULATED, no exchange orders</span></h2>
  {p?<dl className="crypto-paper-balances">
   <div><dt>Entries</dt><dd className={p.status==='ACTIVE'?'text-emerald-300':'text-amber-300'}>{p.status}</dd></div>
   <div><dt>Equity</dt><dd>{money(p.totalEquity)}</dd></div>
   <div><dt>Cash</dt><dd>{money(p.currentCash)}</dd></div>
   <div><dt>Realised P&amp;L</dt><dd>{money(p.realisedPnl)}</dd></div>
   <div><dt>Open P&amp;L</dt><dd className={p.unrealisedPnl<0?'text-red-300':'text-emerald-300'}>{money(p.unrealisedPnl)}</dd><span className="text-xs text-slate-400">before exit costs</span></div>
  </dl>
   :data&&<p>No paper account yet. Enable it below; nothing is sent to an exchange.</p>}
  <div className="flex flex-wrap gap-3">
   <button disabled={busy} onClick={()=>void load(p?.status==='ACTIVE'?'pause':'enable')} className="rounded bg-violet-800 px-3 py-2 disabled:opacity-50">{p?.status==='ACTIVE'?'Pause paper entries':p?'Resume paper entries':'Enable crypto paper account'}</button>
   {p&&<button disabled={busy} onClick={()=>void load('cycle')} className="rounded border px-3 py-2">Run paper cycle</button>}
   <button disabled={busy||!data} onClick={()=>void load(data?.automation?.enabled?'auto_pause':'auto_enable')} className="rounded border px-3 py-2">{data?.automation?.enabled?'Pause background scans':'Enable background scans'}</button>
   <button disabled={busy} onClick={()=>onRefresh?onRefresh():void load()} className="rounded border px-3 py-2">Refresh paper account</button>
  </div>
  {busy&&<p>Updating paper account…</p>}{error&&<p role="alert" className="text-red-300">{error}</p>}
  <ul className="space-y-1 text-sm">
   <li>Last cycle: {last?<>{last.title} · {new Date(last.createdAt).toLocaleString()}{cycleOverdue&&<span className="text-amber-300"> · OVERDUE — check monitoring</span>}</>:'no completed cycle recorded yet'}</li>
   <li>Background scans: <span className={data?.automation?.enabled?'text-emerald-300':'text-amber-300'}>{data?.automation?.enabled?'ENABLED':'OFF'}</span>{data?.automation?.last&&<> · last batch {new Date(data.automation.last.at).toLocaleString()} · {data.automation.last.ok?'completed':<span className="text-red-300">FAILED {data.automation.last.error??''}</span>}</>} · manual scans remain available</li>
   {data&&noise&&<li>{data.stats?`${withR} of 30 closed trades with R`:'Closed trades with R could not be read.'} · Open risk {p?money(openRiskUsd):'—'} · cap {data.limits?.openRiskPct??'—'}%{p&&data.limits?` (${money(p.totalEquity*data.limits.openRiskPct/100)})`:''} · Cluster cap {data.limits?.clusterRiskPct??'—'}% of equity{p&&data.limits?.clusterRiskPct!=null?` (${money(p.totalEquity*data.limits.clusterRiskPct/100)})`:''}</li>}
   {clusters!==undefined&&<li>Correlated clusters (latest cycle): {clusters===null?'recheck unavailable':!clusters.length?'none at ≥0.7':clusters.map((x,i)=><span key={x.coins.join()} className={x.overCap?'text-red-300':''}>{i?'; ':''}{x.coins.join(' + ')} · risk {money(x.riskUsd)} of {money(x.capUsd)} cap{x.overCap?' · OVER CAP (not resized; new correlated entries blocked)':''}</span>)}</li>}
   <li>BTC daily trend: {data?.btcRegime?<>{data.btcRegime.state}{data.btcRegime.state!=='UNAVAILABLE'&&<> · close {data.btcRegime.close?.toLocaleString()} vs 20d {data.btcRegime.sma20?.toFixed(0)} / 50d {data.btcRegime.sma50?.toFixed(0)}</>} · 200-day {data.btcRegime.longTrend??'NOT_RECORDED'} · <span title={`${data.btcRegime.reason} · ${data.btcRegime.source}, candle ${data.btcRegime.asOf??'—'}`}>checked {new Date(data.btcRegime.checkedAt).toLocaleString()}</span>{now-Date.parse(data.btcRegime.checkedAt)>26*3600000?<span className="text-amber-300"> · STALE</span>:''}</>:'not checked yet (runs on the next entry cycle with candidates)'} · recorded on each entry; DOWN skips live-sleeve entries (the research sleeve still records them for comparison)</li>
   {last?.arcaReasoning&&<li className="text-slate-400">{last.arcaReasoning}</li>}
  </ul>
  {!!noticeLines.length&&<div className="rounded border border-slate-700 p-3 text-sm"><p className="text-xs text-slate-400">Latest cycle notes</p><ul className="mt-1 list-disc space-y-1 pl-5">{noticeLines.map((line,i)=><li key={i}>{line}</li>)}</ul></div>}
  {data?.limits&&!noise&&<p className="text-xs text-slate-400">BETA DATA-COLLECTION LIMITS: {data.limits.riskPerTradePct}% risk per trade, reduced by 1/√(1+n) when n open positions have ≥0.7 correlation over the last 30 4h returns (minimum 25%; missing history counts as correlated){data.limits.clusterRiskPct!=null?<> · combined risk of any correlated cluster (a new entry plus the open positions correlated with it) capped at {data.limits.clusterRiskPct}% of equity; existing positions are never resized, an over-cap cluster is logged and blocks new correlated entries</>:null} · targets 2R from the actual fill (rule fill-2R-v1; earlier trades used 2R above the signal close) · {data.limits.notionalPct}% maximum notional per position · at most {data.limits.maxPairVolumePct}% of the pair's 24h volume (volume evidence under {data.limits.maxVolumeAgeHours}h old or no entry) · {data.limits.positions} open positions · {data.limits.openRiskPct}% open-risk cap · {data.limits.dailyEntries} entries per day · pause new entries below {100-data.limits.lossFromStartPct}% of starting equity. Raised to collect more trade outcomes; open positions are often correlated, so account-level drawdown is not representative of a live allocation. Judge the strategy by expectancy in R below.</p>}
  <details className="rounded border border-slate-700 p-3"><summary className="cursor-pointer text-sm">How the paper account works (sleeves, schedule, exits, conversion, fees)</summary>
  <p className="text-xs text-slate-400"><b>Two sleeves.</b> Research sleeve: today's beta limits; it records an entry the live sleeve refused. Live sleeve: one open position per correlation cluster; a new entry is refused when that cluster is already over the cap, and open positions are not resized. Both are independent $200,000 paper ledgers taking Coinbase USD and OKX USDT momentum breakouts and continuations with no daily base requirement. OKX prices are converted into USD using observed Coinbase USDT/USD quotes. Other venues remain research-only.</p>
  <p className="text-xs text-slate-400"><b>Background scans.</b> When enabled, the 15-minute schedule advances up to 100 momentum coins and 20 daily-base coins per run. A new momentum scan starts each UTC 4h window; bases restart daily. Discovery refreshes when a new scan needs fresh coverage. A 300-coin momentum scan takes about 30–45 minutes. Turning this off does not pause paper exits.</p>
  <p className="text-xs text-slate-400"><b>Costs.</b> Estimated fee and slippage: 0.05% each per side for Coinbase; 0.10% each per side for OKX including the conversion leg. No real orders.</p>
  <p className="text-xs text-slate-400"><b>Target rule (fill-2R-v1):</b> the target is 2× the fill-to-stop distance above the actual fill, the same rule the backtest uses, so reward at the target (about 1.93R after costs) no longer depends on how long after the signal the entry filled. Positions opened before this change keep their original targets. <b>Time stop (crypto-momentum-v2, entries from 2026-09-30):</b> a position that never reached +1R on a completed 15m candle closes at the first completed candle at or after 72h (18 signal-timeframe candles), at that candle&apos;s close less slippage, exit reason TIME_EXIT. It frees the 20-position cap from dead trades; it never touches positions opened under v1, whose checkpoints carry no rule. <b>OKX target rule:</b> an OKX target counts only when the OKX high converted at the lowest Coinbase USDT/USD price in that 15-minute candle reaches it; a USD holder must convert, and the two venues&apos; extremes need not coincide. Touches that only reach the target at the best USDT/USD rate are reported as near-misses in the cycle notes, never filled.</p>
  <p className="text-xs text-slate-400">The scheduled paper cycle checks positions every 15 minutes, including when this page is closed. Pausing entries keeps exit monitoring active. Scheduled runs monitor exits first, advance the scan, then recheck positions and evaluate entries in the same run. New entries use the saved 4h momentum scan and a freshly rechecked setup plus bid/ask. Scans refresh automatically only when background scans are enabled above. Missing exit data blocks further entries.</p>
  <p className="text-xs text-slate-400">Stops and targets use completed 15-minute candles plus the latest quote. Both touched in one candle: stop first. Partial entry candle: a possible stop is charged conservatively; its target high is never credited. Gaps can lose more than planned risk. These are simulated results, not exchange fills.</p>
  <p className="text-xs text-slate-400">All paper prices and levels below are USD. Conversion costs are model estimates; no cross-exchange transfers or real orders occur. OKX stops and targets are fixed USD levels. Historical conversion uses matching 15-minute USDT/USD candles: possible stops and gap losses are charged conservatively; targets require a lower bound proving the level was reached. This can overstate stop hits or miss targets; it is not exact cross-exchange execution. Missing conversion history blocks monitoring and new entries. A USDT deviation over 2% blocks new OKX entries, while exits continue.</p>
  </details>
  {p&&<>
   <CryptoPaperStats stats={data?.stats} exitPlans={data?.exitPlans} openRiskUsd={p?openRiskUsd:null} openRiskCapPct={data?.limits?.openRiskPct??null} equity={p?.totalEquity??null} clusterCapPct={data?.limits?.clusterRiskPct??null} />
   {data?.reconciliation&&<section aria-label="Paper account reconciliation" className="rounded border border-slate-700 p-3">
    <h3>Account reconciliation: {data.reconciliation.status}</h3>
    <p>Read-only check against starting cash, open-position costs and all closed trades. No balancing adjustment is made. Tolerance: $0.05.</p>
    {data.reconciliation.expectedCash!==undefined&&<p>Expected cash {money(data.reconciliation.expectedCash)} · Expected equity {money(data.reconciliation.expectedEquity!)} · Cash difference {money(data.reconciliation.cashDifference!)} · Equity difference {money(data.reconciliation.equityDifference!)} · Realised difference {money(data.reconciliation.realisedDifference!)}</p>}
    <p>Closed trades checked: {data.reconciliation.closedTrades??'—'} · Closed-trade fees: {data.reconciliation.closedFees===undefined?'—':money(data.reconciliation.closedFees)} · Open entry fees: {data.reconciliation.openEntryFees===undefined?'—':money(data.reconciliation.openEntryFees)} · Closed-trade mismatches: {data.reconciliation.invalidClosedTrades??'—'}</p>
    <p>{data.reconciliation.reason??'A matched ledger does not prove execution quality or profitability. Checks use a consistent account snapshot.'}</p>
   </section>}
   <details><summary>Recent setup decisions ({decisions.length})</summary>
    {!decisions.length?<p>Decision records appear after the next entry cycle.</p>:<div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Coin / venue','Sleeve','Decision','Reason','Observed bid / ask (USD)','Quote time','Checked'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{decisions.slice(0,100).map((d,i)=><tr key={i}><td>{d.coin} · {d.venue} · {d.product}</td><td>{d.sleeve==='live'?'Live · SIMULATED':d.sleeve==='research'?'Research · SIMULATED':d.sleeve==='base'?'Base breakout · SIMULATED':'—'}</td><td>{d.status}</td><td>{d.reason}</td><td>{d.bid??'Not requested'} / {d.ask??'Not requested'}{d.conversion&&<><br/>USDT/USD {d.conversion.bid} / {d.conversion.ask}<br/>FX at {d.conversion.at}</>}</td><td>{d.quoteAt??'—'}</td><td>{new Date(d.checkedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
   </details>
   <h3 className="font-semibold">Research sleeve · SIMULATED · open positions ({data!.positions.length})</h3>
   {!data!.positions.length?<p>No open paper positions. Entries require a qualifying setup and a valid current entry price.</p>:<PositionsTable positions={data!.positions} trending={data!.trending} giveBack={data!.giveBack}/>}
   <BookGiveBack view={data?.giveBack}/><ShadowLock lock={data?.lock}/><SignalLedger view={data?.signalLedger}/>
   <p><a href="/api/admin/crypto-markets/paper?format=csv" className="underline">Download full trade log (CSV)</a> <span className="text-xs text-slate-400">Every paper entry: why it was taken (setup, signal, volume, BTC trend, funding, correlation, liquidity cap), its levels and size, and the outcome, including the shadow exit plan. SIMULATED.</span></p>
   <h3 className="font-semibold">Live sleeve · SIMULATED · open positions ({data?.live?.positions?.length??0})</h3>
   {!data?.live?.portfolio?<p>Live sleeve is created with the research account. It stays empty until a cycle accepts an entry.</p>:!data.live.positions?.length?<p>No open live-sleeve positions. Equity {money(data.live.portfolio.totalEquity)} · Cash {money(data.live.portfolio.currentCash)}. SIMULATED. No exchange orders.</p>:<><p>Equity {money(data.live.portfolio.totalEquity)} · Cash {money(data.live.portfolio.currentCash)} · SIMULATED</p><PositionsTable positions={data.live.positions} giveBack={data.live.giveBack}/><BookGiveBack view={data.live.giveBack}/><ShadowLock lock={data.live.lock}/></>}
   <h3 className="font-semibold">Base-breakout sleeve · SIMULATED · open positions ({data?.base?.positions?.length??0})</h3>
   <p className="text-xs text-slate-400">The early setup: first confirmed 4h breakout closing 0–3% above a saved daily base high. Separate $200,000 ledger. Exit is a 2-ATR trailing stop ratcheted on completed candles, the structural initial stop, and a {data?.base?.limits?.timeStopHours??168}h time stop only if +1R was never reached; there is no fixed target. Stops shown are the initial stops; the trail is applied by the cycle from stored candles. Jev shadow, chart confirmer and catalyst are recorded with each entry, never gates.</p>
   {!data?.base?.portfolio?<p>Base sleeve is created when the paper account is enabled. It stays empty until a daily base breaks out on a confirmed 4h candle.</p>:<>
    <p>Entries {data.base.portfolio.status} · Equity {money(data.base.portfolio.totalEquity)} · Cash {money(data.base.portfolio.currentCash)} · Realised {money(data.base.portfolio.realisedPnl)} · Open P&amp;L {money(data.base.portfolio.unrealisedPnl)} · SIMULATED</p>
    {!data.base.positions?.length?<p className="text-sm text-slate-400">No open base-breakout positions.</p>:<PositionsTable positions={data.base.positions}/>}
    {!!data.base.trades?.length&&<details><summary className="cursor-pointer text-sm">Base-breakout closed trades ({data.base.trades.length})</summary><div className="overflow-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{['Coin','Entry','Exit','Net P&L','R','Reason','Closed at'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.base.trades.map(x=><tr key={x.id} className="border-t border-slate-700"><td className="p-2">{x.symbol}</td><td className="p-2">{x.entryPrice.toPrecision(6)}</td><td className="p-2">{x.exitPrice.toPrecision(6)}</td><td className="p-2">{money(x.realisedPnl)}</td><td className="p-2">{x.rMultiple?.toFixed(2)??'—'}</td><td className="p-2">{x.exitReason==='RULE_EXIT'?'TRAIL_STOP':x.exitReason}</td><td className="p-2">{new Date(x.exitTime).toLocaleString()}</td></tr>)}</tbody></table></div></details>}
   </>}
   <h3 className="font-semibold">Research sleeve · SIMULATED · closed paper trades (latest 100)</h3>
   {!data!.trades.length?<p>No closed trades yet.</p>:<div className="overflow-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr>{['Coin','Entry','Exit','Net P&L','R','Reason','Closed at'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data!.trades.map(x=><tr key={x.id} className="border-t border-slate-700"><td className="p-2">{x.symbol}</td><td className="p-2">{x.entryPrice.toPrecision(6)}</td><td className="p-2">{x.exitPrice.toPrecision(6)}</td><td className="p-2">{money(x.realisedPnl)}</td><td className="p-2">{x.rMultiple?.toFixed(2)??'—'}</td><td className="p-2">{x.exitReason}</td><td className="p-2">{new Date(x.exitTime).toLocaleString()}</td></tr>)}</tbody></table></div>}
  </>}
 </section>;
}
