import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — MarketScanner Pros",
  description: "Terms of Service for MarketScanner Pros.",
  alternates: { canonical: "/terms" },
  robots: { index: false, follow: true }
};

const effective = "13 December 2025";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--msp-bg)] px-4 py-16 text-slate-200">
      <div className="mx-auto max-w-[800px]">
        <div className="rounded-3xl border border-emerald-500/20 bg-[var(--msp-card)] p-8 shadow-2xl md:p-12">
          <div className="prose prose-invert prose-emerald max-w-none prose-headings:text-slate-100 prose-a:text-emerald-400 prose-strong:text-slate-200">
      <h1 className="text-emerald-400">Terms of Service</h1>
      <p><strong>Effective Date:</strong> {effective}</p>

      <p>
        Welcome to MarketScanner Pros (&ldquo;the App&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;). By accessing or using the
        App, you agree to these Terms of Service. Please read them carefully.
      </p>

      <nav className="my-6 rounded-xl border border-emerald-500/20 bg-emerald-500/10 px-6 py-4">
        <strong className="mb-2 block text-emerald-500">On this page</strong>
        <div className="text-slate-400 leading-relaxed">
          <a href="#eligibility">Eligibility</a> · <a href="#use">Use</a> · <a href="#paper">Paper Trade System</a> · <a href="#ai">AI Content</a> · <a href="#billing">Subscriptions</a> · <a href="#ip">IP</a> · <a href="#warranty">Warranties</a> · <a href="#liability">Liability</a> · <a href="#privacy">Privacy &amp; Cookies</a> · <a href="#termination">Termination</a> · <a href="#governing">Governing Law</a> · <a href="#disputes">Disputes</a> · <a href="#changes">Changes</a> · <a href="#contact">Contact</a>
        </div>
      </nav>

      <h2 id="eligibility">1. Eligibility</h2>
      <p>You must be at least 16 years old to use the App. By using it, you confirm that you meet this requirement.</p>

      <h2 id="use">2. Use of the App</h2>
      <ul>
        <li>The App is provided for educational purposes only.</li>
        <li><strong className="text-amber-500">We do not provide financial, investment, or trading advice.</strong></li>
        <li>ARCA AI chatbot (powered by OpenAI GPT-4) provides educational insights only, not financial advice.</li>
        <li>AI responses may contain errors or inaccuracies. Always verify information independently.</li>
        <li>AI usage is subject to daily limits based on your subscription tier (5/50/unlimited questions per day).</li>
        <li>You are solely responsible for your trading and investment decisions.</li>
      </ul>

      <h2 id="paper">2A. Paper Trade &amp; Simulation System</h2>
      <ul>
        <li>The App is an <strong className="text-amber-500">educational paper trade simulation system</strong>. No feature of the App executes real trades, connects to live brokerage accounts, or places orders on any exchange.</li>
        <li>The portfolio tracker, trade journal, risk governor, scenario plans, and all analysis outputs are for educational and simulated paper trading purposes only.</li>
        <li>Scores, alignment readings, confluence percentages, and scenario analyses reflect indicator agreement and technical pattern recognition &mdash; they do not represent profit probability, guaranteed outcomes, or trading instructions.</li>
        <li>Edge Profile insights are derived from your own journal data and reflect historical patterns only. Past performance does not guarantee future results.</li>
        <li><strong className="text-amber-500">MarketScanner Pros does not hold an Australian Financial Services Licence (AFSL)</strong> and is not authorised to provide personal or general financial product advice under the Corporations Act 2001 (Cth).</li>
      </ul>

      <h2 id="ai">2B. AI-Generated Content</h2>
      <ul>
        <li>ARCA AI (powered by OpenAI GPT-4) generates educational insights only. Outputs are not financial advice and may contain errors, inaccuracies, or outdated information.</li>
        <li>AI responses are generated by large language models using statistical pattern matching &mdash; they are not predictions and should not be relied upon for any financial decisions.</li>
        <li>We do not warrant the accuracy, completeness, or reliability of any AI-generated content. You must independently verify all information before acting on it.</li>
        <li>Personalisation features (Edge Profile, Adaptive Personality, scenario analysis) use your historical data to surface analytical patterns, not to recommend specific trades or strategies.</li>
        <li>AI usage is subject to daily limits based on your subscription tier.</li>
      </ul>

      <h2 id="billing">3. Subscriptions &amp; Billing</h2>
      <ul>
        <li>The App offers Free, Pro ($39.99/mo), and Pro Trader ($89.99/mo) plans.</li>
        <li>Payments are processed securely via Stripe (web/Android) or Apple In-App Purchase (iOS).</li>
        <li><strong>Free Plan:</strong> Limited to Top 10 equities and Top 10 crypto symbols. Includes 5 AI questions per day with ARCA AI.</li>
        <li><strong>Pro Plan ($39.99/mo):</strong> Unlimited symbol scanning, 50 AI questions per day, CSV exports, advanced charts, and priority support.</li>
        <li><strong>Pro Trader Plan ($89.99/mo):</strong> Unlimited AI questions, real Alpha Vantage backtesting, TradingView script access, and premium support.</li>
        <li><strong>Email Required:</strong> You must provide a valid email address to verify trial eligibility.</li>
        <li><strong>One Trial Per Email:</strong> Each email address is eligible for one free trial per plan. Using multiple emails or accounts to access repeated trials is prohibited and may result in account termination.</li>
        <li>After your trial period ends, you will be automatically charged the monthly subscription fee unless you cancel before the trial expires.</li>
        <li>Subscriptions renew automatically until cancelled through your account, Stripe Customer Portal, or app store settings.</li>
        <li><strong>Refunds:</strong> We offer a 7-day money-back guarantee. See our <a href="/refund-policy">Refund Policy</a> for details.</li>
        <li><strong>Trial Abuse Prevention:</strong> We track trial usage by email address and device to prevent abuse. Attempting to circumvent trial limitations may result in immediate subscription termination without refund.</li>
      </ul>

      <h2 id="ip">4. Intellectual Property</h2>
      <p>
        All content, features, and code within the App are owned by MarketScanner Pros. You may not
        copy, modify, distribute, or resell without prior written permission.
      </p>

      <h2 id="warranty">5. Disclaimer of Warranties</h2>
      <p>
        The App is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee accuracy,
        completeness, or uninterrupted access.
      </p>

      <h2 id="liability">6. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, MarketScanner Pros shall not be liable for any losses
        or damages arising from use of the App, including but not limited to trading losses.
      </p>

      <h2 id="privacy">7. Privacy &amp; Cookies</h2>
      <p>Our use of your data is governed by our <a href="/privacy">Privacy Policy</a>.</p>
      <p>Our use of cookies and tracking technologies is explained in our <a href="/cookie-policy">Cookie Policy</a>.</p>

      <h2 id="termination">8. Termination</h2>
      <p>We may suspend or terminate your access if you violate these Terms. You may stop using the App at any time.</p>

      <h2 id="governing">9. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the laws of <strong>New South Wales, Australia</strong>, without regard to its conflict of law provisions.
        You agree to submit to the personal and exclusive jurisdiction of the courts located in New South Wales, Australia for resolution of any disputes.
      </p>
      <p>
        Nothing in these Terms excludes, restricts or modifies any consumer rights under the <em>Australian Consumer Law</em> (Schedule 2 of the Competition and Consumer Act 2010 (Cth)) or equivalent legislation that cannot be excluded.
      </p>

      <h2 id="disputes">10. Dispute Resolution</h2>
      <p>
        Any dispute arising from these Terms or your use of the App shall first be attempted to be resolved through informal negotiation by contacting us at <a href="mailto:support@marketscannerpros.app">support@marketscannerpros.app</a>.
      </p>
      <p>
        If informal resolution is unsuccessful within 30 days, either party may pursue mediation administered by the Australian Disputes Centre (ADC) in Sydney, NSW. If mediation is unsuccessful, disputes may be resolved by binding arbitration or in the courts of New South Wales.
      </p>
      <p>
        <strong className="text-amber-500">Class Action Waiver:</strong> To the extent permitted by law, you agree to resolve disputes only on an individual basis and waive any right to participate in class actions or representative proceedings.
      </p>

      <h2 id="indemnification">11. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless MarketScanner Pros, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, or expenses (including legal fees) arising from your use of the App, violation of these Terms, or infringement of any third-party rights.
      </p>

      <h2 id="changes">12. Changes</h2>
      <p>We may update these Terms occasionally. Changes will be posted on this page with a revised effective date.</p>

      <h2 id="contact">13. Contact</h2>
      <p>
        For questions, please email us at:<br />
        📧 <a href="mailto:support@marketscannerpros.app">support@marketscannerpros.app</a>
      </p>

          </div>
        </div>
      </div>
    </main>
  );
}
