export const metadata = {
  title: "Disclaimer — MarketScanner Pros",
  alternates: { canonical: "/disclaimer" }
};

const effective = "13 December 2025";

export default function DisclaimerPage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: 'radial-gradient(circle at top, #111827 0, #020617 55%, #000 100%)',
      color: '#f9fafb',
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", sans-serif',
      padding: '48px 20px 60px'
    }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <h1 style={{ fontSize: 36, fontWeight: 700, marginBottom: 16, color: '#f9fafb' }}>Disclaimer</h1>
        <p style={{ fontSize: 14, color: '#9ca3af', marginBottom: 24 }}><strong style={{ color: '#cbd5e1' }}>Effective Date:</strong> {effective}</p>
        
        <nav style={{
          margin: '24px 0',
          padding: '16px 20px',
          border: '1px solid #1f2933',
          borderRadius: 12,
          background: 'rgba(15, 23, 42, 0.5)'
        }}>
          <strong style={{ display: 'block', marginBottom: 8, color: '#f9fafb', fontSize: 14 }}>On this page</strong>
          <div style={{ fontSize: 13, color: '#9ca3af', display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <a href="#edu" style={{ color: '#22c55e', textDecoration: 'none' }}>Educational use</a>
            <span>·</span>
            <a href="#risk" style={{ color: '#22c55e', textDecoration: 'none' }}>Market risk</a>
            <span>·</span>
            <a href="#accuracy" style={{ color: '#22c55e', textDecoration: 'none' }}>Data & accuracy</a>
            <span>·</span>
            <a href="#delay" style={{ color: '#22c55e', textDecoration: 'none' }}>Data delays</a>
            <span>·</span>
            <a href="#paper" style={{ color: '#22c55e', textDecoration: 'none' }}>Paper trade system</a>
            <span>·</span>
            <a href="#backtests" style={{ color: '#22c55e', textDecoration: 'none' }}>Backtests</a>
            <span>·</span>
            <a href="#jurisdiction" style={{ color: '#22c55e', textDecoration: 'none' }}>Jurisdiction</a>
            <span>·</span>
            <a href="#liability" style={{ color: '#22c55e', textDecoration: 'none' }}>Liability</a>
            <span>·</span>
            <a href="#contact" style={{ color: '#22c55e', textDecoration: 'none' }}>Contact</a>
          </div>
        </nav>

        <section style={{ marginTop: 32 }}>
          <h2 id="edu" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Educational Use Only</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            MarketScanner Pros ("the App") is provided for educational and informational purposes.
            We are not a broker, dealer, or investment adviser, and nothing here is financial,
            investment, or trading advice.
          </p>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6, marginTop: 12 }}>
            <strong style={{ color: '#f59e0b' }}>MarketScanner Pros does not hold an Australian Financial Services Licence (AFSL)</strong> and is not authorised to provide personal or general financial product advice under the Corporations Act 2001 (Cth). 
            All scanner outputs, scores, signals, AI-generated insights, and analytics are general information only and do not take into account your personal objectives, financial situation, or needs. 
            You should obtain independent financial advice from a licensed adviser before making any investment decisions.
          </p>
        </section>

        <section>
          <h2 id="risk" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Market Risk</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Trading and investing involve substantial risk. You may lose part or all of your capital.
            You are solely responsible for your decisions.
          </p>
        </section>

        <section>
          <h2 id="accuracy" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Data, Signals, AI & Accuracy</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Scores, indicators, signals, and AI-generated insights (ARCA AI powered by GPT-4) may be incomplete, 
            delayed, or inaccurate. Market data is sourced from Alpha Vantage Premium API. Availability can be 
            affected by third-party providers. AI responses are generated by large language models and are for 
            educational purposes only — they do not constitute financial advice and should not be relied upon for 
            trading decisions. No accuracy, completeness, or uptime guarantees are made.
          </p>
        </section>

        <section>          <h2 id="delay" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Data Delays &amp; Third-Party Sources</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Market data is sourced from Alpha Vantage Premium API and may be delayed by 15 minutes or more 
            depending on the asset class and exchange. Real-time data availability varies by provider and plan. 
            Options data, derivatives data, and certain crypto metrics may have additional delays. 
            We do not guarantee real-time data delivery and are not responsible for delays, interruptions, 
            or inaccuracies in third-party data feeds.
          </p>
        </section>

        <section>
          <h2 id="paper" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Paper Trade &amp; Simulation System</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            MarketScanner Pros is an educational paper trade simulation system. The portfolio tracker, 
            trade journal, risk governor, scenario plans, and all analysis outputs are designed for 
            educational purposes and simulated paper trading only. No feature of this platform executes 
            real trades, connects to live brokerage accounts, or places orders on any exchange.
          </p>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6, marginTop: 12 }}>
            Scores, alignment readings, confluence percentages, and scenario analyses reflect indicator 
            agreement and technical pattern recognition — they do not represent profit probability, 
            guaranteed outcomes, or trading instructions. All users are solely responsible for any 
            decisions they make with their own capital outside this platform.
          </p>
        </section>

        <section>          <h2 id="backtests" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Backtests & Historical Data</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Backtesting features use real historical data from Alpha Vantage Premium. However, backtested results 
            are hypothetical, do not reflect actual trading, and are for illustration only. They do not account for 
            slippage, commissions, liquidity, or market impact. Past results do not predict or guarantee future 
            outcomes. Market conditions change and historical patterns may not repeat. No backtested strategy 
            should be interpreted as a recommendation to trade.
          </p>
        </section>

        <section>
          <h2 id="jurisdiction" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Jurisdiction & Compliance</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            You are responsible for complying with the laws and regulations of your jurisdiction.
            The App does not solicit or target any specific country's investors.
          </p>
        </section>

        <section>
          <h2 id="liability" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Liability</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Use the App at your own risk. See our <a href="/terms" style={{ color: '#22c55e', textDecoration: 'none' }}>Terms of Service</a> for limitations
            of liability and other important terms.
          </p>
        </section>

        <section>
          <h2 id="contact" style={{ fontSize: 22, fontWeight: 650, marginBottom: 12, marginTop: 24, color: '#f9fafb' }}>Contact</h2>
          <p style={{ fontSize: 14, color: '#9ca3af', lineHeight: 1.6 }}>
            Questions? Email <a href="mailto:support@marketscannerpros.app" style={{ color: '#22c55e', textDecoration: 'none' }}>support@marketscannerpros.app</a>.
          </p>
        </section>
      </div>
    </main>
  );
}