[server]
headless = true
address = "0.0.0.0"
port = 8080
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
fileWatcherType = "none"
runOnSave = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[global]
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false
