[theme]
base = "dark"
primaryColor = "#10B981"                 # emerald
backgroundColor = "#0B0F14"              # page bg
secondaryBackgroundColor = "#111827"     # card bg
textColor = "#E5E7EB"
font = "sans serif"
