[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
fileWatcherType = "none"
runOnSave = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[global]
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[theme]
base = "dark"
primaryColor = "#10B981"                 # emerald
backgroundColor = "#0B0F14"              # page bg
secondaryBackgroundColor = "#111827"     # card bg
textColor = "#E5E7EB"
font = "sans serif"
